package scraper_test

import (
	"testing"
	"time"

	"github.com/reaper47/recipya/internal/models"
)

func TestScraper_E(t *testing.T) {
	testcases := []testcase{
		{
			name: "eatingbirdfood.com",
			in:   "https://www.eatingbirdfood.com/cinnamon-rolls/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Breakast"},
				CookTime:      "PT25M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2022-12-15T08:05:22+00:00",
				Description: &models.Description{
					Value: "Make cinnamon rolls from scratch with this easy recipe that&#039;s perfect for beginners! They&#039;re soft, gooey, and made with bread flour, which gives them the perfect fluffy texture. Overnight instructions included.",
				},
				Keywords: &models.Keywords{Values: "cinnamon rolls"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 0.25 oz. pkg. active dry yeast",
						"1 cup warm milk (around 105°–115°F)",
						"3 cups bread flour (plus more for rolling dough)",
						"1 teaspoon sea salt",
						"2 Tablespoons granulated sugar",
						"3 Tablespoons unsalted butter, melted (plus more for greasing)",
						"1 large egg (at room temperature)",
						"½ cup brown sugar (packed )",
						"1 Tablespoon ground cinnamon",
						"¼ cup unsalted butter (softened)",
						"4 oz cream cheese (full fat, softened to room temperature)",
						"3 Tablespoons unsalted butter (softened to room temperature)",
						"¼ teaspoon vanilla extract",
						"1 cup powdered sugar",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Heat milk in a saucepan or in the microwave (about 40-50 seconds) until warm, but not hot. Around (105°–115°F). Stir yeast into warm almond milk until dissolved. Let stand 10 minutes."},
						{Type: "HowToStep", Text: "In a stand mixer with the paddle attachment, add flour, salt and sugar. Mix to combine. With mixer running at low speed, add melted butter, egg and yeast mixture. Increase speed to medium-low, and mix 2 minutes until dough starts to form."},
						{Type: "HowToStep", Text: "Switch to the dough hook attachment and knead the dough in the stand mixer at medium-low speed for 5 minutes, or until dough is smooth. Increase speed to medium and mix 2 minutes. Kneading is done when dough makes a slapping sound as it hits the side of the bowl. Dough temperature should be close to 90°F. If dough is too sticky add a little more flour."},
						{Type: "HowToStep", Text: "Once combined, place dough in oiled mixing bowl and cover with plastic wrap and a warm towel. Let rise 1-2 hours, or until doubled in volume. Time will depend on how warm your house is."},
						{Type: "HowToStep", Text: "While dough is rising, make cinnamon sugar filling by stirring together brown sugar and cinnamon in a small bowl. Grease 13 x 9-inch baking pan or round 9.5-inch pie pan with butter."},
						{Type: "HowToStep", Text: "Once dough has doubled in size, sprinkle extra flour on your surface and rolling pin and roll dough into 14 x 12-inch rectangle."},
						{Type: "HowToStep", Text: "Spread softened butter onto dough with your fingers or a knife."},
						{Type: "HowToStep", Text: "Sprinkle cinnamon sugar mixture over butter and press down slightly with your hands."},
						{Type: "HowToStep", Text: "Starting at the top, roll the dough toward you into a large log, moving back and forth down the line of dough (in a “typewriter” motion) and always rolling toward you. Roll it tightly as you go so the rolls will be nice and neat. When it’s all rolled, pinch the seam closed and turn the roll over so that the seam is facing down. Cut roll crosswise into 12 1-inch-thick pieces and place on prepared baking pan."},
						{Type: "HowToStep", Text: "Cover, and let rise in warm place 45 minutes, or until doubled in size."},
						{Type: "HowToStep", Text: "Preheat oven to 350°F. Bake cinnamon rolls for 20-25 minutes, or until golden brown, cooked through and no longer doughy. I baked mine for 22 minutes."},
						{Type: "HowToStep", Text: "While cinnamon rolls are cooling, make cream cheese frosting by adding softened cream cheese and butter and vanilla to a mixing bowl. Using a hand mixer or stand mixer on medium speed, whip the ingredients together until smooth and fluffy, scraping down the sides as needed. Then, add the powdered sugar ¼ cup at a time, mixing in between, until fully combined and smooth."},
						{Type: "HowToStep", Text: "Spread frosting over warm cinnamon rolls and serve."},
					},
				},
				Name: "Fluffy Cinnamon Rolls",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "269",
					Carbohydrates:  "37",
					Cholesterol:    "43",
					Fat:            "11",
					Fiber:          "1",
					Protein:        "6",
					SaturatedFat:   "6",
					Servings:       "1",
					Sodium:         "252",
					Sugar:          "14",
					UnsaturatedFat: "3",
				},
				PrepTime:  "PT30M",
				TotalTime: "PT175M",
				Yield:     &models.Yield{Value: 12},
				URL:       "https://www.eatingbirdfood.com/cinnamon-rolls/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:       "VideoObject",
							ContentURL:   "https://content.jwplatform.com/videos/ZCg18AzV.mp4",
							Description:  "Make cinnamon rolls from scratch with this easy recipe that's perfect for beginners! They're soft, gooey, and made with bread flour, which gives them the perfect fluffy texture. Overnight instructions included.",
							Name:         "Fluffy Cinnamon Rolls",
							ThumbnailURL: &models.ThumbnailURL{Value: "https://content.jwplatform.com/thumbs/ZCg18AzV-720.jpg"},
							UploadDate:   time.Date(2022, 3, 30, 13, 0, 0, 0, time.UTC),
						},
					},
				},
			},
		},
		{
			name: "eatingwell.com",
			in:   "https://www.eatingwell.com/recipe/7887715/lemon-chicken-piccata/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				DateModified:  "2024-04-18T13:12:56.664-04:00",
				DatePublished: "2021-02-04T15:20:10.000-05:00",
				Description: &models.Description{
					Value: "This chicken piccata recipe has a bright, briny flavor, is made from ingredients you likely have on hand, and goes with everything from chicken to tofu to scallops. Bonus: It&#39;s lower in calories than a lot of other pan sauces.",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1.25 pounds boneless, skinless chicken breasts, trimmed",
						".5 teaspoon salt",
						".25 teaspoon ground pepper",
						"2 tablespoons extra-virgin olive oil",
						"1 medium shallot, minced",
						"3 cloves garlic, minced",
						"2 teaspoons all-purpose flour",
						".5 cup low-sodium chicken broth",
						".5 cup dry white wine",
						"2 tablespoons lemon juice",
						"1 tablespoon butter",
						"1 tablespoon capers, rinsed",
						"2 tablespoons chopped fresh parsley",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Remove tenders from chicken and reserve for another use. Place the chicken breasts between 2 pieces of plastic wrap and gently pound with a meat mallet, rolling pin or small skillet to an even thickness of about ½ inch. Pat the chicken dry and sprinkle with salt and pepper."},
						{Type: "HowToStep", Text: "Heat oil in a large skillet over medium-high heat. Add the chicken and cook, flipping once, until well browned on both sides, 6 to 8 minutes. Continue to cook, flipping often, until an instant-read thermometer inserted in the thickest part registers 165°F, about 3 minutes more. Transfer to a clean cutting board and tent with foil to keep warm."},
						{Type: "HowToStep", Text: "Reduce heat to medium and add shallot to the pan. Cook, stirring often, until softened, 1 to 2 minutes. Add garlic and cook, stirring, until fragrant, about 1 minute. Sprinkle with flour and cook, stirring, for 1 minute. Stir in broth and wine, scraping up any browned bits. Simmer until reduced by half, 3 to 5 minutes. Remove from heat and stir in lemon juice, butter, capers and parsley. Serve the chicken with the sauce."},
					},
				},
				Name: "Lemon Chicken Piccata",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "264",
					Carbohydrates:  "7",
					Cholesterol:    "70",
					Fat:            "13",
					Protein:        "24",
					SaturatedFat:   "4",
					Sodium:         "382",
					Sugar:          "1",
					UnsaturatedFat: "0",
				},
				TotalTime: "PT20M",
				Yield:     &models.Yield{Value: 4},
				URL:       "https://www.eatingwell.com/recipe/7887715/lemon-chicken-piccata/",
			},
		},
		{
			name: "eatliverun.com",
			in:   "https://www.eatliverun.com/dinner-cheap-garlickly-greens-beans/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main Course"},
				CookTime:      "PT4M",
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DatePublished: "2017-05-18T05:31:11+00:00",
				Description:   &models.Description{},
				Keywords:      &models.Keywords{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 cup dried lima beans",
						"1 large bunch dark leafy greens (such as collard greens or kale, roughly chopped)",
						"4 tbsp extra virgin olive oil", "3 cloves garlic (minced)", "kosher salt",
						"freshly ground black pepper",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "To quick soak your beans like I usually do, just place beans in a large pot and cover with water. Bring to a high boil and boil for 3 minutes. Turn off burner, cover pot and let beans rest for an hour. After an hour, drain beans and add fresh water with plenty of salt. Bring to a simmer and cook until beans are soft, about 40 minutes."},
						{Type: "HowToStep", Text: "After your beans have cooked, drain them gently (lima beans get really soft so be careful not to crush them). Add three tablespoons of the olive oil in a large saute pan over medium heat."},
						{Type: "HowToStep", Text: "Add minced garlic and saute for 30 seconds. Add leafy greens and saute for another minute. Stir in beans. Season to taste with salt and pepper and drizzle additional olive oil over top."},
					},
				},
				Name:            "Garlicky Beans & Greens",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT90M",
				ThumbnailURL:    &models.ThumbnailURL{},
				TotalTime:       "PT94M",
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 3},
				URL:             "https://www.eatliverun.com/dinner-cheap-garlickly-greens-beans/",
				Video:           &models.Videos{},
			},
		},
		{
			name: "eatsmarter.com",
			in:   "https://eatsmarter.com/recipes/vietnamese-chicken-cabbage-salad",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Lunch"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{Value: "Asian, Vietnamese"},
				DatePublished: "2016-10-07",
				Description: &models.Description{
					Value: "Light and refreshing Vietnamese Chicken Cabbage Salad with crunchy peanuts",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"24 ozs Chicken broth",
						"22 ozs Chicken breasts",
						"3  carrots (10-12 ounces)",
						"1 bunch Radish",
						"1 Red chili pepper",
						"1  Chinese cabbage",
						"1 bunch mixed Fresh herbs (such as mint, basil)",
						"1  Lime",
						"3 Tbsps chopped Peanuts",
						"2 Tbsps vegetable oil",
						"peppers",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Bring broth to a boil, add chicken and simmer for about 20 minutes on low heat."},
						{Type: "HowToStep", Text: "Peel carrots and cut into thin, long strips. Rinse and dry radishes, cut into thin slices. Rinse and chop chile pepper."},
						{Type: "HowToStep", Text: "Rinse and dry cabbage, cut into fine strips. Rinse and shake dry herbs, pluck off leaves."},
						{Type: "HowToStep", Text: "Remove chicken from broth and cool. Squeeze lime juice."},
						{Type: "HowToStep", Text: "Cut meat into thin strips, mix with prepared vegetables and herbs, drizzle with lime juice and oil, season with salt and pepper and sprinkle with nuts. Serve."},
					},
				},
				Keywords:        &models.Keywords{},
				Name:            "Vietnamese Chicken Cabbage Salad",
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				TotalTime:       "PT40M",
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 4},
				URL:             "https://eatsmarter.com/recipes/vietnamese-chicken-cabbage-salad",
				Video:           &models.Videos{},
			},
		},
		{
			name: "eatwell101.com",
			in:   "https://www.eatwell101.com/garlic-parmesan-marinated-mushrooms-recipe",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateModified:  "2023-06-18T14:01:38+00:00",
				DatePublished: "2023-06-16T22:24:57+00:00",
				Description: &models.Description{
					Value: "This marinated mushroom recipe is the perfect appetizer or side for any occasion. Enjoy the delicious flavor and texture of these mushrooms marinated in olive oil, parmesan, garlic, and herbs! CLICK HERE to Get the Recipes",
				},
				Keywords: &models.Keywords{
					Values: "Garlic Parmesan Marinated Mushrooms Recipe, Easy marinated Mushrooms, how to marinate mushrooms",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 lb (450g) mushrooms, sliced", "1/3 cup grated parmesan",
						"4 clove garlic, minced", "1/2 teaspoon black pepper",
						"2 tablespoons chopped parsley", "1/2 cup olive oil",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "1. To make the garlic parmesan marinated mushrooms: In a small bowl, combine minced garlic, grated parmesan, chopped parsley, and olive oil."},
						{Type: "HowToStep", Text: "2. Arrange the sliced mushrooms on a large shallow plate, and pour the olive oil-parmesan mixture on top. Toss gently to coat the mushrooms and marinate for at least 30 minutes."},
						{Type: "HowToStep", Text: "3. Serve the parmesan mushroom dip with toasted bread, crackers, tortilla chips, or pita chips. Enjoy! ❤️"},
						{Type: "HowToStep", Text: "Photo credit: © Eatwell101.com"},
						{Type: "HowToStep", Text: "More mushroom recipes"},
					},
				},
				Name:            "Olive Garlic Parmesan Marinated Mushrooms",
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{},
				URL:             "https://www.eatwell101.com/garlic-parmesan-marinated-mushrooms-recipe",
				Video:           &models.Videos{},
			},
		},
		{
			name: "eatwhattonight.com",
			in:   "https://eatwhattonight.com/2021/11/diced-chicken-with-spicy-chilies-%e8%be%a3%e5%ad%90%e9%b8%a1%e4%b8%81/#wpzoom-recipe-card",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Sides"},
				CookingMethod: &models.CookingMethod{},
				CookTime:      "PT20M",

				Cuisine:       &models.Cuisine{Value: "Chinese"},
				DatePublished: "2021-11-30T13:14:26+08:00",
				Description:   &models.Description{Value: ""},
				Keywords:      &models.Keywords{Values: "Chicken"},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"150g diced boneless chicken leg, de-skinned",
						"12 pcs dried chilies, soaked in water to soften, cut into sections",
						"2 tbsp cooking oil",
						"1 tsp Szechuan peppercorns",
						"2 small bulbs of garlic, sliced",
						"5-6 thin slices of ginger",
						"2-3 tbsp water",
						"1 tbsp cooking wine",
						"Some sesame seeds",
						"1 3/4 tsp light soya sauce",
						"1 tbsp ginger juice",
						"1/2 tsp sugar",
						"Pinch of pepper",
						"4 tsp corn flour",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Marinate chicken, cover and set aside in the fridge for an hour."},
						{Type: "HowToStep", Text: "Heat up 1 tbsp cooking oil and panfry marinated chicken till cooked and remove from flame (helps to release excess oils from chicken)."},
						{Type: "HowToStep", Text: "Add to air-fryer to grill for further 5 mins at 160 degrees C or till browned. Remove and set aside."},
						{Type: "HowToStep", Text: "Heat up balance cooking oil and saute ginger and garlic slices."},
						{Type: "HowToStep", Text: "Add Szechuan pepper and dried chilies and stir-fry to bring out the aroma."},
						{Type: "HowToStep", Text: "Add water if it starts to get too dry. Add chicken pieces and stir-fry to mix well."},
						{Type: "HowToStep", Text: "Add cooking wine and stir-fry till chicken are dry. Off heat and sprinkle sesame seeds all over. Mix well and serve hot immediately to enjoy."},
					},
				},
				Name:            "Diced Chicken with Spicy Chilies 辣子鸡丁",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT10M",
				ThumbnailURL:    &models.ThumbnailURL{},
				TotalTime:       "PT30M",
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 1},
				URL:             "https://eatwhattonight.com/2021/11/diced-chicken-with-spicy-chilies-%e8%be%a3%e5%ad%90%e9%b8%a1%e4%b8%81/#wpzoom-recipe-card",
				Video:           &models.Videos{},
			},
		},
		{
			name: "elavegan.com",
			in:   "https://elavegan.com/vegan-moussaka-lentils-gluten-free/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main Course"},
				CookTime:      "PT50M",
				Cuisine:       &models.Cuisine{Value: "Greek"},
				DatePublished: "2023-11-19T08:13:22+00:00",
				Description: &models.Description{
					Value: "Vegan moussaka with lentils and eggplant! This popular Greek dish can be easily made without meat and still tastes amazing. This healthy casserole is a wonderful comfort meal which is flavorful, satisfying, and very enjoyable. The recipe is plant-based, gluten-free, and fairly easy to make.",
				},
				Keywords: &models.Keywords{Values: "eggplant casserole, lentil moussaka, vegan moussaka"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"2 pounds potatoes (peeled)", "3 large eggplants", "Olive oil (to brush)",
						"Sea salt &amp; pepper (to sprinkle)",
						"3 cups cooked lentils ((about 1 1/2 cups dried))", "2 cups passata",
						"1 cup chopped tomatoes", "1 Tbsp olive oil", "1 large onion (chopped)",
						"2 cloves of garlic (minced)", "2 bay leaves", "1-2 tsp dried thyme",
						"1 tsp oregano", "1 tsp paprika", "1 tsp coconut sugar (or brown sugar)",
						"1 pinch of cinnamon",
						"Sea salt &amp; pepper (to taste)",
						"2 Tbsp vegan butter",
						"2 cups plant-based milk",
						"3 1/2 Tbsp cornstarch",
						"2 Tbsp nutritional yeast",
						"Sea salt &amp; pepper (to taste)",
						"1 pinch of nutmeg",
						"Vegan cheese (to taste (optional))",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Check the video in the post for visual instructions.First, preheat the oven to 390 °F/200 °C and line two baking sheets with parchment paper."},
						{Type: "HowToStep", Text: "Then, slice each eggplant into 4-5 lengthwise slices and the potatoes into ½-inch (1 cm) thick slices."},
						{Type: "HowToStep", Text: "Once sliced, arrange the slices in a single layer across the baking sheets, lightly brush them with olive oil, and sprinkle with salt and pepper."},
						{Type: "HowToStep", Text: "Bake them for 20 minutes or until lightly browned."},
						{Type: "HowToStep", Text: "Meanwhile, peel and chop the onion and mince the garlic while heating a little oil in a large skillet over medium heat."},
						{Type: "HowToStep", Text: "Once hot, sauté the onion and garlic for 4-5 minutes, until translucent."},
						{Type: "HowToStep", Text: "Then add the tomato puree, chopped tomatoes, and all the spices (including salt and pepper to taste). Stir, add the lentils, and let it simmer on low heat for about 5 minutes."},
						{Type: "HowToStep", Text: "Add the plant-based milk to a small saucepan/skillet with the cornstarch, nutritional yeast, salt, and pepper, and whisk well."},
						{Type: "HowToStep", Text: "Then, add the dairy-free butter and bring the mixture to a boil over medium-high heat. Immediately lower to a simmer and stir/whisk constantly until it thickens. Remove it from the heat and set aside."},
						{Type: "HowToStep", Text: "Grease a 9x13-inch (23x33cm) baking dish with vegan butter or oil and arrange half the potato and eggplant slices across the bottom of the dish."},
						{Type: "HowToStep", Text: "Top that with the lentil mixture, followed by the remaining eggplant and potato slices."},
						{Type: "HowToStep", Text: "Pour the bechamel sauce over the top and spread it evenly. Then, optionally, sprinkle some vegan cheese over the top."},
						{Type: "HowToStep", Text: "Transfer the potato eggplant moussaka to the oven to bake for 30 minutes or until golden brown on top with tender eggplant/potato and a bubbling filling. Finally, optionally garnish with herbs, and enjoy!"},
					},
				},
				Name: "Vegan Moussaka",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "400",
					Carbohydrates: "70",
					Fat:           "8",
					Fiber:         "22",
					Protein:       "19",
					SaturatedFat:  "1",
					Servings:      "1",
					Sugar:         "16",
				},
				PrepTime:  "PT30M",
				TotalTime: "PT80M",
				Yield:     &models.Yield{Value: 6},
				URL:       "https://elavegan.com/vegan-moussaka-lentils-gluten-free/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:       "VideoObject",
							ContentURL:   "https://content.jwplatform.com/videos/NYxGgMHa.mp4",
							Description:  "Vegan moussaka with lentils and eggplant! This popular Greek dish can be easily made without meat and still tastes amazing. This healthy casserole is a wonderful comfort meal which is flavorful, satisfying, and very enjoyable. The recipe is plant-based, gluten-free, and fairly easy to make.",
							Name:         "Vegan Moussaka With Lentils",
							ThumbnailURL: &models.ThumbnailURL{Value: "https://content.jwplatform.com/thumbs/NYxGgMHa-720.jpg"},
							UploadDate:   time.Date(2020, 4, 13, 16, 38, 49, 0, time.UTC),
						},
					},
				},
			},
		},
		{
			name: "elephantasticvegan.com",
			in:   "https://www.elephantasticvegan.com/banana-blossom-vegan-fish",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main Course"},
				CookTime:      "PT10M",
				Cuisine:       &models.Cuisine{Value: "Vegan"},
				DatePublished: "2018-10-30T14:00:00+00:00",
				Description: &models.Description{
					Value: "This Vegan Fish made with Banana Blossoms is life-changing - especially if you thought that you would never eat anything tastes like fish again! The soft and flaky texture of the banana flowers is perfect as the base!&nbsp;",
				},
				Keywords: &models.Keywords{Values: "banana blossom vegan fish, vegan fish made with banana blossoms, vegan fish without soy"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 can banana blossoms in brine ((20 oz))",
						"frying oil",
						"1 cup all-purpose flour",
						"1/2 teaspoon salt",
						"1 teaspoon dill",
						"1 1/2 tablespoons crushed nori",
						"1 cup flour",
						"1/2 teaspoon salt",
						"1 pinch turmeric",
						"1 tablespoon pickle juice",
						"1 tablespoon caper brine ((or sub with more pickle juice))",
						"2 teaspoons lemon juice",
						"1/2 cup sparkling water",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Rinse and drain the banana blossoms."},
						{Type: "HowToStep", Text: "In separate bowls, combine the ingredients for the flour mixture and whisk together the ingredients for the batter."},
						{Type: "HowToStep", Text: "In a pot or wok, heat the frying oil. You'll want enough so that the battered banana blossoms can swim in the oil but make sure you leave enough space in the pot/wok so that it doesn't spill over."},
						{Type: "HowToStep", Text: "Coat the banana blossoms in the flour mixture. Then dip them in the batter. Carefully lower them in the oil. Let them fry for about 4-5 minutes until golden brown, flipping them once."},
						{Type: "HowToStep", Text: "Transfer the fried banana blossoms onto a kitchen paper to remove excess oil. Serve with tartar sauce, fries, and mashed peas, for example. Add fresh dill on top and squeeze with lemon juice."},
					},
				},
				Name: "Banana Blossom Vegan Fish",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "160",
					Carbohydrates: "24",
					Fat:           "5",
					Protein:       "3",
					SaturatedFat:  "4",
					Sodium:        "325",
					Servings:      "1",
				},
				PrepTime:  "PT10M",
				TotalTime: "PT20M",
				Yield:     &models.Yield{Value: 8},
				URL:       "https://www.elephantasticvegan.com/banana-blossom-vegan-fish",
			},
		},
		{
			name: "emmikochteinfach.de",
			in:   "https://emmikochteinfach.de/kartoffelgratin-rezept-klassisch-und-einfach/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookTime:      "PT45M",
				DatePublished: "2024-10-03T16:00:40+00:00",
				Description: &models.Description{
					Value: "Das klassische Kartoffelgratin geht ganz einfach. Es schmeckt als leckere Beilage zu Fleisch und Fisch oder als vegetarische Hauptspeise.",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"800 g mittelgroße Kartoffeln (Wichtig: Sorte &quot;vorwiegend festkochend&quot;)",
						"200 ml Kochsahne (15% Fett)",
						"100 g französischer Kräuterfrischkäse (z.B. Bresso, Miree etc.)",
						"100 g geriebener Emmentaler (alternativ Comté, Gruyère oder gar kein Käse)",
						"20 g Butter (in Flöckchen, Stückchen)", "1 TL Butter für die Form",
						"1 TL Salz", "1/2 TL Muskat (frisch gerieben)",
						"1/2 TL schwarzer Pfeffer, gemahlen",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Den Backofen für das Kartoffelgratin rechtzeitig auf 180 Grad Umluft (200 °C Ober- / Unterhitze) vorheizen."},
						{Type: "HowToStep", Text: "Die 800 g Kartoffeln abwaschen, schälen, gegebenenfalls nochmals abwaschen und mit einem scharfen Messer oder Hobel in ca. 2-3 mm dicke Scheiben schneiden."},
						{Type: "HowToStep", Text: "Eine runde oder rechteckige Auflaufform mit ca. 1 TL Butter einfetten und die Kartoffelscheiben dachziegelartig arrangieren."},
						{Type: "HowToStep", Text: "Bei einer runden Auflaufform arbeitest du dich am besten von außen nach innen und schichtest die Kartoffelscheiben schneckenförmig im Kreis. TIPP: Bei rechteckigen Formen an der schmalen Seite beginnen und reihenartig einschichten."},
						{Type: "HowToStep", Text: "Nun verrührst du in einer Schüssel mit einem Schneebesen 200 ml Kochsahne, 100 g Kräuterfrischkäse, 1 TL Salz, 1/2 TL weißen oder schwarzen Pfeffer und 1/2 TL frisch geriebene Muskatnuss."},
						{Type: "HowToStep", Text: "Die Sahne-Frischkäse-Masse gießt du nun gleichmäßig über die Kartoffelscheiben in der Auflaufform und verteilst 20 g Butter in Flöckchen darüber. Die 100 g Emmentaler reibst du frisch mit einer Reibe und verteilst ihn ebenfalls gleichmäßig auf den Kartoffeln. Im vorgeheizten Backofen, auf der mittleren Schiene, ca. 45 Minuten backen."},
						{Type: "HowToStep", Text: "Wenn dir der Käse gegen Ende der Backzeit zu braun wird, das Kartoffelgratin am besten mit Alufolie abdecken. Das fertige Gratin direkt in der Form servieren. Guten Appetit!"},
					},
				},
				Name:      "Kartoffelgratin – einfach und klassisch",
				PrepTime:  "PT15M",
				TotalTime: "PT60M",
				Yield:     &models.Yield{Value: 4},
				URL:       "https://emmikochteinfach.de/kartoffelgratin-rezept-klassisch-und-einfach/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:       "VideoObject",
							ContentURL:   "https://www.youtube.com/watch?v=-w8qtjBq3pM",
							Description:  "Zum einfachen Kartoffelgratin-Rezept: 👉https://emmikochteinfach.de/kartoffelgratin-rezept-klassisch-und-einfach/\n\nMein herzhaftes und einfaches Kartoffelgratin Rezept ist ein herzhaftes Alltagsgericht aus dem Backofen. Es macht sich super als vegetarische Hauptspeise mit einem Salat zum Beispiel, aber natürlich auch als Beilage – je nach Geschmack.\n\n00:00 Begrüßung & Intro\n00:31 Zutaten\n00:56 Rezept\n01:00 Vorbereitung\n01:54 Backofen\n02:09 Welche Kartoffelsorte?\n02:16 Verabschiedung & Outro\n\nWarum ich mein klassisches Kartoffelgratin Rezept so mag?\nRezepte für ein Gratin gibt es viele, das erwartet dich bei meinem einfachen Rezept:\n\n✔️ Mein Kartoffelgratin ist wirklich einfach. In nur 15 Minuten zubereitet, übernimmt dein Backofen die meiste Arbeit. \n✔️ Die wenigen Zutaten, die du für mein alltagstaugliches Rezept brauchst, findest du das ganze Jahr über im Lebensmitteleinzelhandel. 🛒\n✔️ Ich verwende eine leichte Kochsahne – dadurch wird das Kartoffelgratin am Ende nicht zu mächtig. \n✔️ Der französische Kräuterfrischkäse verleiht meinem Rezept eine besondere Würze.\n✔️ Du sparst dir das Vorkochen der Kartoffeln, da sie für meine Variation des Gratins roh verarbeitet werden. Wichtig ist, dass du eine vorwiegend festkochende Kartoffelsorte benutzt. 🥔\n✔️ Mein Rezept ist wie gemacht für Kochanfänger; lediglich ein bisschen Geduld brauchst du beim Schichten der Kartoffelscheiben in der Form. 🧑‍🍳\n✔️ Außer der Auflaufform brauchst du einfach  nur einen Schneebesen und deinen Backofen. 😉\n✔️ Mit einem leckeren Salat ergibt mein einfaches Kartoffelgratin eine leckere vegetarische Hauptspeise.\n\nWillkommen bei EMMI KOCHT EINFACH. Wenn Dir mein Video gefällt, lass mir gerne einen 👍 da. Vergiss auch nicht meinen Kanal zu abonnieren und die 🔔 zu aktivieren, um keine Folge mit einfachen Rezepten mehr zu verpassen.",
							Duration:     "PT2M37S",
							EmbedURL:     "https://www.youtube.com/embed/-w8qtjBq3pM?feature=oembed",
							Name:         "Kartoffelgratin Rezept – So einfach gelingt dir der perfekte Auflauf!",
							ThumbnailURL: &models.ThumbnailURL{Value: "https://i.ytimg.com/vi/-w8qtjBq3pM/hqdefault.jpg"},
							UploadDate:   time.Date(2024, 10, 10, 10, 0, 1, 0, time.UTC),
						},
					},
				},
			},
		},
		{
			name: "entertainingwithbeth.com",
			in:   "https://entertainingwithbeth.com/orange-pecan-crumb-muffins/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Muffins and Scones"},
				CookTime:      "PT25M",
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2020-09-18",
				Description: &models.Description{
					Value: "You will love this recipe because all you’ll need are two bowls and a whisk. No need to drag out the electric mixer and clean one more kitchen gadget. These muffins are as low tech as it gets and so delicious!",
				},
				Keywords: &models.Keywords{Values: "Crumb Cake Muffins, Crumb Muffin, Muffin Recipe with Crumb Topping"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"2 eggs",
						"¼ cup (50g) sugar",
						"¼ cup (45g) brown sugar",
						"3 tbsp (45ml) maple syrup",
						"¾ cup (180ml) melted butter",
						"¼ cup (60ml) of vegetable oil",
						"1 tbsp (15ml) orange zest",
						"½ cup (120ml) orange juice",
						"½ cup (120ml) water",
						"2 cups (240g) all-purpose flour",
						"2 tsp (10ml) baking powder",
						"½ tsp (2.5ml) salt",
						"¼ tsp (1.25ml) ground cloves",
						"½ cup pecans (75g) chopped",
						"3 tbsp (37g) sugar",
						"3 tbsp (34g) brown sugar",
						"6 tbsp (90g) flour",
						"¾ tsp (3.75ml) cinnamon",
						"4 tbsp (60ml) melted butter",
						"½ tsp (2.5ml) baking powder",
						"A dusting of powdered sugar",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat oven to 400F (200ml). For the crumb topping, whisk together the sugars, flour, baking powder and cinnamon. Add the butter and stir together with a fork until a crumb topping forms. Set aside."},
						{Type: "HowToStep", Text: "In a large bowl whisk together the eggs, sugars, maple syrup, butter, vegetable oil, orange zest and juice, and water. Set aside."},
						{Type: "HowToStep", Text: "In a medium-sized bowl whisk together the flour, baking powder, salt, and cloves."},
						{Type: "HowToStep", Text: "Add the dry ingredients, in thirds, to the wet ingredients, whisking gently until just combined."},
						{Type: "HowToStep", Text: "Do not overmix."},
						{Type: "HowToStep", Text: "Stir in the pecans."},
						{Type: "HowToStep", Text: "Line a 12-cup muffin tin with muffin papers (or a jumbo muffin tin with 6 wells) with papers. Fill the batter in the muffin tin about &frac34; of the way full. Top with the crumb topping."},
						{Type: "HowToStep", Text: "Bake for 25 minutes. Once cool enough to handle, transfer muffins to a cooling rack and dust lightly with powdered sugar."},
					},
				},
				Name: "Orange Pecan Crumb Muffin Recipe",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "233",
					Carbohydrates:  "43",
					Cholesterol:    "43",
					Fat:            "6",
					Fiber:          "1",
					Protein:        "3",
					SaturatedFat:   "3",
					Servings:       "1",
					Sodium:         "68",
					Sugar:          "21",
					TransFat:       "0",
					UnsaturatedFat: "2",
				},
				PrepTime:     "PT45M",
				ThumbnailURL: &models.ThumbnailURL{},
				Tools:        &models.Tools{Values: []models.HowToItem{}},
				TotalTime:    "PT1H10M",
				Yield:        &models.Yield{Value: 12},
				URL:          "https://entertainingwithbeth.com/orange-pecan-crumb-muffins/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:       "VideoObject",
							ContentURL:   "https://www.youtube.com/watch?v=ZrmJZGvDGxE",
							Description:  "#entertainingwithbeth #CookingChannel #EasyRecipes\n\nDAD'S IGTV CHANNEL (fun inspiring videos with Dad!) \nhttps://bit.ly/2HlWcbX\n\nMORE INFO ON GIVE ESSENTIAL: https://www.giveessential.org/\n1.) Give Essential was started in April by two Dartmouth College students. \n2.) They are a female-led and student-run nonprofit, and their team is 100% volunteer\n3.) Give Essential is a matching platform that connects essential workers who need household items to donors who are able to provide them; since they started, donors have pledged $1 million in in-kind and cash donations to essential workers in all 50 US-states!\n4.) For every dollar donated to Give Essential, they are able to send packages valued at $200 total\n5.) For the month of September, they are turning Labor Day into Labor Month to celebrate the essential workers that have kept our communities safe and healthy during the pandemic. \n6.)  Their goal is to raise $100,000 so that they can meet the goal of helping 50,000 families by the end of the year!\n\nORANGE PECAN CRUMB MUFFINS\nMakes 12 standard Muffins or 6 Jumbo Muffins \n\nINGREDIENTS:\n2 eggs\n¼ cup (50g) sugar\n¼ cup (45g) brown sugar\n3 tbsp (45ml) maple syrup\n¾ cup (180ml) melted butter\n¼ cup (60ml) of vegetable\n1 tbsp (15ml) orange zest\n½ cup (120ml) orange juice\n½ cup (120ml) water\n2 cups (240g) all-purpose flour\n2 tsp (10ml) baking powder\n½ tsp (2.5ml) salt\n¼ tsp (1.25ml) ground cloves\n½ cup pecans (75g) chopped\n\nFor Crumb Topping:\n3 tbsp (37g) sugar\n3 tbsp (34g) brown sugar\n6 tbsp (90g) flour\n¾ tsp (3.75ml) cinnamon\n4 tbsp (60ml) melted butter\n½ tsp (2.5ml) baking powder\n\nGarnish:\nA dusting of powdered sugar\n\nMETHOD:\nPreheat oven to 400F (200ml).\n\nFor the crumb topping, whisk together the sugars, flour and cinnamon. Add the butter and stir together with a fork until a crumb topping forms. Set aside.\n\nIn a large bowl whisk together the eggs, sugars, maple syrup, butter, vegetable oil, orange zest and juice and water. Set aside.\n\nIn a medium-sized bowl whisk together the flour, baking powder, salt and cloves.\n\nAdd the dry ingredients, in thirds, to the wet ingredients, whisking gently until just combined. Do not overmix.\n\nStir in the pecans.\n\nLine a 12-cup muffin tin with muffin papers (or a jumbo muffin tin with 6 wells) with papers. Fill the batter in the muffin tin about ¾ of the way full. Top with the crumb topping.\n\nBake for 25 minutes. Once cool enough to handle, transfer muffins to a cooling rack and dust lightly with powdered sugar. \n\n\n\nABOUT THIS CHANNEL\nHi! I'm Beth Le Manach and I believe food tastes better when shared. Subscribe to my cooking channel, Entertaining with Beth, to learn holiday recipes, party planning tips and easy recipes for weeknight meals! New recipe videos post every Saturday! SUBSCRIBE HERE! http://bit.ly/BethsEntertaining.",
							Duration:     "PT29M11S",
							Name:         "🔴 LIVE! BAKE WITH ME! (Orange Pecan Muffins)",
							ThumbnailURL: &models.ThumbnailURL{Value: "https://i.ytimg.com/vi/ZrmJZGvDGxE/hqdefault.jpg"},
							UploadDate:   time.Date(2020, 9, 20, 17, 28, 7, 0, time.UTC),
						},
					},
				},
			},
		},
		{
			name: "epicurious.com",
			in:   "https://www.epicurious.com/recipes/food/views/olive-oil-cake",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				CookTime:      "PT15M",
				Cuisine:       &models.Cuisine{},
				DateModified:  "2017-11-01T10:56:00.000-04:00",
				DatePublished: "2017-11-01T10:56:00.000-04:00",
				Description: &models.Description{
					Value: "This easy olive oil cake recipe gets a splash of liqueur for deep flavor, and lemon for brightness—and it only gets better the longer it sits on the counter.",
				},
				Keywords: &models.Keywords{
					Values: "baking,cake,amaretto,vermouth,grand marnier,italian,cake flour,almond flour,lemon,vanilla,snack,breakfast,nut free,stand mixer,bon appétit,web",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1¼ cups plus 2 Tbsp. extra-virgin olive oil, divided; plus more for pan",
						"1 cup plus 2 Tbsp. (225 g) sugar; plus more",
						"2 cups (250 g) cake flour",
						"⅓ cup (32 g) almond flour or meal or (46 g) fine-grind cornmeal",
						"2 tsp. baking powder",
						"½ tsp. baking soda",
						"½ tsp. Diamond Crystal or ¼ tsp. plus ⅛ tsp. Morton kosher salt",
						"3 Tbsp. amaretto, Grand Marnier, sweet vermouth, or other liqueur",
						"1 Tbsp. finely grated lemon zest",
						"3 Tbsp. fresh lemon juice",
						"2 tsp. vanilla extract",
						"3 large eggs, room temperature",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat oven to 400°. Drizzle bottom and sides of a 9\" springform pan (or a 9” round cake pan with sides at least 3” high) with extra-virgin olive oil and use your fingers to coat. Line bottom with a round of parchment paper and smooth to eliminate air bubbles; coat parchment with more extra-virgin olive oil. Generously sprinkle pan with sugar and tilt to coat in an even layer; tap out excess. Whisk 2 cups (250 g) cake flour, ⅓ cup (32 g) almond flour or meal or fine-grind cornmeal, 2 tsp. baking powder, ½ tsp. baking soda, and ½ tsp. Diamond Crystal or ¼ tsp. plus ⅛ tsp. Morton kosher salt in a medium bowl to combine and eliminate any lumps. Stir together 3 Tbsp. amaretto, Grand Marnier, sweet vermouth, or other liqueur, 3 Tbsp. fresh lemon juice, and 2 tsp. vanilla extract in a small bowl."},
						{Type: "HowToStep", Text: "Using an electric mixer on high speed (use whisk attachment if working with a stand mixer), beat 3 large eggs, room temperature, 1 Tbsp. finely grated lemon zest, and 1 cup plus 2 Tbsp. (225 g) sugar in a large bowl until mixture is very light, thick, pale, and falls off the whisk or beaters in a slowly dissolving ribbon, about 3 minutes if using a stand mixer and about 5 minutes if using a hand mixer. With mixer still on high speed, gradually stream in 1¼ cups extra-virgin olive oil and beat until incorporated and mixture is even thicker. Reduce mixer speed to low and add dry ingredients in 3 additions, alternating with wet ingredients in 2 additions, beginning and ending with flour mixture. Fold batter several times with a large rubber spatula, making sure to scrape the bottom and sides of bowl. Scrape batter into prepared pan, smooth top, and sprinkle with more sugar."},
						{Type: "HowToStep", Text: "Place cake in oven and immediately reduce oven temperature to 350°. Bake until top is golden brown, center is firm to the touch, and a tester inserted into the center comes out clean, 40–50 minutes. Transfer pan to a wire rack. Poke holes all over top of cake with a toothpick or skewer and drizzle with remaining 2 Tbsp. extra-virgin olive oil; let cake cool in pan 15 minutes."},
						{Type: "HowToStep", Text: "Run a thin knife around edges of cake and remove ring from pan. Slide cake onto rack and let cool completely. For the best flavor and texture, wrap cooled cake in plastic or place in an airtight container and let sit at room temperature at least a day before serving.\nDo Ahead: Cake can be baked 4 days ahead. Store tightly wrapped at room temperature."},
					},
				},
				Name:            "Olive Oil Cake",
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL: &models.ThumbnailURL{
					Value: "https://assets.epicurious.com/photos/66c750ee9f73594baf5f8e55/2:3/w_622,h_933,c_limit/olive-oil-cake.jpg",
				},
				Tools:     &models.Tools{Values: []models.HowToItem{}},
				TotalTime: "PT1H15M",
				Yield:     &models.Yield{Value: 8},
				URL:       "https://www.bonappetit.com/recipe/olive-oil-cake",
				Video:     &models.Videos{},
			},
		},
		{
			name: "errenskitchen.com",
			in:   "https://www.errenskitchen.com/baked-or-barbecued-sticky-glazed-ribs/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main"},
				CookTime:      "PT120M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2015-07-17T07:32:43+00:00",
				Description: &models.Description{
					Value: "A delightfully sweet and sticky dish, make sure you have napkins at hand!",
				},
				Keywords: &models.Keywords{Values: "bbq ribs recipe, pork ribs recipe, ribs recipe"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"4 lbs spare ribs (cut into individual ribs)", "⅛ cup smoked paprika",
						"⅛ cup sweet paprika", "1 tablespoon garlic powder", "1 teaspoon cumin",
						"1 teaspoons ground black pepper", "5 teaspoons dark brown sugar",
						"1 tablespoon salt", "⅔ cup ketchup", "3 tablespoons soy sauce",
						"1 tablespoon balsamic vinegar", "½ cup honey", "5 tablespoons bourbon",
						"1 teaspoon molasses", "1 teaspoon corn syrup",
						"1 teaspoon smoked paprika (or liquid smoke to taste)",
						"salt (to taste)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat oven to 300°F/150°C"},
						{Type: "HowToStep", Text: "In a small bowl, mix the spices for the rub."},
						{Type: "HowToStep", Text: "Cover the ribs with the rub so they’re coated all over."},
						{Type: "HowToStep", Text: "Place the ribs on a baking tray, and cover the pan with foil and bake for 2 to 2½ hours, until tender."},
						{Type: "HowToStep", Text: "Meanwhile, to make the glaze, add all the ingredients to a saucepan, stir well and bring the mixture to a simmer."},
						{Type: "HowToStep", Text: "Simmer for 5 mins until thickened and sticky, taste for seasoning, and add salt to taste, then remove from the heat and set aside until needed."},
						{Type: "HowToStep", Text: "At this point, they can be dipped in the glaze and grilled on the BBQ for 10-15 minutes (brushing with the glaze again as needed)"},
						{Type: "HowToStep", Text: "When the ribs are done, remove from the oven and increase the heat to 400°F/200°C."},
						{Type: "HowToStep", Text: "Using a pair of tongs, dip each rib in the glaze, then return to the rack."},
						{Type: "HowToStep", Text: "Place the ribs back in the oven and cook for 10 mins."},
						{Type: "HowToStep", Text: "Remove from oven, dip into the glaze again, then return to the oven for another 10-12 minutes until sticky."},
						{Type: "HowToStep", Text: "Serve hot."},
					},
				},
				Name: "Baked or Barbecued Sticky Glazed Ribs",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "1539",
					Carbohydrates: "58",
					Cholesterol:   "362",
					Fat:           "107",
					Fiber:         "3",
					Protein:       "73",
					SaturatedFat:  "34",
					Servings:      "1",
					Sodium:        "3239",
					Sugar:         "49",
				},
				PrepTime:  "PT5M",
				TotalTime: "PT125M",
				Yield:     &models.Yield{Value: 4},
				URL:       "https://www.errenskitchen.com/baked-or-barbecued-sticky-glazed-ribs/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:       "VideoObject",
							ContentURL:   "https://content.jwplatform.com/videos/rOM98iNi.mp4",
							Description:  "Video showing how to make delightfully sweet and sticky ribs - make sure you have napkins at hand!",
							Name:         "Baked or Barbecued Sticky Glazed Ribs",
							ThumbnailURL: &models.ThumbnailURL{Value: "https://content.jwplatform.com/thumbs/rOM98iNi-720.jpg"},
							UploadDate:   time.Date(2021, 8, 29, 0, 0, 0, 0, time.UTC),
						},
					},
				},
			},
		},
		{
			name: "etenvaneefke.nl",
			in:   "http://www.etenvaneefke.nl/pastasalade/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateModified:  "2014-06-21T18:29:35+00:00",
				DatePublished: "2014-04-07T07:00:27+00:00",
				Description:   &models.Description{Value: "Bij de zomer hoort pastasalade. En hoewel het pas april is, kreeg ik door de zomerse temperaturen vorige week spontaan zin in pastasalade. Ik maakte een salade van fusilli, gevuld met gerookte kip, pesto, rucola, zongedroogde tomaatjes, pijnboompitten en een uitje. Ingrediënten (voor 2 à 3 personen) 250 gram pasta 1 zakje rucola 1 gerookte…"},
				Keywords:      &models.Keywords{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"250 gram pasta",
						"1 zakje rucola",
						"1 gerookte kipfilet",
						"1 ui",
						"50 gram pijnboompitten",
						"3 eetlepels pesto",
						"half potje zongedroogde tomaten",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{
							Text: "Kook de pasta gaar volgens de gebruiksaanwijzing en laat het daarna afkoelen (of spoel af onder de kraan met koud water). Rooster de pijnboompitten bruin in een koekenpan zonder olie of boter. Snijd de kip, ui en zongedroogde tomaten in kleine stukjes. Meng de pasta met de pesto en voeg vervolgens alle andere ingrediënten toe. Breng op smaak met zout en peper.",
							Type: "HowToStep",
						},
						{
							Text: "Een goede maaltijdsalade, maar ook lekker als lunch of bijgerecht bij de BBQ!",
							Type: "HowToStep",
						},
					},
				},
				Name:            "PASTASALADE KIP-RUCOLA-PESTO-TOMAAT",
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 1},
				URL:             "http://www.etenvaneefke.nl/pastasalade/",
				Video:           &models.Videos{},
			},
		},
		{
			name: "expressen.se",
			in:   "https://alltommat.expressen.se/recept/saftiga-choklad--och-apelsinbullar/",
			want: models.RecipeSchema{
				AtContext: atContext,
				AtType:    &models.SchemaType{Value: "Recipe"},
				Category:  &models.Category{Value: "uncategorized"},
				Name:      "Saftiga choklad- och apelsinbullar",
				Description: &models.Description{
					Value: `Goda små "fjärilsbullar" med choklad och krämig apelsinfyllning. För att få bullarnas fina fjärilsliknande form skärs degrullen i skivor som trycks ihop i mitten. Spritsa apelsinfyllningen i mitten av varje bulle. Supergott och lyxigt!`,
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"50 g jäst",
						"5 dl mjölk",
						"200 g smör",
						"2 dl strösocker",
						"1 msk hela kardemummakärnor",
						"1.5 tsk salt",
						"16 dl vetemjöl",
						"200 g smör",
						"2 dl strösocker",
						"3 msk kakao",
						"2 tsk vaniljsocker",
						"0.5 dl strösocker",
						"1.25 dl mjölk",
						"0.5 dl apelsin",
						"1 apelsin",
						"17 g majsstärkelse (Maizena)",
						"40 g äggulor",
						"1 krm salt",
						"5 g smör",
						"1 ägg",
						"1 krm salt",
						"droppar vatten",
						"4 msk pärlsocker",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Smula ner jästen i en bunke, gärna tillhörande en köksassistent. Tillsätt mjölken och blanda sedan i resten av ingredienserna. Arbeta degen i ca 10 min. Lägg en bakduk över bunken och låt degen jäsa i 30min. Gör under tiden fyllningen och apelsinkrämen."},
						{Type: "HowToStep", Text: "Chokladfyllning: Rör ihop smör, strösocker, kakao och vaniljsocker. Om den känns för tjock kan du mikra den ett par sekunder."},
						{Type: "HowToStep", Text: "Apelsinkräm: Blanda ihop alla ingredienserna utom smöret i en kastrull. Låt det sjuda och vispa under tiden. Dra av kastrullen från värmen när krämen börjar tjockna och vispa i smöret. Passera krämen genom en sil. Fyll en spritspåse med apelsinkrämen. Låt den svalna."},
						{Type: "HowToStep", Text: "Stjälp upp degen på en mjölad arbetsbänk. Kavla ut degen till en rektangel, 25x65 cm. Bred ut chokladfyllningen på hela ytan. Rulla ihop degen från långsidan till en rulle. Skär rullen i bitar, ca 3 cm breda. Tryck till bitarna på mitten med ett grillspett eller en rund pinne så att snittytorna viks in mot mitten som en fjäril."},
						{Type: "HowToStep", Text: "Låt bullarna jäsa under en bakduk i 1–1 ½ timme. Sätt ugnen på 220grader."},
						{Type: "HowToStep", Text: "Gör ett hål med fingret i mitten på varje bulle och spritsa i apelsinfyllningen. Vispa ihop ägg, salt och vatten med en gaffel. Pensla bullarna med äggblandningen och strö över pärlsocker. Grädda bullarna i 7–8min, låt dem svalna på ett galler."},
					},
				},
				Keywords: &models.Keywords{Values: "sections/recept"},
				ThumbnailURL: &models.ThumbnailURL{
					Value: "https://static.bonniernews.se/images/45/cd/45cd6c5649004e1fa957e891d581fa49/16x9/original.jpg",
				},
				Yield: &models.Yield{Value: 22},
				URL:   "https://alltommat.expressen.se/recept/saftiga-choklad--och-apelsinbullar/",
			},
		},
		{
			name: "evolvingtable.com",
			in:   "https://www.evolvingtable.com/lemon-orzo-pasta-salad-with-feta/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtGraph:       nil,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main Course"},
				CookTime:      "PT30M",
				CookingMethod: nil,
				Cuisine:       &models.Cuisine{Value: "American"},
				DateCreated:   "",
				DateModified:  "",
				DatePublished: "2024-06-25T22:25:45+00:00",
				Description: &models.Description{
					Value: "This Lemon Orzo Pasta Salad is now THE dish I bring to all of our summer get-togethers! Loaded with fresh lemon flavor, tons of herbs, roasted red peppers, summer squash, and tangy feta cheese, it&#039;s secretly simple to prepare and always a crowd-pleaser at every picnic and BBQ!",
				},
				Keywords: &models.Keywords{Values: "easy, how to make, lemon vinaigrette, orzo, pasta salad"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"12 oz. orzo pasta", "2 small red bell peppers (seeds and core removed)",
						"1 zucchini squash (diced)", "1 yellow squash (diced)",
						"3 Tbsp. olive oil (divided)", "1 tsp. salt (divided, plus more to taste)",
						"½ tsp. black pepper", "6 oz. crumbled feta cheese",
						"½ small red onion (thinly sliced)",
						"½ cup thinly sliced basil",
						"½ cup olive oil",
						"1 lemon (juice and zest)",
						"1 Tbsp. red wine vinegar",
						"1 Tbsp. honey",
						"1 garlic clove (finely minced)",
						"1 tsp. dried oregano",
						"½ tsp. dried thyme",
						"¼ tsp. red pepper flakes",
						"½ tsp. salt (plus more to taste)",
						"¼ tsp. black pepper",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Text: "Preheat air fryer to 400°F.", Type: "HowToStep"},
						{Text: "Cook pasta according to package directions.", Type: "HowToStep"},
						{Text: "Slice ½” to the right or left of the bell pepper stems from top to bottom to remove 4 pieces, leaving the core intact. Scrape out and discard any membranes or seeds. Repeat with the other pepper. Drizzle the inside of the pieces with 1 tablespoon oil and sprinkle with ¼ teaspoon salt.", Type: "HowToStep"},
						{Text: "Place pepper pieces skin-side up in the preheated air fryer basket and cook for 14-15 minutes, or until the skin is blistered. (See recipe note if roasting in the oven.) Once roasted, add peppers to a large bowl and cover with either plastic wrap or a plate so the steam can finish cooking them. Let rest for 15 minutes, or until the peppers are cool enough to touch.", Type: "HowToStep"},
						{Text: "Meanwhile, add the diced squash to a large bowl along with the remaining 2 tablespoons oil, ¾ teaspoon salt, and ½ teaspoon black pepper. Toss until the squash is well coated. Add to the air fryer basket in a single layer, reduce the heat to 375°F and cook for 12-14 minutes, or until the squash is tender.", Type: "HowToStep"},
						{Text: "Once the pepper pieces are cooled, peel and remove the skin from each piece of pepper. Reserve 3-4 of the larger pieces of blistered skin. Dice the roasted red peppers into ½” pieces.", Type: "HowToStep"},
						{Text: "For the Lemony Herb Dressing: In a 16-oz. mason jar, add the olive oil, lemon juice, lemon zest, red wine vinegar, honey, garlic, oregano, thyme, red pepper, salt, and black pepper along with the reserved pieces of roasted red pepper skin. Shake vigorously for 20-30 seconds or until the dressing is emulsified. Set this aside to rest for at least 10 minutes.", Type: "HowToStep"},
						{Text: "Add the cooled and cooked orzo pasta to a large salad bowl along with the roasted squash, diced roasted bell peppers, feta cheese crumbles, red onion, and basil. Remove the bell pepper skins from the mason jar and shake the salad dressing for another 10-15 seconds to ensure it is emulsified. Drizzle dressing over the salad and toss until well combined. Serve immediately with additional finely chopped fresh parsley or chill for 3-4 hours to serve cold.", Type: "HowToStep"},
					},
				},
				Name: "Lemon Orzo Pasta Salad with Feta",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "605",
					Carbohydrates:  "68",
					Cholesterol:    "25",
					Fat:            "33",
					Fiber:          "7",
					Protein:        "14",
					SaturatedFat:   "7",
					Servings:       "1",
					Sodium:         "819",
					Sugar:          "10",
					TransFat:       "0.03",
					UnsaturatedFat: "24",
				},
				PrepTime:  "PT20M",
				TotalTime: "PT50M",
				Yield:     &models.Yield{Value: 6},
				URL:       "https://www.evolvingtable.com/lemon-orzo-pasta-salad-with-feta/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:      "VideoObject",
							ContentURL:  "https://mediavine-res.cloudinary.com/video/upload/t_original/v1718481322/zzzyuagnmciiwxseqmpu.mp4",
							Description: "This Lemon Orzo Pasta Salad is now THE dish I bring to all of our summer get-togethers! Loaded with fresh lemon flavor, tons of herbs, roasted red peppers, summer squash, and tangy feta cheese, it’s secretly simple to prepare and always a crowd-pleaser at every picnic and BBQ!",
							Duration:    "PT35S",
							EmbedURL:    "https://video.mediavine.com/videos/zzzyuagnmciiwxseqmpu.js",
							Name:        "Summer Orzo Salad",
							ThumbnailURL: &models.ThumbnailURL{
								Value: "https://mediavine-res.cloudinary.com/video/upload/s--B3SuxlP2--/c_limit,f_auto,fl_lossy,h_1080,q_auto,w_1920/v1718481322/zzzyuagnmciiwxseqmpu.jpg",
							},
							UploadDate: time.Date(2024, 6, 15, 19, 56, 42, 0, time.UTC),
						},
					},
				},
			},
		},
	}
	for _, tc := range testcases {
		t.Run(tc.name, func(t *testing.T) {
			test(t, tc)
		})
	}
}
