package scraper_test

import (
	"testing"

	"github.com/reaper47/recipya/internal/models"
)

func TestScraper_F(t *testing.T) {
	testcases := []testcase{
		{
			name: "farmhousedelivery.com",
			in:   "https://recipes.farmhousedelivery.com/green-shakshuka/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Breakfast"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateModified:  "2023-01-20T18:47:32+00:00",
				DatePublished: "2023-01-20T08:13:29+00:00",
				Description: &models.Description{
					Value: "Who knew a recipe could get us all excited with just a word? Shakshuka is awfully fun to say, but even more fun when you realize how delicious it is. An easy way to make dinner out of a few Read on!",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 yellow onion, slivered",
						"3 cloves garlic, minced",
						"2 Tbsp. olive oil",
						"1 jalapeno, seeded and minced",
						"4 big handfuls greens (mix kale & spinach), chopped and washed",
						"1/2 cup cream",
						"4 eggs",
						"Salt & pepper",
						"Plain yogurt, for serving",
						"Hot sauce, for serving",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Saute onions & garlic in olive oil in a large skillet until they take on a little color. Add jalapeno and continue cooking for 1-2 minutes. Add chopped greens, season with salt and pepper to taste and cover until greens are just wilted. Add cream and bring to a simmer. Crack eggs on top of greens, cover and cook until eggs are cooked to your preference. Serve in wide bowls with a dollop of yogurt and a drizzle of hot sauce and thick slices of warm bread on the side."},
					},
				},
				Name:            "Green Shakshuka",
				NutritionSchema: &models.NutritionSchema{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 1},
				URL:             "https://recipes.farmhousedelivery.com/green-shakshuka/",
			},
		},
		{
			name: "farmhouseonboone.com",
			in:   "https://www.farmhouseonboone.com/sourdough-pretzel-buns",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Sourdough"},
				CookTime:      "PT25M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2023-11-15T18:22:34+00:00",
				Description: &models.Description{
					Value: "The most delicious sourdough pretzel buns have a soft and fluffy interior with a deep brown exterior that tastes just like the soft pretzels you love.",
				},
				Keywords: &models.Keywords{Values: "sourdough pretzel buns"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"½ cup sourdough starter (active and bubbly (113 grams))",
						"1 cup water (236 grams)", "2 teaspoons sugar (8 grams)",
						"1/4 cup butter (softened (57 grams))", "2 teaspoons salt (10 grams)",
						"3 cups unbleached all purpose flour (420 grams)", "8 cups water", "1/2 cup baking soda",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Four to 12 hours before starting this recipe, feed the sourdough starter. It needs to be really active, bubbly, and able to pass the float test."},
						{Type: "HowToStep", Text: "In a bowl of a stand mixer with a dough hook attachment, add the dough ingredients."},
						{Type: "HowToStep", Text: "Mix on low speed (speed 1-2 on a Kitchen Aid mixer) until it forms a shiny dough ball that will pass the windowpane test, about 7-10 minutes. Take a small amount of dough and stretch it into a square. If you can stretch it and see through the dough without the dough breaking, it is ready to move on to the next stage"},
						{Type: "HowToStep", Text: "Place the dough into a lightly oiled bowl and cover with a lid, plastic wrap, or beeswax wraps."},
						{Type: "HowToStep", Text: "Allow it to bulk ferment for 8-12 hours or until doubled. If your house is on the colder side, it may take longer. It should just double in size."},
						{Type: "HowToStep", Text: "Divide into 10 equal pieces."},
						{Type: "HowToStep", Text: "Shape the dough into round dough balls. I like to create tension in the dough by pulling the dough into the center and kind of folding it in."},
						{Type: "HowToStep", Text: "Place on a parchment lined baking sheet and cover with a tea towel."},
						{Type: "HowToStep", Text: "Allow to rise in a warm spot until doubled in size."},
						{Type: "HowToStep", Text: "Preheat oven to 425 degrees."},
						{Type: "HowToStep", Text: "Add 8 cups of water and baking soda to a large pot and bring to a boil."},
						{Type: "HowToStep", Text: "Gently place each roll into the boiling water and boil for about 2 minutes. Flip and boil on the other side for another 2 minutes."},
						{Type: "HowToStep", Text: "Transfer the boiled pretzel buns to the parchment lined baking sheet."},
						{Type: "HowToStep", Text: "Score an X on top of each bun with a lame (a razor blade used in baking) or sharp knife and sprinkle with coarse sea salt."},
						{Type: "HowToStep", Text: "Bake 20-25 minutes until achieving a deep golden brown color."},
						{Type: "HowToStep", Text: "Allow to cool, then serve."},
					},
				},
				Name: "Sourdough Pretzel Buns",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "192",
					Carbohydrates:  "32",
					Cholesterol:    "12",
					Fat:            "5",
					Fiber:          "1",
					Protein:        "4",
					SaturatedFat:   "3",
					Servings:       "1",
					Sodium:         "2155",
					Sugar:          "1",
					TransFat:       "0.2",
					UnsaturatedFat: "1.3",
				},
				PrepTime:  "PT15M",
				TotalTime: "PT880M",
				Yield:     &models.Yield{Value: 10},
				URL:       "https://www.farmhouseonboone.com/sourdough-pretzel-buns",
			},
		},
		{
			name: "fattoincasadabenedetta.it",
			in:   "https://www.fattoincasadabenedetta.it/ricetta/lasagne-al-pistacchio/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Pasta"},
				CookTime:      "P0DT0H40M0S",
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				Description: &models.Description{
					Value: "La lasagna al pistacchio è una lasagna bianca gustosa, caratterizzata da un contrasto di sapori fantastico. Un piatto della domenica speciale!",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"pistacchi 150 g al naturale", "olio di semi di girasole 80 g",
						"besciamella 500 ml", "sfoglie sottili pronte per lasagne 200 g",
						"mozzarella 250 g a dadini", "formaggio grattugiato 60 g",
						"speck 200 g a fette", "granella di pistacchio",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "In un tritatutto mettiamo i pistacchi e l’olio di semi di girasole e frulliamo bene per ottenere un pesto cremoso."},
						{Type: "HowToStep", Text: "In una ciotola mettiamo la besciamella e uniamo i pistacchi frullati, mescolando con un cucchiaio."},
						{Type: "HowToStep", Text: "Prepariamo tutti gli ingredienti e assembliamo la nostra lasagna: prendiamo una pirofila da forno 30&#215;20 cm e spalmiamo sul fondo la besciamella al pistacchio."},
						{Type: "HowToStep", Text: "Sistemiamo sopra la prima sfoglia e mettiamo altra besciamella, poi qualche fetta di speck, la mozzarella a dadini e il formaggio grattugiato."},
						{Type: "HowToStep", Text: "Proseguiamo con gli altri strati fino a terminare gli ingredienti. In superficie mettiamo uno strato di besciamella al pistacchio, una spolverata di formaggio grattugiato e infine della granella di pistacchio."},
						{Type: "HowToStep", Text: "Inforniamo e cuociamo in forno ventilato a 170 °C per 35-40 minuti, oppure in forno statico a 180 °C per lo stesso tempo."},
						{Type: "HowToStep", Text: "Ecco pronta la nostra gustosissima lasagna al pistacchio! Buon appetito!"},
					},
				},
				Name:            "Lasagna al pistacchio",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "P0DT0H10M0S",
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				TotalTime:       "P0DT0H50M0S",
				Yield:           &models.Yield{Value: 4},
				URL:             "https://www.fattoincasadabenedetta.it/ricetta/lasagne-al-pistacchio/",
			},
		},
		{
			name: "feastingathome.com",
			in:   "https://www.feastingathome.com/orecchiette-pasta-with-broccoli-sauce/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "vegetarian main"},
				CookTime:      "PT25M",
				CookingMethod: &models.CookingMethod{Value: "stove top"},
				Cuisine:       &models.Cuisine{Value: "Italian"},
				DatePublished: "2018-03-16",
				Description: &models.Description{
					Value: "Orecchiette Broccoli Sauce - a simple vegetarian pasta dish hailing from Tuscany that is easy to make, healthy and oh so delicious!",
				},
				Keywords: &models.Keywords{Values: "broccoli pasta recipe, Orecchiette Pasta, Orecchiette, broccoli pasta, broccoli pasta recipes, orecchiette pasta recipe, broccoli recipes, vegetarian pasta recipes, healthy pasta recipes, vegetarian broccoli pasta"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"12 ounces broccoli florets- cut or broken into very small florets about equal size (about 6 cups packed)",
						"8 ounces short pasta- orecchiette pasta, penne, rigatoni, etc",
						"3 tablespoons olive oil",
						"1 fat shallot, diced",
						"6 garlic cloves- rough chopped",
						"generous pinch chili flakes ( Aleppo or Urfa biber is nice here)",
						"generous pinch salt and pepper, more to taste",
						"1 teaspoon miso paste (or sub anchovy paste)",
						"2 cups veggie broth or chicken broth",
						"1-2 teaspoons lemon zest",
						"1/4- 1/2 cup fresh grated pecorino cheese ( please see notes) or fresh parmesan",
						"Optional Garnish:  pecorino cheese,  lemon zest, truffle oil, fresh basil ribbons, toasted pine nuts, toasted bread crumbs, capers, truffle oil or kalamata olives&#8211; all optional.",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Steam small broccoli florets until very tender (easily pierced with a fork) then chop and set aside."},
						{Type: "HowToStep", Text: "Cook the pasta in 8 cups water with 1 tablespoon salt (measure), Save a cup of hot pasta water when you drain."},
						{Type: "HowToStep", Text: "In a large pan, saute the shallot and garlic and chili flakes in the olive oil, over medium heat until fragrant and golden, about 3 minutes. Stir in the miso paste (or anchovy), then add steamed broccoli, salt, pepper and the broth."},
						{Type: "HowToStep", Text: "Bring to a gentle simmer and break apart the broccoli with a metal spatula into tiny pieces. As it cooks and softens it will get easier to break apart. You want the broccoli to melt down into a &#8220;sauce &#8221; &#8211; take your time here, adding more liquid as needed."},
						{Type: "HowToStep", Text: "Stir in 1/4 cup grated pecorino cheese. Continue simmering gently on low heat until half of the liquid evaporates and it becomes the consistency of a thick sauce, about 10 minutes."},
						{Type: "HowToStep", Text: "At this point, if you like a smoother sauce, feel free to use an immersion blender right in the pan. I did not use one for these photos- but it is an option. Taste and adjust salt and pepper to taste- you want it on the slightly salty side."},
						{Type: "HowToStep", Text: "Add the pasta. Toss well. Add more hot pasta water to keep it &#8221; saucy.&#8221;  Taste once more for salt, adjust, adding more along with pepper, chili flakes. If you want more richness add another splash of olive oil (or pat of butter- my husband loves this). Stir in more pecorino if you like."},
						{Type: "HowToStep", Text: "Divide among pasta bowls and top with any of the garnishes you like!"},
					},
				},
				Name: "Orecchiette with Broccoli",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "351",
					Carbohydrates: "49.2",
					Cholesterol:   "9.7",
					Fat:           "12.7",
					Fiber:         "7.5",
					Protein:       "15.6",
					SaturatedFat:  "3.6",
					Sodium:        "518.3",
					Sugar:         "3.2",
					TransFat:      "0",
				},
				PrepTime:  "PT5M",
				TotalTime: "PT30M",
				Yield:     &models.Yield{Value: 4},
				URL:       "https://www.feastingathome.com/orecchiette-pasta-with-broccoli-sauce/",
			},
		},
		{
			name: "fifteenspatulas.com",
			in:   "https://www.fifteenspatulas.com/guacamole/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Appetizer"},
				Cuisine:       &models.Cuisine{Value: "Mexican"},
				DatePublished: "2023-06-05T09:44:00+00:00",
				Description: &models.Description{
					Value: "This Homemade Guacamole has the perfect texture and combination of flavors, with chunky mashed avocados mixed with fresh lime juice, jalapeno, white onion, tomatoes, and cilantro.",
				},
				Keywords: &models.Keywords{Values: "guacamole"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"3 ripe avocados",
						"1/4 cup seeded and diced tomato",
						"2 tbsp finely chopped white onion",
						"2 tbsp minced jalapeno",
						"1 tbsp freshly squeezed lime juice",
						"1/2 tsp salt (or to taste)",
						"2 tbsp chopped cilantro",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Cut the avocados in half and remove the pits."},
						{Type: "HowToStep", Text: "Scoop the avocado flesh out into a bowl, and mash the avocado with a fork, leaving plenty of chunky, unmashed bits of avocado."},
						{Type: "HowToStep", Text: "Add the tomato, onion, jalapeno, lime juice, and salt, then gently stir to combine."},
						{Type: "HowToStep", Text: "Gently fold in the cilantro."},
						{Type: "HowToStep", Text: "Taste the guacamole and adjust to your tastes (you may desire more salt, or more acidity), then serve. Enjoy!"},
					},
				},
				Name: "Guacamole",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "168",
					Carbohydrates: "10",
					Fat:           "15",
					Fiber:         "7",
					Protein:       "2",
					SaturatedFat:  "2",
					Servings:      "1",
					Sodium:        "307",
					Sugar:         "2",
				},
				PrepTime:  "PT10M",
				TotalTime: "PT10M",
				Yield:     &models.Yield{Value: 4},
				URL:       "https://www.fifteenspatulas.com/guacamole/",
			},
		},
		{
			name: "finedininglovers.com",
			in:   "https://www.finedininglovers.com/recipes/main-course/szechuan-chicken",
			want: models.RecipeSchema{
				AtContext: atContext,
				AtType:    &models.SchemaType{Value: "Recipe"},
				Category: &models.Category{
					Value: "Main Course",
				},
				Description: &models.Description{
					Value: "Szechuan Chicken is a spicy, crispy chicken recipe from Sichuan Region in China: discover the original recipe and try to make it at home.",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"Chicken",
						"White onion",
						"Red pepper",
						"Yellow bell peppers",
						"Chilli",
						"Ginger",
						"Cane sugar",
						"Cornstarch",
						"Garlic powder",
						"Dark soy sauce",
						"Sesame Oil",
						"Chicken stock",
						"Szechuan pepper",
						"Sunflower oil",
						"Kosher salt",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Start with the chicken. Cut it into pieces of equal size that are not too small so that the meat can have the same cooking time. Put the cornstarch in a bowl (set aside a spoon) and toss the chicken in the flour.\nIn a non-stick pan"},
						{Type: "HowToStep", Text: "pour a drizzle of seed oil and when hot"},
						{Type: "HowToStep", Text: "add the floured chicken. Cook the chicken nuggets for 3/4 minutes so that they become crunchy and amber on the outside. In the meantime"},
						{Type: "HowToStep", Text: "wash the peppers"},
						{Type: "HowToStep", Text: "remove the stalk"},
						{Type: "HowToStep", Text: "seeds and internal filaments"},
						{Type: "HowToStep", Text: "then cut them into small pieces. Peel the onion and cut this into small pieces of the same size as the peppers.\nWhen the chicken is well browned"},
						{Type: "HowToStep", Text: "remove it from the pan and keep it warm in a covered bowl. In the same pan"},
						{Type: "HowToStep", Text: "add the peppers"},
						{Type: "HowToStep", Text: "onion"},
						{Type: "HowToStep", Text: "whole chillies"},
						{Type: "HowToStep", Text: "garlic powder and freshly grated ginger. Season with salt and bring to the fire to dry the vegetables. It will take about 5 minutes on high heat. If you have decided to add it"},
						{Type: "HowToStep", Text: "now is the time to add the Szechuan pepper.\nMeanwhile"},
						{Type: "HowToStep", Text: "prepare the sauce by combining the soy sauce"},
						{Type: "HowToStep", Text: "sesame oil"},
						{Type: "HowToStep", Text: "chicken broth"},
						{Type: "HowToStep", Text: "sugar and a tablespoon of cornstarch in a bowl. Mix very well.\nAdd the chicken to the vegetables and cook for another 5 minutes"},
						{Type: "HowToStep", Text: "then add the sauce and mix well. After 30 seconds your super creamy and spicy Szechuan chicken is ready. Serve it alone or accompanied with white rice. If you like"},
						{Type: "HowToStep", Text: "you can add chopped fresh parsley or coriander. Tip & Tricks The use of corn starch instead of normal flour"},
						{Type: "HowToStep", Text: "both in the flour and in the preparation of the sauce"},
						{Type: "HowToStep", Text: "gives the dish a creamy texture. Origins This recipe has its origins in the Szechuan region"},
						{Type: "HowToStep", Text: "a place where every dish is prepared with spicy hints. Also typical of this area is Szechuan pepper"},
						{Type: "HowToStep", Text: "a fragrant berry that is added to dishes dried or in powder. Variants For a slightly less spicy Szechuan chicken"},
						{Type: "HowToStep", Text: "you can remove the seeds from the peppers or add less during cooking. To give a note of freshness you can add the grated lime or lemon zest just before serving."},
					},
				},
				Keywords: &models.Keywords{Values: "Tried and Tasted,Channel: Food & Drinks"},
				Name:     "Szechuan Chicken",
				NutritionSchema: &models.NutritionSchema{
					Servings: "4",
				},
				TotalTime: "P0DT0H0M0S",
				Yield:     &models.Yield{Value: 4},
				URL:       "https://www.finedininglovers.com/recipes/main-course/szechuan-chicken",
			},
		},
		{
			name: "fitmencook.com",
			in:   "https://fitmencook.com/rosemary-blue-cheese-turkey-sliders/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookTime:      "PT20M",
				DateModified:  "2023-05-16T19:59:35+00:00",
				DatePublished: "2021-09-05T18:05:31+00:00",
				Description:   &models.Description{},
				Keywords:      &models.Keywords{Values: "meal prep,meat,turkey"},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"Meat",
						"1 1/2 lb 93% lean ground turkey",
						"1 1/2 tablespoons The Fit Cook Everyday Blend",
						"2 tablespoons fresh rosemary, finely chopped",
						"1/3 cup blue cheese crumble",
						"pinch of sea salt & pepper",
						"\n",
						"Sliders",
						"8 (wheat) slider buns",
						"2 roma tomatoes, sliced",
						"1 medium cucumber, diagonally sliced",
						"8 tablespoons Dijon mustard",
						"8 Romaine lettuce leaves",
						"\n",
						"Quick Caramelized Onions (OPTIONAL)",
						"3 tablespoons olive oil",
						"1 large white onion, sliced",
						"pinch of sea salt & peppe",
						"\n",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "In a bowl, mix together the ingredients for the turkey sliders.  Use an ice cream scoop or 1/4 cup measuring cup to scoop to measure out each slider to keep them uniform. Alternatively you can measure out full sized burgers."},
						{Type: "HowToStep", Text: "Set a nonstick skillet on medium heat and once hot, spray with avocado or olive oil, then add the slider patties. Cook for 4 – 6 minutes on each side, or until the top/bottom are browned and the slider is cooked through."},
						{Type: "HowToStep", Text: "In a carbon steel skillet on medium heat and once hot, add olive oil and onion. As the onions saute and caramelize, add a pinch of sea salt to draw out sweetness. If desired, reduce the onions in 1/2 cup of (chicken/veggie/beef) broth, white wine, or water. Continue cooking until the onions are “wilted,” soft and golden brown, about 15 minutes."},
						{Type: "HowToStep", Text: "Build the sliders! Toast the buns then add Dijon, lettuce, tomato, cucumber, caramelized onions and the burger!"},
					},
				},
				Name: "Rosemary Blue Cheese Turkey Sliders",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "330",
					Carbohydrates: "24",
					Fat:           "15",
					Fiber:         "2",
					Protein:       "21",
					Sodium:        "670",
					Sugar:         "5",
				},
				PrepTime: "PT5M",
				URL:      "https://fitmencook.com/rosemary-blue-cheese-turkey-sliders/",
			},
		},
		{
			name: "fitslowcookerqueen.com",
			in:   "https://fitslowcookerqueen.com/easy-homemade-breakfast-sausage/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookTime:      "PT10M",
				DatePublished: "2022-07-15",
				Description:   &models.Description{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 pound ground pork", "1 teaspoon salt", "1/2 teaspoon ground sage",
						"1/2 teaspoon black pepper", "1/4 teaspoon thyme", "1/4 teaspoon onion powder",
						"1/4 teaspoon cayenne",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Combine all ingredients in a large mixing bowl. Divide the meat mixture into even portions and flatten into patties or form into links."},
						{Type: "HowToStep", Text: "Add patties to the air fryer basket. Do not overlap. You may have to cook the sausage in batches depending on the size of your air fryer."},
						{Type: "HowToStep", Text: "Cook 380 degrees for 12-15 minutes (see note below), flipping the sausage halfway through cooking. Make sure the internal temperature is at least 145 F."},
					},
				},
				Name: "Air Fryer Homemade Breakfast Sausage ",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "150",
					Carbohydrates: "0.2",
					Cholesterol:   "40.9",
					Fat:           "12.1",
					Fiber:         "0.1",
					Protein:       "9.6",
					SaturatedFat:  "4.5",
					Sodium:        "322.6",
					Sugar:         "0",
					TransFat:      "0",
				},
				PrepTime:  "PT5M",
				TotalTime: "PT15M",
				Yield:     &models.Yield{Value: 8},
				URL:       "https://fitslowcookerqueen.com/easy-homemade-breakfast-sausage/",
			},
		},
		{
			name: "food.com",
			in:   "https://www.food.com/recipe/jim-lahey-s-no-knead-pizza-margherita-382696",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Lunch/Snacks"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				CookTime:      "PT6M",
				DatePublished: "2009-07-24T13:27Z",
				Description: &models.Description{
					Value: "This is a great recipe for a simple, thin crust pizza.  It's from Jim Lahey (of no-knead bread fame) who now runs a popular NYC pizzeria called Co.  The recipe was printed in New York Magazine (Jul 12, 2009).  If you don't have a pizza stone, this works well in a cast iron skillet.  The recipe requires very little time and effort but the dough must be started the day before.",
				},
				Keywords: &models.Keywords{
					Values: "Cheese,Vegetable,European,Low Cholesterol,Healthy,Kid Friendly,Kosher,Broil/Grill,< 60 Mins,Oven,Beginner Cook,Easy,Inexpensive",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"3  cups  all-purpose flour or 3  cups  bread flour, more for dusting",
						"1/4 teaspoon  instant yeast",
						"1 1/2 teaspoons  salt",
						"1 1/4 cups  water",
						"1   vine-ripened tomatoes (about 5 oz.) or 1    heirloom tomato (about 5 oz.)",
						"1  pinch  salt",
						"1/4 teaspoon  extra virgin olive oil",
						"5  tablespoons  tomato sauce",
						"2  ounces  buffalo mozzarella (about 1/4 ball)",
						"basil leaves",
						"1  tablespoon  extra virgin olive oil",
						"salt",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "To make dough: In a large bowl, mix the flour, yeast, and salt. Add water and stir until blended (the dough will be very sticky). Cover with plastic wrap and let rest for 12 to 24 hours in a warm spot, about 70 degrees."},
						{Type: "HowToStep", Text: "Place the dough on a lightly floured work surface and sprinkle the top with flour. Fold the dough over on itself once or twice, cover loosely with plastic wrap, and let rest for 15 minutes."},
						{Type: "HowToStep", Text: "Shape the dough into 3 or 4 balls, depending on how thick you want the crust. Generously sprinkle a clean cotton towel with flour and cover the dough with it. Let the dough rise for 2 hours."},
						{Type: "HowToStep", Text: "To make sauce: Blanch tomato for 5 seconds in boiling water and quickly remove. Allow to cool to the touch. Peel the skin with your hands and quarter the tomato. Remove the jelly and seeds, and reserve in a strainer or fine sieve. Strain the jelly to remove seeds, and combine resulting liquid in a bowl with the flesh of the tomatoes. Proceed to crush the tomatoes with your hands. Add salt and olive oil and stir."},
						{Type: "HowToStep", Text: "To make pizza: Place pizza stone on the middle rack of the oven and preheat on high broil. Stretch or toss the dough into a disk approximately 10 inches in diameter. Pull rack out of oven and place the dough on top of the preheated pizza stone. Drizzle 5 generous tablespoons of sauce over the dough, and spread evenly. Try to keep the sauce about &frac12; inch away from the perimeter of the dough. Break apart or slice the buffalo mozzarella and arrange over the dough. Return rack and pizza stone to the middle of the oven and broil for approximately 6 minutes. Remove and top with basil, olive oil, and salt."},
					},
				},
				Name: "Jim Lahey’s No-Knead Pizza Margherita",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "569.4",
					Carbohydrates: "98.9",
					Cholesterol:   "15",
					Fat:           "10.5",
					Fiber:         "4.3",
					Protein:       "17.9",
					SaturatedFat:  "3.4",
					Sodium:        "1472",
					Sugar:         "2.7",
				},
				PrepTime:  "PT30M",
				Tools:     &models.Tools{Values: []models.HowToItem{}},
				TotalTime: "PT36M",
				URL:       "https://www.food.com/recipe/jim-lahey-s-no-knead-pizza-margherita-382696",
				Yield:     &models.Yield{Value: 1},
			},
		},
		{
			name: "food52.com",
			in:   "https://food52.com/recipes/7930-orecchiette-with-roasted-butternut-squash-kale-and-caramelized-red-onion",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Appetizer"},
				CookingMethod: &models.CookingMethod{},
				CookTime:      "PT1H0M",
				Cuisine:       &models.Cuisine{Value: "Italian"},
				DateModified:  "2021-04-17 19:58:03 -0400",
				DatePublished: "2010-11-21 19:54:38 -0500",
				Description: &models.Description{
					Value: "This recipe is for the butternut squash lover. This orecchiette recipe is yet another reason to love squash (and kale, and adorably shaped pasta).",
				},
				Keywords: &models.Keywords{
					Values: "Onion, Kale, Goat Cheese, Butternut Squash, Sage, Milk/Cream, Nutmeg, Pasta, Fall",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 large butternut squash, cut into small cubes, divided",
						"4 tablespoons extra-virgin olive oil, divided",
						"Kosher salt and pepper",
						"1 pinch cayenne pepper",
						"1/4 teaspoon ground nutmeg",
						"1 red onion, sliced thinly",
						"1/2 pound orecchiette",
						"1 or 2 garlic cloves, minced",
						"2 cups chicken broth, divided",
						"1 bunch kale",
						"1/2 cup white wine",
						"1/2 cup heavy cream",
						"1 ounce goat cheese, optional",
						"1 tablespoon chopped fresh sage",
						"Parmesan cheese, to serve",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat oven to 425° F. Toss all but 1 cup of the butternut squash with 1 tablespoon olive oil, salt, pepper, a pinch of cayenne pepper, and the nutmeg. Roast until butternut squash pieces are tender and caramelized, about 30 minutes. Set aside."},
						{Type: "HowToStep", Text: "Heat 1 tablespoon olive oil in a medium saucepan over low heat. Cook sliced red onions until caramelized, about 30 minutes. Set aside."},
						{Type: "HowToStep", Text: "Heat a pot of water over high heat until boiling. Salt water generously. Cook orecchiette according to package instructions until al dente."},
						{Type: "HowToStep", Text: "Meanwhile, heat another tablespoon of olive oil in a heavy pan over medium-high heat. Cook the remaining cup of butternut squash for approximately 3 minutes. Add garlic and cook for another minute. Add 1/2 cup of the chicken broth and cook until broth is almost completely absorbed."},
						{Type: "HowToStep", Text: "Remove the middle stems from the kale and roughly chop the leaves. Add kale to butternut squash and stir until kale has softened. Add caramelized red onions."},
						{Type: "HowToStep", Text: "Add white wine and cook for 2 minutes. Add remaining chicken broth and reduce, about 10 minutes."},
						{Type: "HowToStep", Text: "Turn heat to low and add the heavy cream. When the pasta is al dente, add it to the pan with the sauce. Add the roasted butternut squash."},
						{Type: "HowToStep", Text: "Loosen sauce with pasta water if needed. Sprinkle with goat cheese (optional), sage, and Parmesan cheese."},
					},
				},
				Name:            "Orecchiette With Roasted Butternut Squash, Kale, &amp;amp; Caramelized Red Onion",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT0H15M",
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 4},
				URL:             "https://food52.com/recipes/7930-orecchiette-with-roasted-butternut-squash-kale-and-caramelized-red-onion",
			},
		},
		{
			name: "foodal.com",
			in:   "https://foodal.com/recipes/candy/chili-chocolate-bark/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Candy"},
				CookingMethod: &models.CookingMethod{Value: "Stovetop"},
				CookTime:      "PT5M",
				Cuisine:       &models.Cuisine{Value: "Dessert"},
				DateModified:  "",
				DatePublished: "2021-12-14",
				Description: &models.Description{
					Value: "Everyone loves an edible gift, and this cinnamon-spiked chocolate and cherry bark gets a spicy lift from chili flakes and cayenne.",
				},
				Keywords: &models.Keywords{Values: "chocolate bark, cayenne, dried cherries, dark chocolate"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"12 ounces dark chocolate chips (at least 45% cacao)",
						"1 1/2 tablespoons unsweetened cocoa powder",
						"1/2 teaspoon crushed red pepper flakes",
						"1/2 teaspoon ground cayenne pepper",
						"1 teaspoon ground paprika",
						"1/2 teaspoon ground cinnamon",
						"2 tablespoons chopped dried cherries",
						"1/4 teaspoon large-flake salt",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Line a quarter-size rimmed sheet pan (9.5 x 13 inches) with parchment paper."},
						{Type: "HowToStep", Text: "Pull out your double boiler and add about 2 inches of water, or create a makeshift double boiler by adding the water to a medium saucepot and placing a heatproof bowl over the top. Make sure there’s a gap between the water and the bowl."},
						{Type: "HowToStep", Text: "Place over medium heat. Add the chocolate, cocoa powder, crushed red pepper flakes, cayenne, paprika, and cinnamon to the bowl (or top of the double boiler) and then bring the water in the base to a simmer. Turn off the heat, and whisk the chocolate mixture constantly until it’s melted and smooth."},
						{Type: "HowToStep", Text: "Pour the chocolate into the prepared pan, and spread it evenly with an offset spatula. It’s okay if it doesn’t reach the edges of the parchment paper."},
						{Type: "HowToStep", Text: "Immediately sprinkle the bark with the dried cherries and salt. Chill in the fridge until set, about 2-3 hours."},
						{Type: "HowToStep", Text: "Once the bark has hardened, break it into big chunks. Store in an airtight container in the fridge for 2-3 weeks."},
					},
				},
				Name: "Chili Pepper Chocolate Bark",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "296",
					Carbohydrates: "29",
					Cholesterol:   "2.9",
					Fat:           "18.9",
					Fiber:         "4.6",
					Protein:       "3.3",
					SaturatedFat:  "10.8",
					Servings:      "2",
					Sodium:        "88.8",
					Sugar:         "19.9",
					TransFat:      "0",
				},
				PrepTime:  "PT10M",
				TotalTime: "PT3H15M",
				Yield:     &models.Yield{Value: 12},
				URL:       "https://foodal.com/recipes/candy/chili-chocolate-bark/",
			},
		},
		{
			name: "foodandwine.com",
			in:   "https://www.foodandwine.com/recipes/garlic-salmon-with-sheet-pan-potatoes",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Dinner"},
				DateModified:  "2023-08-02T10:26:55.248-04:00",
				DatePublished: "2022-03-25T10:20:00.000-04:00",
				Description: &models.Description{
					Value: "For this sheet pan dinner, baby potatoes, red onion, and spring onions get a head start in a hot oven, before they are joined by a side of salmon, slathered with mustard and drizzled with toasted garlic oil, which cooks alongside the vegetables for a seamless final presentation. Sommelier Erin Miller, of Charlie Palmer&#39;s Dry Creek Kitchen in Healdsburg, California, who provided the inspiration for this dish, notes that it tastes even better when served with a great wine. She recommends a glass of Hirsch Vineyards Raschen Ridge Sonoma Coast Pinot Noir, noting, &#34;The bright acidity of the Hirsch Pinot Noir is a perfect foil for the fresh, fatty fish and flavors of garlic and lemon.&#34;",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1.5 pounds baby yellow potatoes, halved lengthwise",
						"1 large red onion, cut into 1/2-inch wedges",
						"5 spring onions (about 6 ounces), trimmed and halved lengthwise",
						"0.333 cup plus 2 tablespoons extra-virgin olive oil, divided",
						"2 teaspoons kosher salt, divided",
						"0.5 teaspoon black pepper, divided",
						"0.25 cup Dijon mustard, divided",
						"1 (2-pound) skin-on or skinless salmon side",
						"3 garlic cloves, thinly sliced (about 1 1/2 tablespoons)",
						"2 tablespoons chopped fresh tarragon",
						"2 tablespoons chopped fresh chives",
						"Lemon wedges, for serving",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat oven to 425°F. Toss together potatoes, red onion, spring onions, and 2 tablespoons oil on a large rimmed baking sheet; spread in an even layer. Sprinkle evenly with 1 teaspoon salt and 1/4 teaspoon pepper. Roast in preheated oven until vegetables begin to brown, about 20 minutes. Remove from oven, and reduce oven temperature to 325°F."},
						{Type: "HowToStep", Text: "Add 1 tablespoon mustard to vegetable mixture on baking sheet; toss to coat. Push vegetables to long edges of baking sheet. Place salmon, skin side down, lengthwise in middle of baking sheet. Spread salmon with remaining 3 tablespoons mustard; sprinkle with remaining 1 teaspoon salt and remaining 1/4 teaspoon pepper."},
						{Type: "HowToStep", Text: "Heat remaining 1/3 cup oil in a large skillet over medium-high. Add garlic; cook, stirring often, until garlic is fragrant and light golden brown, about 2 minutes. Pour hot oil mixture over salmon on baking sheet. Roast at 325°F until salmon flakes easily with a fork and vegetables are tender, 12 to 15 minutes. Remove from oven. Transfer salmon to a platter; sprinkle with tarragon and chives. Transfer vegetables to a bowl. Serve salmon and vegetables with lemon wedges."},
					},
				},
				Name:      "Sizzling Garlic Salmon with Sheet Pan Potatoes",
				TotalTime: "PT50M",
				Yield:     &models.Yield{Value: 4},
				URL:       "https://www.foodandwine.com/recipes/garlic-salmon-with-sheet-pan-potatoes",
			},
		},
		{
			name: "foodbymaria.com",
			in:   "https://www.foodbymaria.com/plant-based-summer-moussaka",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main Dishes"},
				CookTime:      "PT40M",
				Cuisine:       &models.Cuisine{Value: "Vegan"},
				DatePublished: "2021-07-05T06:08:35+00:00",
				Description:   &models.Description{},
				Keywords:      &models.Keywords{Values: "meal prep, vegan, plant-based, summer recipes, moussaka"},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"",
						"3 large white russet potatoes (peeled and cut into 1/2-1/4 inch slices)",
						"1 large eggplant (cut into 1/2- 1/4 inch slices)",
						"2 large zucchini (cut into 1/2-1/4 inch slices)",
						"4-5 tbsp (olive oil)",
						"season to taste",
						"2 tbsp dry oregano",
						"3 tbsp. olive oil",
						"1 large white onion (finely chopped)",
						"3 cloves of garlic (finely chopped)",
						"2 bay leaves",
						"Season to taste",
						"2 tbsp. dry basil",
						"1 tbsp. dry oregano",
						"1 tsp vegetable stock paste",
						"1/2 tsp cinnamon",
						"1/4 tsp cloves",
						"2 400 ml can of brown lentils (strained and drained)",
						"1 400 ml can of black beans (strained and drained)",
						"600 ml crushed Roma tomatoes",
						"1 tbsp. Coconut sugar or white sugar is fine too",
						"Sliced fresh tomato",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat your oven to 400F and line three baking sheets with parchment paper."},
						{Type: "HowToStep", Text: "Cut your peeled potatoes, zucchini and eggplant and evenly coat with olive oil, seasoning and oregano. Cook potatoes till soft, eggplant till tender and golden brown and zucchini till most of it’s liquid has evaporated (around 25-30 minutes). The reason we’re pre cooking them is so there is no moisture in the baking dish for the moussaka. You want this to be a mix of perfectly crispy and creamy, not watery!"},
						{Type: "HowToStep", Text: "To prepare your “meat” sauce all you will need in one deep pot. Start by pre-heating your olive oil and adding your onions. Cook them down on medium-low heat for around 5 minutes or until soft. Add in your garlic, salt + pepper, basil, oregano, stock paste, cinnamon and cloves and give your mixture a good stir. Cook for 3 or so more minute on medium-low heat. At this point your home should smell fabulous. Add in your lentils, black bean, tomatoes and sugar. Give it all a good stir before turning heat to low and popping on a lid and reducing for around 20 minutes. You want the sauce to reduce enough that it’s thick but not stew like! Once cooked set aside."},
						{Type: "HowToStep", Text: "To assemble, place a layer on potatoes on to a plate, then some zucchini, eggplant, lentil meat sauce, fresh tomato and repeat one more time. Garnish with fresh parsley and your choice of fixings. I love eating this with feta and tzatziki."},
					},
				},
				Name:     "Plant-Based Summer Moussaka",
				PrepTime: "PT20M",
				Yield:    &models.Yield{Value: 5},
				URL:      "https://www.foodbymaria.com/plant-based-summer-moussaka",
			},
		},
		{
			name: "foodiecrush.com",
			in:   "https://www.foodiecrush.com/gnocchi-with-pomodoro-sauce",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main Course"},
				Cuisine:       &models.Cuisine{Value: "Italian"},
				CookTime:      "PT30M",
				DatePublished: "2019-11-04T06:00:16+00:00",
				Description: &models.Description{
					Value: "This simple tomato sauce gets tons of flavor from herbs steeped in olive oil that lusciously coats potato pillows of gnocchi, topped with fresh balls of mozzarella.",
				},
				Keywords: &models.Keywords{Values: "gnocchi"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1/4 cup DeLallo extra virgin olive oil (, plus 1 tablespoon)",
						"4 stems fresh Italian flat leaf parsley",
						"4 stems fresh oregano",
						"2 stems fresh rosemary",
						"2 stems fresh basil (,plus 2 more stems for serving)",
						"1/2 yellow onion (, diced)",
						"3 cloves garlic (, pressed or minced)",
						"1 28 ounce can DeLallo San Marzano tomatoes",
						"Kosher salt and freshly ground black pepper",
						"Pinch of red pepper flakes",
						"1/4 cup heavy cream (, optional)",
						"1 16- ounce package DeLallo potato gnocchi",
						"8 ounces cherry size mozzarella balls (, cut in half)",
						"1/2 cup freshly grated Parmesan cheese",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Add 1/4 cup olive oil to a 10-inch high sided sauté pan or a saucepan over medium heat. Add the parsley, oregano, rosemary and 2 stems of basil and cook for about 5 minutes or until the herbs become crisp."},
						{Type: "HowToStep", Text: "Remove the herbs and discard then add the onion and garlic to the oil, lowering the heat if needed so the onions cook gently and don't brown. Cook until the onions are transparent, about 5-7 minutes, then crush the tomatoes with your hand and add to the pan with juice."},
						{Type: "HowToStep", Text: "Season with kosher salt, freshly ground black pepper and red pepper flakes and simmer for 30-40 minutes or until the sauce reduces and thicken, stirring occasionally. Stir in the heavy cream and remove from the heat."},
						{Type: "HowToStep", Text: "Meanwhile, bring a saucepan of water to a boil and add the gnocchi. Season generously with kosher salt and cook until the gnocchi float to the top of the boiling water."},
						{Type: "HowToStep", Text: "Drain and then place the gnocchi into the cooked sauce. Top with the halved mozzarella balls and sprinkle with Parmesan cheese then drizzle the tops of the gnocchi with the remaining olive oil."},
						{Type: "HowToStep", Text: "Broil for 5-8 minutes or until the cheese melts and the tops become crispy. Garnish with additional basil leaves and serve immediately."},
					},
				},
				Name: "Gnocchi With Pomodoro Sauce",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "229",
					Carbohydrates: "3",
					Cholesterol:   "29",
					Fat:           "22",
					Fiber:         "1",
					Protein:       "5",
					SaturatedFat:  "7",
					Servings:      "1",
					Sodium:        "207",
					Sugar:         "1",
				},
				PrepTime:  "PT10M",
				TotalTime: "PT40M",
				Yield:     &models.Yield{Value: 4},
				URL:       "https://www.foodiecrush.com/gnocchi-with-pomodoro-sauce",
			},
		},
		{
			name: "foodnetwork.co.uk",
			in:   "https://foodnetwork.co.uk/recipes/waldorf-chicken-boats",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				CookTime:      "PT10M",
				DateCreated:   "2015-11-30T11:55:59+00:00",
				DateModified:  "2020-09-29T11:10:46+00:00",
				DatePublished: "2015-11-30T11:55:59+00:00",
				Description: &models.Description{
					Value: "Introduce the kids to salad with this one that's fun to assemble and eat.",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"For the dressing:", "1/2 cup low-fat Greek yogurt",
						"1 tablespoon lemon juice", "1 tablespoon olive oil",
						"2 teaspoons apple cider vinegar", "1/2 teaspoon chopped fresh thyme leaves",
						"Salt and freshly ground black pepper", "For the salad:", "1/4 cup walnuts",
						"1 1/2 cups 1/2-inch pieces rotisserie chicken, skin and bones discarded",
						"1 small crisp apple, cored and cut into 1/2-inch pieces",
						"1/2 cup red seedless grapes, halved",
						"3 spring onions, whites and greens divided and chopped",
						"8 hearts of romaine leaves",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat the oven to 175°C."},
						{Type: "HowToStep", Text: "For the dressing: Whisk together the yogurt, lemon juice, oil, vinegar, thyme, 1/2 teaspoon salt and 1/4 teaspoon pepper in a small bowl until combined; set aside."},
						{Type: "HowToStep", Text: "For the salad: Spread the walnuts on a baking sheet, and toast until lightly browned and fragrant, 5 to 7 minutes. Let cool for 5 minutes, then break up into 1/4-inch pieces."},
						{Type: "HowToStep", Text: "To assemble: Toss the walnuts, chicken, apples, grapes and scallion whites together with the dressing in a large bowl until everything is well coated; season with salt and pepper. Scoop a scant 1/2 cup of the salad into each romaine leaf, and arrange 2 on each serving plate. Garnish with the scallion greens, and serve."},
						{Type: "HowToStep", Text: "Copyright 2015 Television Food Network, G.P. All rights reserved."},
						{Type: "HowToStep", Text: "Note: Never leave a child unattended in the kitchen. Limit the child to tasks that are safe and age-appropriate."},
						{Type: "HowToStep", Text: "From Food Network Kitchen"},
					},
				},
				Name:            "Waldorf Chicken Boats",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT20M",
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 4},
				URL:             "https://foodnetwork.co.uk/recipes/waldorf-chicken-boats",
			},
		},
		{
			name: "foodrepublic.com",
			in:   "https://www.foodrepublic.com/recipes/hand-cut-burger/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				Name:          "How To Cook A Hand-Cut Burger",
				Description: &models.Description{
					Value: "When you don't have a meat grinder, but still want a nice, juicy burger, this recipe for a hand-cut burger has a trick you'll use over and over again.",
				},
				Keywords:      &models.Keywords{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				DateModified:  "2018-06-08T15:00:40+00:00",
				DatePublished: "2018-06-08T15:00:40+00:00",
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 (1 1/2-pound) boneless rib-eye steak (preferably dry-aged)",
						"2 cups unsalted butter or rendered beef tallow, plus 2 tablespoons unsalted butter",
						"1 white onion",
						"1 (5-ounce) piece horseradish (2 to 3 inches)",
						"2 tablespoons buttermilk",
						"kosher salt",
						"4 Pain de Mie Buns or 8 slices soft slab bread",
						"16 to 24 dill pickle slices",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Chill the steak in the freezer until firm to the touch but not frozen, 15 to 20 minutes. Cut the steak into 1⁄4-inch-thick slices, then slice into 1⁄4-inch-thick strips, and then into 1⁄4-inch cubes. Remove the sinew and connective tissue but keep the fat."},
						{Type: "HowToStep", Text: "Divide the beef into four equal balls. Put a sheet of plastic wrap over a 4-inch ring mold on a cutting board or other hard surface. Put a ball in the middle of the mold and gently press down with the palm of your hand, forming a patty that is 4 inches wide. Pop it out with the plastic wrap. Put the patties on a large dish or small baking sheet and refrigerate until ready to cook."},
						{Type: "HowToStep", Text: "Melt 2 cups of the butter in a pot over medium heat. (Why yes, that is a lot of butter, but it’s used to fully submerge the onion while it cooks; you will not eat 2 cups of butter in this burger.) Add the onion, turn the heat to low, and gently cook at a bare simmer until the onion is tender, about 20 minutes. The onion should be cooked but still al dente, so there’s some texture and a slight hit of sharpness yet not enough that you’ll taste onion the rest of the day. Remove the onion from the butter and drain on a paper towel."},
						{Type: "HowToStep", Text: "While the onion cooks, make a horseradish sauce. In a bowl, mix the grated horseradish with the buttermilk and a pinch of salt. Stir to combine and refrigerate until ready to use."},
						{Type: "HowToStep", Text: "Before you begin cooking the burgers, get the buns toasting. Heat a cast-iron skillet or similar surface over medium-low heat. Slice the buns in half horizontally. Smear the remaining 2 tablespoons of butter on the buns and place, butter side down, on the hot surface, working in batches if necessary. Toast until golden brown, 6 to 8 minutes, adjusting the heat if necessary. You want to do your best to time their completion to the burger cooking."},
						{Type: "HowToStep", Text: "While the buns toast, cook the patties. Heat a cast-iron skillet or grill over high heat. Use a spatula to handle the patty—it will be loose, so be careful. Salt both sides of each patty and put them on the hot skillet. Cook on one side, about 1 minute, then flip the patties and cook until rare, another minute."},
						{Type: "HowToStep", Text: "Place a patty on a bottom bun and top with some pickles and onions. Slather 1 1⁄2 teaspoons horseradish sauce on the top bun and cap it off. Repeat."},
					},
				},
				NutritionSchema: &models.NutritionSchema{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{},
				URL:             "https://www.foodrepublic.com/recipes/hand-cut-burger/",
			},
		},
		{
			name: "foolproofliving.com",
			in:   "https://foolproofliving.com/chocolate-chili/",
			want: models.RecipeSchema{
				AtContext: atContext,
				AtType:    &models.SchemaType{Value: "Recipe"},
				Category:  &models.Category{Value: "Soup"},
				CookTime:  "PT30M",
				Cuisine:   &models.Cuisine{Value: "Mexican Cuisine"},
				Name:      "Chocolate Chili Recipe",
				Description: &models.Description{
					Value: "This Chocolate Chili recipe is a one-pot meal that you can make under 45 minutes. Made with unsweetened chocolate, cocoa powder, sweet potatoes, and beans, it is the perfect balance of sweet and savory with a deep rich mole-like flavor.",
				},
				Keywords:      &models.Keywords{Values: "chocolate chili, Dark Chocolate Chili"},
				Image:         &models.Image{Value: anUploadedImage.String()},
				DatePublished: "2022-01-03T11:58:00+00:00",
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 tablespoon vegetable oil",
						"1 large onion (chopped ~ approximately 1 cup)",
						"2 jalapenos (seeded and chopped (A medium-sized bell pepper would also work))",
						"2 tablespoons chili powder",
						"1 tablespoon ground cumin",
						"1 tablespoon ground coriander",
						"1 lbs ground turkey (I used 93%)",
						"4 cloves garlic (minced)",
						"1 tablespoon tomato paste",
						"2 tablespoons unsweetened cocoa powder",
						"2 oz. unsweetened chocolate (roughly chopped)",
						"1 large or 2 medium sweet potatoes (peeled and cut into 1-inch cubes)",
						"1 15 oz. can of black beans (, drained and rinsed)",
						"1 15 oz. can of red kidney beans (, drained and rinsed)",
						"1 28 oz. can of diced tomatoes (with their juices)",
						"3 cups chicken stock",
						"1 teaspoon kosher salt",
						"½ teaspoon black pepper",
						"½ cup fresh cilantro (roughly chopped - (Optional) plus more as garnish)",
						"¼ cup sour cream (optional)",
						"¼ cup pumpkin seeds - options;",
						"1 lime (cut into wedges)",
						"Maple syrup - optional",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Heat oil in a large heavy-bottomed pot (like a Dutch oven) over medium-high heat. Add onion, jalapenos, chili powder, ground cumin, and ground coriander. Cook, stirring frequently, for 5-6 minutes or until onions are softened."},
						{Type: "HowToStep", Text: "Add in the ground turkey and cook, breaking the meat with a wooden spoon, until no pink parts remain. Stir in the garlic and tomato paste and cook for another minute or so."},
						{Type: "HowToStep", Text: "Add in the cocoa powder, unsweetened chocolate, sweet potatoes, black beans, kidney beans, tomatoes, chicken stock, and salt and black pepper. Give it a big stir. Bring it to a boil, turn the heat down to medium-low and let it simmer for 20-25 minutes or until sweet potatoes are fully cooked. If using, stir in the chopped cilantro."},
						{Type: "HowToStep", Text: "Ladle into bowls. Top each serving with a dollop of sour cream on top and drizzle with a teaspoon of maple syrup and a squeeze of fresh lime juice. Garnish with pumpkin seeds and chopped cilantro. Serve."},
					},
				},
				NutritionSchema: &models.NutritionSchema{
					Calories:       "274",
					Carbohydrates:  "26",
					Cholesterol:    "50",
					Fat:            "11",
					Fiber:          "6",
					Protein:        "25",
					SaturatedFat:   "5",
					Servings:       "1",
					Sodium:         "797",
					Sugar:          "7",
					TransFat:       "1",
					UnsaturatedFat: "5",
				},
				PrepTime:  "PT10M",
				TotalTime: "PT40M",
				Yield:     &models.Yield{Value: 6},
				URL:       "https://foolproofliving.com/chocolate-chili/",
			},
		},
		{
			name: "forksoverknives.com",
			in:   "https://www.forksoverknives.com/recipes/vegan-snacks-appetizers/crispy-buffalo-cauliflower-bites/",
			want: models.RecipeSchema{
				AtContext: atContext,
				AtType:    &models.SchemaType{Value: "Recipe"},
				Category: &models.Category{
					Value: "vegan snacks",
				},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				CookTime:      "PT0D0H35M",
				DatePublished: "2017-01-27 15:29:56",
				Description: &models.Description{
					Value: "It took a lot of trial and error to find the right coating that would not draw out the moisture and would make the florets crisp, so I am pleased that it has turned out to be a very simple recipe. You will not need to add salt as the sauces have enough salt to season them. Either a smoky barbecue sauce or Frank’s hot sauce would work well, but if you are like me and prefer sweet and spicy, then try a little bit of both. Serve with ranch or Caesar dressing on the side if you wish, or whip up a batch of Spinach Ranch Dip. Note: The buffalo cauliflower bites will get softer once they are coated with the sauce, so hold off tossing until the very last minute",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"⅔ cup brown rice flour",
						"2 tablespoons almond flour",
						"1 tablespoon tomato paste",
						"2 teaspoons garlic powder",
						"2 teaspoons onion powder",
						"2 teaspoons smoked paprika",
						"1 teaspoon dried parsley",
						"1 head cauliflower, cut into 2-inch florets",
						"⅓ cup Frank’s hot sauce or barbecue sauce",
						"<a href=\"https://www.forksoverknives.com/recipes/spinach-ranch-dip/#gs.MasyuTc\" target=\"_blank\" rel=\"noopener\">Spinach Ranch Dip</a>",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat oven to 450°F. Line 2 baking sheets with parchment paper."},
						{Type: "HowToStep", Text: "Combine the brown rice flour, almond flour, tomato paste, garlic powder, onion powder, paprika, parsley, and ⅔ cup of water in a blender. Puree until the batter is smooth and thick. Transfer to a bowl and add the cauliflower florets; toss until the florets are well coated with the batter."},
						{Type: "HowToStep", Text: "Arrange the cauliflower in a single layer on the prepared baking sheets, making sure that the florets do not touch one another. Bake for 20 to 25 minutes, until crisp on the edges. They will not get crispy all over while still in the oven."},
						{Type: "HowToStep", Text: "Remove from the heat and let stand for 3 minutes to crisp up a bit more. Transfer to a bowl and drizzle with the sauce. Serve immediately."},
					},
				},
				Name:            "Crispy Buffalo Cauliflower Bites",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT0D0H0M",
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				TotalTime:       "PT0D0H35M",
				Yield:           &models.Yield{Value: 6},
				URL:             "https://www.forksoverknives.com/recipes/vegan-snacks-appetizers/crispy-buffalo-cauliflower-bites/",
			},
		},
		{
			name: "forktospoon.com",
			in:   "https://forktospoon.com/air-fryer-blooming-onion-bites",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Appetizer"},
				CookTime:      "PT15M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2023-11-20T11:59:57+00:00",
				Description: &models.Description{
					Value: "Air Fryer Blooming Onion Bites -- Step into a world of crispy, flavorful delight with our Air Fryer Blooming Onion Bites recipe!",
				},
				Keywords: &models.Keywords{Values: "Air Fryer Blooming Onion Bites"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"12 ounces pearl onions (frozen)", "2 tablespoon olive oil",
						"½ teaspoon paprika", "½ teaspoon oregano", "½ teaspoon ground thyme",
						"½ teaspoon cumin", "½ teaspoon kosher salt", "½ teaspoon black pepper",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Mix the Seasonings: In a large bowl, combine olive oil, paprika, oregano, ground thyme, cumin, salt, and pepper."},
						{Type: "HowToStep", Text: "Add Onions: Take the frozen pearl onions (do not defrost) and add them to the bowl. Toss them gently to ensure they are evenly coated with the seasoning mix."},
						{Type: "HowToStep", Text: "Air Fry: Preheat your air fryer. Place the seasoned onions in the air fryer basket and cook at a high temperature (around 400°F or 200°C) for about 10-15 minutes, or until they are golden brown and crispy. Shake the basket halfway through for even cooking."},
						{Type: "HowToStep", Text: "Serve: Once cooked, let them cool slightly before serving. These onion bites are perfect as a snack or appetizer, served with your favorite dipping sauce."},
					},
				},
				Name: "Air Fryer Blooming Onion Bites",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "66",
					Carbohydrates:  "6",
					Fat:            "5",
					Fiber:          "1",
					Protein:        "1",
					SaturatedFat:   "1",
					Servings:       "1",
					Sodium:         "197",
					Sugar:          "2",
					UnsaturatedFat: "4",
				},
				PrepTime:  "PT5M",
				TotalTime: "PT20M",
				Yield:     &models.Yield{Value: 6},
				URL:       "https://forktospoon.com/air-fryer-blooming-onion-bites",
			},
		},
		{
			name: "francescakookt.nl",
			in:   "https://www.francescakookt.nl/vegetarische-rode-kool-stamppot-jus",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Hoofdgerecht"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateModified:  "2022-05-16T09:46:59+02:00",
				DatePublished: "2017-09-21T04:00:03+02:00",
				Description: &models.Description{
					Value: "Deze vegetarische rode kool stamppot met groente gehaktballetjes en vega jus is door de korte bereidingstijd perfect voor doordeweeks!",
				},
				Keywords: &models.Keywords{Values: "binnen 30 minuten,recept,rode kool"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"900 gr CêlaVíta Oma’s kruimige aardappelen",
						"melk of plantaardige kookroom", "olijfolie of boter",
						"500 gr gekookte rode kool", "1 tl nootmuskaat", "zwarte peper", "zeezout",
						"200 gr groente gehaktballetjes (400 gr voor grote eters)", "40 gr boter",
						"1 sjalot, gesnipperd", "500 ml warme groentebouillon", "sojasaus",
						"klein handje platte peterselie, fijngehakt",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Voor de stamppot kook je de aardappelen 14 minuten in een bodempje water. Giet af en schep ze terug in de pan. Schenk er een scheut melk/kookroom bij en een paar klontjes boter/scheut olijfolie en stamp tot een puree. Roer de gekookte rode kool erdoor en breng op smaak met nootmuskaat, zwarte peper en zout."},
						{Type: "HowToStep", Text: "In de tussentijd verhit je een koekenpan en bak je de groenteballetjes rondom bruin aan. Schep uit de pan en houd warm onder aluminiumfolie."},
						{Type: "HowToStep", Text: "Smelt een kwart van de boter in de pan en fruit hier 2 minuten de sjalot in."},
						{Type: "HowToStep", Text: "Voeg de rest van de boter toe en laat op laag vuur smelten. Roer nu de bloem erdoor en blijf een paar minuten roeren totdat je bloem ‘gebakken’ is. Deze roux is de basis voor je vegetarische jus. Schenk nu langzaam de warme bouillon erbij en klop met een garde totdat je een jus hebt die je qua dikte zelf goed vindt. Je kunt altijd nog wat extra bouillon toevoegen. Breng op smaak met sojasaus."},
						{Type: "HowToStep", Text: "Serveer de rode kool stamppot met groente gehaktballetjes, jus en garneer met fijngehakte peterselie. Eet smakelijk!"},
					},
				},
				Name:            "Vegetarische rode kool stamppot met jus - Francesca Kookt",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT30M",
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 4},
				URL:             "https://www.francescakookt.nl/vegetarische-rode-kool-stamppot-jus",
			},
		},
		{
			name: "franzoesischkochen.de",
			in:   "https://www.franzoesischkochen.de/navettes-aus-marseille/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Alte französische Rezepte"},
				CookTime:      "PT30M",
				Cuisine:       &models.Cuisine{Value: "französische Rezepte"},
				DateModified:  "2022-03-09T15:14:09+02:00 ",
				DatePublished: "2022-03-09T15:14:09+02:00 ",
				Description:   &models.Description{Value: "Ein einfaches Rezept mit Schritt-für-Schritt-Fotos und vielen Tipps über das Thema: Navettes aus Marseille"},
				Keywords:      &models.Keywords{Values: "französisch,frankreich,Alte französische Rezepte,Einfachste Rezepte,In der Boulangerie,Kekse &amp; Plätzchen,Provence,Traditionelle Rezepte,Typisch französische Kuchen"},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 Ei",
						"160g Mehl T55",
						"20 g Olivenöl",
						"60 g Honig",
						"1 TL Orangenblütenwasser",
						"1 kleine Prise Salz. Milch zum Pinseln.",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Das Ei mit dem Honig, Orangenblütenwasser und Olivenöl rühren...."},
						{Type: "HowToStep", Text: "Kleine Teigkugels (25 bis 30g ) nehmen, wie Knete in die Länge ausrollen. Sie sollten eine ovale Form oder besser eine Schiff-Form bekommen. Die geformten Navette auf einem mit Backpapier belegten Backblech legen. Die Navettes in der Mitte entlang anschneiden."},
						{Type: "HowToStep", Text: "Backen: 180°C Umluft für 12 bis 15 Minuten. (es kommt darauf an, ob Ihr eure Navettes brauner mögt wie ich oder lieber hell!)"},
					},
				},
				Name:      "Navettes aus Marseille",
				PrepTime:  "PT60M",
				TotalTime: "PT90M",
				Yield:     &models.Yield{Value: 3},
				URL:       "https://www.franzoesischkochen.de/navettes-aus-marseille/",
			},
		},
		{
			name: "fredriksfika.allas.se",
			in:   "https://fredriksfika.allas.se/fredriks-pajer/knackig-appelpaj-med-rakram/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Fika, äppelpaj"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateCreated:   "2020-08-27T17:18:00.000000Z",
				DateModified:  "2023-01-07T09:01:57.000000Z",
				DatePublished: "2020-08-27T17:18:00.000000Z",
				Description:   &models.Description{Value: "Godaste äppelpajen"},
				Keywords:      &models.Keywords{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"5-6 äpplen som har fast fruktkött", "2 tsk kanel", "2 msk strösocker",
						"150 g smör", "1,5 dl strösocker", "0,5 dl ljus sirap", "0,5 dl vispgrädde",
						"3 dl havregryn", "1,5 dl vetemjöl", "0,5 tsk bakpulver", "0,5 tsk salt",
						"2 äggulor", "2 msk strösocker", "1 msk vaniljsocker", "2 dl vispgrädde",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Sätt ugnen på 175 grader."},
						{Type: "HowToStep", Text: "Skala, kärna ur och klyfta äpplena, blanda med socker och kanel och lägg i en pajform på cirka 20 x 30 cm."},
						{Type: "HowToStep", Text: "Smält smöret i en stekpanna eller kastrull tillsammans med strösocker, sirap och grädde."},
						{Type: "HowToStep", Text: "Blanda ner havregryn och vetemjöl blandat med bakpulver och salt och rör till en jämn smet. Ta av från värmen."},
						{Type: "HowToStep", Text: "Fördela smeten över äpplena i formen."},
						{Type: "HowToStep", Text: "Grädda i nedre delen av ugnen i ca 35-40 minuter, tills pajen är gyllenbrun. Låt svalna något innan servering."},
						{Type: "HowToStep", Text: "Råkräm – Vispa äggulor, strösocker och vaniljsocker fluffigt."},
						{Type: "HowToStep", Text: "Vispa grädden rätt fast."},
						{Type: "HowToStep", Text: "Vänd ner äggvispet i grädden."},
					},
				},
				Name:            "Fyllning",
				NutritionSchema: &models.NutritionSchema{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				TotalTime:       "PT60M",
				Yield:           &models.Yield{Value: 6},
				URL:             "https://fredriksfika.allas.se/fredriks-pajer/knackig-appelpaj-med-rakram/",
			},
		},
	}
	for _, tc := range testcases {
		t.Run(tc.name, func(t *testing.T) {
			test(t, tc)
		})
	}
}
