package scraper_test

import (
	"testing"
	"time"

	"github.com/reaper47/recipya/internal/models"
)

func TestScraper_H(t *testing.T) {
	testcases := []testcase{
		{
			name: "halfbakedharvest.com",
			in:   "https://www.halfbakedharvest.com/louisiana-style-chicken-and-rice/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main Course"},
				CookTime:      "PT50M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2022-03-23T02:00:00+00:00",
				Description: &models.Description{
					Value: "One Skillet Louisiana Style Chicken and Rice: has a variety of flavors and textures, yet it&#39;s all made in ONE skillet with pantry staple ingredients!",
				},
				Keywords: &models.Keywords{Values: "one skillet"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"2 tablespoons extra virgin olive oil",
						"1 pound boneless chicken breasts or thighs",
						"2 tablespoons cajun seasoning",
						"kosher salt and black pepper",
						"6 tablespoons salted butter",
						"1 lemon, sliced",
						"1/2 cup dry broken spaghetti or angel hair pasta",
						"1 cup long grain rice",
						"1 medium yellow onion, sliced",
						"2 bell peppers, sliced",
						"3-4 cups low sodium chicken broth",
						"3 cloves garlic, chopped",
						"1/2 cup fresh tenders herbs, cilantro + parsley",
						"chili flakes",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat the oven to 425° F."},
						{Type: "HowToStep", Text: "In a large oven-safe skillet, combine the olive oil, chicken, and cajun seasoning, toss to coat. Set the skillet over high heat. Sear on both sides until golden, 3-5 minutes. During the last 2 minutes of cooking, add 1 tablespoon of butter and lemon slices. Remove everything from the skillet."},
						{Type: "HowToStep", Text: "Add the rice and pasta. Cook until the rice is toasted, about 1 minute. Add the onion and peppers and continue to cook another 3-4 minutes, then pour in 3 cups broth. Season with salt and pepper. Bring to a boil."},
						{Type: "HowToStep", Text: "Slide the chicken, lemon slices, and any juices left on the plate back into the skillet. Bring to a boil. Cover the skillet and turn the heat down to the lowest setting possible. Allow the rice to cook 10 minutes, until most of the liquid has cooked into the rice, but not all of it. If needed add more broth. Bake, uncovered for 10-15 minutes or until the chicken is cooked through."},
						{Type: "HowToStep", Text: "Meanwhile, melt together 5 tablespoons butter, the garlic, and a pinch of chili flakes. Cook until the butter is browning. Stir in the mixed herbs."},
						{Type: "HowToStep", Text: "Serve the chicken and rice drizzled with garlic butter and topped with fresh herbs."},
					},
				},
				Name: "Skillet Louisiana Style Chicken and Rice",
				NutritionSchema: &models.NutritionSchema{
					Calories: "547",
					Servings: "1",
				},
				PrepTime:  "PT20M",
				TotalTime: "PT70M",
				Yield:     &models.Yield{Value: 6},
				URL:       "https://www.halfbakedharvest.com/louisiana-style-chicken-and-rice/",
			},
		},
		{
			name: "handletheheat.com",
			in:   "https://handletheheat.com/peanut-butter-pie/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Dessert"},
				CookTime:      "PT12M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2023-07-10T03:00:31+00:00",
				Description: &models.Description{
					Value: "This homemade Peanut Butter Pie is made from scratch with just a few ingredients and will have everyone coming back for seconds! It's CRAZY good! With step-by-step video.",
				},
				Keywords: &models.Keywords{Values: "peanut butter cups, peanut butter pie, peanut butter pie recipe, thanksgiving"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"14 whole (196 grams) chocolate graham crackers*",
						"1 tablespoon light brown sugar",
						"7 tablespoons (99 grams) unsalted butter, (melted)",
						"8 ounces (227 grams) cream cheese, (at room temperature)",
						"3/4 cup (94 grams) powdered sugar plus 2 tablespoons, (divided)",
						"1 cup (270 grams) creamy conventional peanut butter",
						"1 cup (240 grams) heavy whipping cream", "1 teaspoon vanilla extract",
						"Melted peanut butter", "Melted chocolate", "Mini Reese’s cups",
						"Peanut butter chips",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat the oven to 325°F."},
						{Type: "HowToStep", Text: "In the bowl of a food processor, process the crackers and sugar until finely ground. Add the butter and pulse until moistened. Use the bottom of a measuring cup, glass, or ramekin to press the crust mixture into the bottom and up the sides of a 9-inch pie plate. Bake until fragrant, about 10 to 12 minutes. Cool completely on a wire rack."},
						{Type: "HowToStep", Text: "In a large bowl, use an electric mixer to beat the cream cheese, 3/4 cup powdered sugar, and the peanut butter until light and fluffy, about 3 minutes."},
						{Type: "HowToStep", Text: "In a separate bowl, use an electric mixer with the whisk attachment to whip the heavy cream until thick and light. Add in the remaining 2 tablespoons of powdered sugar and the vanilla extract and continue to whip until stiff peaks form."},
						{Type: "HowToStep", Text: "Gently fold the whipped cream into the peanut butter mixture. Pour into the prepared pie shell and freeze for 3 hours or chill in the fridge at least 6 hours."},
						{Type: "HowToStep", Text: "Place your melted peanut butter and melted chocolate in separate resealable bags or piping bags. Snip off a tiny corner of the bag&#39;s tip. Squeeze slightly to drizzle the melted peanut butter and melted chocolate over your pie. Top with mini Reese&#39;s cups and peanut butter chips. Serve frozen or refrigerated."},
						{Type: "HowToStep", Text: "Store in the fridge, covered, for up to 3 days, or in the freezer for up to 1 month."},
					},
				},
				Name:      "Peanut Butter Pie",
				PrepTime:  "PT20M",
				TotalTime: "PT272M",
				URL:       "https://handletheheat.com/peanut-butter-pie/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:      "VideoObject",
							ContentURL:  "https://mediavine-res.cloudinary.com/video/upload/t_original/v1686750184/iQqyOm2s6.mp4",
							Description: "This homemade Peanut Butter Pie is made from scratch with just a few easy ingredients and will have everyone coming back for seconds! Tons of amazing chocolate and peanut butter flavor and topped with reese's. The best easy dessert idea to serve for a crowd!",
							Duration:    "PT59S",
							EmbedURL:    "https://video.mediavine.com/videos/iQqyOm2s6.js",
							Name:        "Easy Peanut Butter Pie Recipe",
							ThumbnailURL: &models.ThumbnailURL{
								Value: "https://mediavine-res.cloudinary.com/image/upload/s--MPjo6Nh3--/c_limit,f_auto,fl_lossy,h_1080,q_auto,w_1920/v1686750187/lzydttnsifro1sltfxvd.jpg",
							},
							UploadDate: time.Date(2022, 3, 31, 22, 59, 19, 0, time.UTC),
						},
					},
				},
				Yield: &models.Yield{Value: 8},
			},
		},
		{
			name: "hassanchef.com",
			in:   "https://www.hassanchef.com/2022/10/dragon-chicken.html",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "appetizer"},
				CookTime:      "PT10M",
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{Value: "Indo Chinese"},
				DatePublished: "2022-10-14",
				Description: &models.Description{
					Value: "Dragon Chicken an appetizer or snacks of Indian Chinese cuisines where deep fried chicken strips are stir fried with a spicy combination of sauces and herbs",
				},
				Keywords: &models.Keywords{Values: "Dragon Chicken"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 large Chicken breast",
						"1 teaspoon red chilly paste",
						"1 teaspoon ginger garlic paste",
						"1/4 teaspoon green chilly paste",
						"2 tablespoon cornflour",
						"1 tablespoon beaten egg or egg white",
						"1/2 of each red, yellow and green bell pepper cut into julienne",
						"1/2 of a onion cut into thin slices",
						"Oil for deep frying",
						"1/2 teaspoon chopped garlic",
						"1/2 teaspoon chopped ginger",
						"1 whole red chilly cut into pieces",
						"10 - 12 roasted or golden fried cashew nuts",
						"1/2 teaspoon red chilly sauce",
						"1/2 teaspoon red chilly paste",
						"1/3 teaspoon pepper powder",
						"1/3 teaspoon madras curry powder",
						"Salt as taste",
						"Seasoning powder(optional)",
						"Some chopped green spring onions",
						"1 tablespoon slurry (cornflour)",
						"2 tablespoon cooking oil",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Dragon Chicken is made using boneless chicken breast pieces. Here I have taken only one single chicken breast and sliced it into two parts. Then cut them into thin strips around half inch width. Now add half teaspoon red chilly paste, ginger garlic paste, around 1/4 teaspoon green chilli paste, 2 tablespoon corn flour, 2 tablespoon beaten egg and salt as per your taste. Mix them nicely so that all the chicken strips are get evenly coated. Cover and let them marinated for 5 to 6 minutes to absorb the flavours."},
						{Type: "HowToStep", Text: "Cut the bell peppers and capsicum into julienne shape and onion into thin slices. Finely chopped the ginger and garlic. You can avoid to use the bell peppers if not available at your pantry, capsicum and onion also yield a good result. You can either roast the cashew nuts or fry them till golden brown. Roughly chopped the green spring onions and cut the whole red chilly into two or three parts."},
						{Type: "HowToStep", Text: "Heat a kadai or small deep vessel pan with enough cooking oil under medium heat flame. When the oil become hot lower the gas flame to low and carefully add the chicken strips one by one into the hot oil. Fry them until become crisp golden from all sides. Remove them on a absorbent paper to absorb any excess oil."},
						{Type: "HowToStep", Text: "Heat a non stick pan or Chinese wok with one tablespoon oil under medium flame heat gas fire. Add the bell peppers, capsicum, onion and pieces of whole red chilly. Stir fry them for few seconds in high flame heat. Then add chopped onion, chopped ginger, garlic, green chilly paste and cashew nuts. Stir fry them for one minute."},
						{Type: "HowToStep", Text: "Now add red chilly paste, red chilly sauce, tomato sauce and give them a good mix."},
						{Type: "HowToStep", Text: "Add some water and cook the sauces for few seconds. Then add soya sauce, white pepper powder, salt and madras curry powder and cook further for few seconds. Now add the fried chicken strips and mix well with the sauces so that the chicken pieces are get well coated with them."},
						{Type: "HowToStep", Text: "Pour 2 tablespoon corn flour slurry over the chicken mixture and mix well. Finally sprinkle some chopped spring onions and give a final mix. Remove on a serving plate and serve hot."},
					},
				},
				Name: "Dragon Chicken",
				NutritionSchema: &models.NutritionSchema{
					Calories: "640",
					Fat:      "34",
					Servings: "1",
				},
				PrepTime:     "PT20M",
				ThumbnailURL: &models.ThumbnailURL{},
				Tools:        &models.Tools{Values: []models.HowToItem{}},
				TotalTime:    "PT30M",
				URL:          "https://www.hassanchef.com/2022/10/dragon-chicken.html",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:      "VideoObject",
							ContentURL:  "https://youtu.be/9yCRMQ7uX24",
							Description: "Dragon Chicken an appetizer or snacks of Indian Chinese cuisines where deep fried chicken strips are stir fried with a spicy combination of sauces and herbs",
							Name:        "Dragon Chicken",
							ThumbnailURL: &models.ThumbnailURL{
								Value: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjVPyaqbaCDbK5VdlCoe93-7wQjDmM4jVCrnuGlne0QDqUKlwfzat-Z2RS7GSFujClIpZUZIn7Q0-J75jr4LFCkJu_OwOc-YTIw30WnvpC0lH9vhMGjSDE-FmIvvg0m6dv2KlFRo1YcfA804XBHPp1AeOpf0tA0qoMFzWKHo4tSjUtrL_TJ5a7HP24w/s4623/IMG_20220906_222143.webp",
							},
						},
					},
				},
				Yield: &models.Yield{Value: 1},
			},
		},
		{
			name: "headbangerskitchen.com",
			in:   "https://headbangerskitchen.com/recipe/keto-chicken-adobo/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main Dish"},
				CookTime:      "PT25M",
				Cuisine:       &models.Cuisine{Value: "Filipino"},
				DatePublished: "2021-10-06T17:23:00+00:00",
				Description: &models.Description{
					Value: "A Keto version of a classic Filipino chicken adobo",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"6 Chicken Thighs (Bone in and Skin On)",
						"1/2 tbsp Avocado Oil",
						"8 cloves garlic (I used small cloves)",
						"1/2 tbsp Whole Black Peppercorns",
						"4 small bay leaves",
						"1/2 tsp Black Pepper Powder",
						"60 ml dark soya sauce or coconut aminos",
						"80 ml cane vinegar or apple cider vinegar",
						"2 tsp Keto sweetener (1:1 sugar substitute)",
						"spring onion greens for garnish",
						"salt as needed",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Get a large, deep skillet on the stove and add a good glug of oil to it. I’m using avocado oil."},
						{Type: "HowToStep", Text: "Once the oil is hot, place your chicken thighs in the pan skin side down. Let the chicken cook till the skin is crispy, about 3-4 minutes."},
						{Type: "HowToStep", Text: "Using the flat of a knife, smash the eight cloves of garlic."},
						{Type: "HowToStep", Text: "Flip the chicken over and add in the aromats – the smashed garlic, the whole bay leaves and peppercorns – and let everything fry till fragrant, about a minute or two."},
						{Type: "HowToStep", Text: "Deglaze the pan with a splash of water, then add in the black pepper, soy sauce and apple cider vinegar and give it all a good mix. Flip the chicken again and let everything come to a boil."},
						{Type: "HowToStep", Text: "Cook the chicken for about 10 minutes, flipping the pieces halfway through."},
						{Type: "HowToStep", Text: "Check the seasoning in the sauce, then add about two teaspoons worth of Keto sweetener. You may need to adjust this depending on the sweetener you’re using, so taste, taste, taste before adding any more."},
						{Type: "HowToStep", Text: "After your 10 minutes are up, remove the chicken from the sauce, and let the sauce continue reducing. You want it to become a sticky, syrupy consistency."},
						{Type: "HowToStep", Text: "Once the sauce is reduced, add the chicken back in and flip it a few times till it’s completely basted and bathed in that sauce. Finish with some spring onion greens and serve over plain cauli rice."},
					},
				},
				Name:      "Keto Chicken Adobo",
				PrepTime:  "PT5M",
				TotalTime: "PT30M",
				Yield:     &models.Yield{Value: 6},
				URL:       "https://headbangerskitchen.com/recipe/keto-chicken-adobo/",
			},
		},
		{
			name: "healthylittlefoodies.com",
			in:   "https://www.healthylittlefoodies.com/broccoli-tots/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Side Dish"},
				CookTime:      "PT20M",
				Cuisine:       &models.Cuisine{Value: "Western"},
				DatePublished: "2021-09-05T09:55:32+00:00",
				Description: &models.Description{
					Value: "Crispy on the outside and soft on the inside, these broccoli tots are sure to be enjoyed by all ages.",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"2 medium broccoli (, 550g / 19.5 oz)",
						"2 eggs",
						"¾ cup (60g) almond meal/flour",
						"¾ packed cup (75g) sharp cheddar cheese",
						"2 garlic cloves (,minced)",
						"½ tsp salt (,optional - do not add for baby)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat oven to 375℉/190℃ and line a baking sheet with parchment paper."},
						{Type: "HowToStep", Text: "Cut the florets off the broccoli and break them up into medium pieces. Remove the tough outer skin of the stem and then cut the stem into pieces around 1-2 cm / ½-¾ inch in size."},
						{Type: "HowToStep", Text: "Steam (or boil) the stems for 1 minute and then add the florets and steam for a further 3-4 minutes, or until soft. Drain well"},
						{Type: "HowToStep", Text: "Chop the cooked broccoli up and transfer to a large mixing bowl."},
						{Type: "HowToStep", Text: "Add the cheese, egg, almond meal and garlic and mix well to combine. Mash any bigger pieces of broccoli up as you mix."},
						{Type: "HowToStep", Text: "Scoop a heaped tablespoon of the mixture and form it into a tot. Place on prepared tray. Repeat with the remaining mixture (It should make around 23 -25 tots)."},
						{Type: "HowToStep", Text: "Spray with oil (optional) then bake for 20 minutes, or until golden."},
						{Type: "HowToStep", Text: "Serve with a dip of choice."},
					},
				},
				Keywords: &models.Keywords{Values: "Broccoli Tots"},
				Name:     "Broccoli Tots",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "39",
					Carbohydrates:  "2",
					Cholesterol:    "16",
					Fat:            "3",
					Fiber:          "1",
					Protein:        "2",
					SaturatedFat:   "1",
					Servings:       "1",
					Sodium:         "31",
					Sugar:          "1",
					TransFat:       "1",
					UnsaturatedFat: "2",
				},
				PrepTime:  "PT20M",
				TotalTime: "PT40M",
				URL:       "https://www.healthylittlefoodies.com/broccoli-tots/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:      "VideoObject",
							ContentURL:  "https://mediavine-res.cloudinary.com/video/upload/t_original/v1630820374/ltvoszmwvluaw6vyhycl.mp4",
							Description: "Video showing how to make broccoli tots. Cooked broccoli, egg, almond meal, garlic and cheese are mixed together to form tablespoon-sized tots. They are then baked for 20 mins until golden and crispy.",
							Duration:    "PT53S",
							EmbedURL:    "https://video.mediavine.com/videos/ltvoszmwvluaw6vyhycl.js",
							Name:        "Broccoli Tots",
							ThumbnailURL: &models.ThumbnailURL{
								Value: "https://mediavine-res.cloudinary.com/image/upload/s--LyyrRVz---/c_limit,f_auto,fl_lossy,h_1080,q_auto,w_1920/v1630820338/lpr9iq9ohbmxudkjmgua.jpg",
							},
							UploadDate: time.Date(2021, 9, 5, 5, 40, 38, 0, time.UTC),
						},
					},
				},
				Yield: &models.Yield{Value: 25},
			},
		},
		{
			name: "heatherchristo.com",
			in:   "https://heatherchristo.com/2020/05/03/13229/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				CookTime:      "PT12M",
				Description:   &models.Description{Value: "Good morning! I am up early on a Sunday morning of what has not really been my finest week. This quarantine thing has definitely been fascinating and I am sure each and every household could be really and truly great control groups for different psychological experiments at this point LOL! But after a few gloomy …"},
				Keywords:      &models.Keywords{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"Lemon Sugar:",
						"¾ cup sugar",
						"2 tablespoons lemon zest",
						"Scones:",
						"6 tablespoons non-dairy milk (I used full-fat oat milk)",
						"2 tablespoons fresh lemon juice",
						"2 cups all-purpose gluten-free baking flour (i used bob's red mill in dark red bag)",
						"½ cup lemon sugar",
						"2 teaspoons baking powder",
						"½ teaspoon baking soda",
						"½ teaspoon xanthum gum",
						"½ teaspoon kosher salt",
						"6 tablespoons vegan butter or butter flavored shortening",
						"½ cup blueberries",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat the oven to 400 degrees and prepare a sheet pan with a silpat or with parchment paper."},
						{Type: "HowToStep", Text: "For the Lemon Sugar:"},
						{Type: "HowToStep", Text: "In a small bowl, combine the sugar and the 2 Tablespoons of finely grated zest of lemon (this takes about two large lemons and I like to use a rasp.) Gently stir together- the sugar will get clumpy, and set aside."},
						{Type: "HowToStep", Text: "For the Scones:"},
						{Type: "HowToStep", Text: "In a small bowl, combine the non-dairy milk and the lemon juice and set aside."},
						{Type: "HowToStep", Text: "In the bowl of a food processor, add all of the dry ingredients, including the ½ cup of the lemon sugar. Pulse everything together until well combined."},
						{Type: "HowToStep", Text: "Add in the 6 tablespoons of vegan butter or shortening and pulse until you have a coarse crumb, about 15-20 seconds. Then with the processor running, stream in the milk and lemon juice combination and pulse until the dough is uniform. You will have a wet sticky dough."},
						{Type: "HowToStep", Text: "I dropped the dough by big “rustic” spoonfuls onto the prepared baking sheets- I got 6 large scones. Then I stuck (with my finger pushing them in!) about 8 blueberries into each scone, making sure some of them were all the way inside the scone, and some were sticking out of the top or sides."},
						{Type: "HowToStep", Text: "Generously divide the remaining ¼ cup of lemon sugar over the tops of the scones and then bake them for 12-13 minutes until golden around the edges. I let them cool on the sheet pan for a few minutes before serving them. THey are wonderful all on their own, or served with berry jam."},
					},
				},
				Name:            "Lemon Blueberry Scones with Lemon Sugar (Vegan and Gluten-free)",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT15M",
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 6},
				URL:             "https://heatherchristo.com/2020/05/03/13229/",
				Video:           &models.Videos{},
			},
		},
		{
			name: "hellofresh.com",
			in:   "https://www.hellofresh.com/recipes/creamy-shrimp-tagliatelle-5a8f0fcbae08b52f161b5832",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "main course"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{Value: "North America"},
				DatePublished: "2018-02-22T18:45:31+00:00",
				Description: &models.Description{
					Value: "Pronto! Pronto! You can make this dinner recipe with the lightning speed of an Italian race car. Thanks to fresh tagliatelle, which cooks faster than the dried kind, you arrive at al dente perfection in a matter of minutes. The shrimp and heirloom tomatoes only need a quick toss in the pan, too, becoming tender on the count of uno, due, tre.",
				},
				Keywords: &models.Keywords{Values: "Spicy,Dinner Ideas,SEO"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"2 clove Garlic",
						"2 unit Scallions",
						"1 unit Chili Pepper",
						"10 ounce Heirloom Grape Tomatoes",
						"1 unit Lemon",
						"10 ounce Shrimp",
						"9 ounce Tagliatelle Pasta",
						"4 tablespoon Sour Cream",
						"1 teaspoon Olive Oil",
						"2 tablespoon Butter",
						"Salt",
						"Pepper",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Wash and dry all produce. Bring a large pot of salted water to a boil. Mince garlic. Trim, then thinly slice scallions, keeping greens and whites separate. Finely mince chili, removing seeds and ribs for less heat. Halve tomatoes. Cut lemon into wedges. Rinse shrimp and pat dry with a paper towel."},
						{Type: "HowToStep", Text: "Heat a drizzle of olive oil in large pan over medium-high heat. Add garlic, scallion whites, and chili (to taste). Cook until fragrant, about 30 seconds. Add shrimp and cook, tossing, until starting to turn pink but not quite cooked through, 1-2 minutes. Season with salt and pepper."},
						{Type: "HowToStep", Text: "Once water is boiling, add tagliatelle to pot. (TIP: If any noodles are stuck together, separate them first.) Cook, stirring occasionally, until al dente, 4-5 minutes. Carefully scoop out and reserve ¼ cup pasta cooking water, then drain."},
						{Type: "HowToStep", Text: "Meanwhile, add tomatoes to pan with shrimp. Cook, tossing, until wilted and juicy, 2-3 minutes. Season with salt and pepper. Remove from heat and set aside until pasta is ready. TIP: If you like it extra hot, add any remaining chili (to taste) at this point."},
						{Type: "HowToStep", Text: "Once tagliatelle is done cooking, return pan with shrimp and tomatoes to medium heat and add tagliatelle and 2 TBSP butter. Toss to combine and melt butter. Season with salt and pepper."},
						{Type: "HowToStep", Text: "Remove pan from heat and stir in sour cream, a squeeze of lemon, and as much pasta cooking water as needed to reach a saucy consistency. Season with salt and pepper. Divide between plates or bowls and garnish with scallion greens. Serve with lemon wedges on the side for squeezing over."},
					},
				},
				Name: "Creamy Shrimp Tagliatelle with Heirloom Tomatoes, Garlic, and Chili",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "750",
					Carbohydrates: "86",
					Cholesterol:   "350",
					Fat:           "27",
					Fiber:         "5",
					Protein:       "50",
					SaturatedFat:  "12",
					Sodium:        "880",
					Sugar:         "9",
				},
				ThumbnailURL: &models.ThumbnailURL{
					Value: "https://img.hellofresh.com/f_auto,fl_lossy,h_300,q_auto,w_450/hellofresh_s3/image/5a8f0fcbae08b52f161b5832-033c9a4a.jpg",
				},
				Tools:     &models.Tools{Values: []models.HowToItem{}},
				TotalTime: "PT20M",
				Yield:     &models.Yield{Value: 2},
				URL:       "https://www.hellofresh.com/recipes/creamy-shrimp-tagliatelle-5a8f0fcbae08b52f161b5832",
				Video:     &models.Videos{},
			},
		},
		{
			name: "homebrewanswers.com",
			in:   "https://homebrewanswers.com/banana-wine-recipe",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "wine"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateModified:  "2019-10-27T00:00:00Z",
				DatePublished: "2017-11-02T00:00:00Z",
				Description: &models.Description{
					Value: "Banana wine might sound odd, believe me, I was unsure of how this wine recipe would taste too but it is definitely worth trying. Bananas are full of sugar and are one of the sweetest fruits available to most people. This sweetness is perfect for winemaking and with just a few additions to balance the […]",
				},
				Keywords: &models.Keywords{Values: "banana, wine, brewing"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"4.5 litres Water", "1.4 kg / 3lb Bananas", "900g / 2lb Sugar",
						"1/4 tsp Tannin", "3 tsp Acid Blend", "1/2 tsp Pectic Enzyme",
						"1 tsp Yeast Nutrient", "1 Campden Tablet",
						"1 Sachet Yeast (Lallemand EC-1118 is a good choice but experiment with others)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{
							Text: "Bring half of the water to a boil in the large stockpot. Whilst the water is heating up slice the bananas including the skins and secure them in the straining bag. Submerge the straining bag in the boiling water and simmer gently for 30 minutes.",
							Type: "HowToStep",
						},
						{
							Text: "After simmering for 30 minutes remove the pot from the heat. Lift out the straining bag with the bananas and set it to one side for a moment. Pour the liquid from the pot into a sanitised fermenting bucket and then add the straining bag with the bananas as well.",
							Type: "HowToStep",
						},
						{
							Text: "Take the remaining half of the water and add to the stockpot with the sugar. Heat to a boil and stir to dissolve the sugar and prevent it from burning. Simmer for a few minutes, remove from the heat and then add this to the fermenter. Along with this add the acid blend, tannin and yeast nutrients. Allow cooling to room temperature.",
							Type: "HowToStep",
						},
						{
							Text: "Once cooled add the crushed Campden tablet and mix thoroughly, allow to stand for at least 12 hours.",
							Type: "HowToStep",
						},
						{
							Text: "After at least 12 hours add the pectic enzyme and mix thoroughly. 24 hours after adding the pectic enzyme add the yeast by sprinkling it onto the surface of the must, fit a lid and airlock. Fermentation will begin a few days after this.",
							Type: "HowToStep",
						},
						{
							Text: `<img decoding="async" width="478" height="640" src="https://homebrewanswers.com/wp-content/uploads/2015/09/1227133.jpg" alt="Wine Additives" class="wp-image-419"/>`,
							Type: "HowToStep",
						},
						{
							Text: "Allow fermentation to progress for a week stirring daily, after this remove the straining bag and the remains of the banana. Leave for a further 3 days and the fermentation should have died down completely. At this point, you can syphon the banana wine into a demijohn or carboy, fit with a bung and airlock.",
							Type: "HowToStep",
						},
						{
							Text: "Allow the wine to condition in the demijohn for 3 – 4 months racking to a sanitised carboy once or twice after sediment builds up.",
							Type: "HowToStep",
						},
						{
							Text: "After conditioning, for at least 4 months or up to 6 you are ready to bottle the wine. You may want to sample the banana wine and back sweeten it if you prefer a less dry or sweeter wine. Once bottled I like to set aside a few bottles for a number of months and you will notice the banana wine will keep improving with age up to a couple of years.",
							Type: "HowToStep",
						},
					},
				},
				Name:            "Banana Wine Recipe – A Wine You Need To Try For Yourself",
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools: &models.Tools{
					Values: []models.HowToItem{
						{Quantity: 1, Text: "Large Stock Pot", Type: "HowToTool"},
						{Quantity: 1, Text: "Small Fermenting Bucket", Type: "HowToTool"},
						{Quantity: 1, Text: "Demijohn", Type: "HowToTool"},
						{Quantity: 1, Text: "Syphon", Type: "HowToTool"},
						{Quantity: 1, Text: "Fine Straining Bag", Type: "HowToTool"},
						{Quantity: 1, Text: "Airlock & Bung", Type: "HowToTool"},
					},
				},
				Yield: &models.Yield{Value: 1},
				URL:   "https://homebrewanswers.com/banana-wine-recipe/",
			},
		},
		{
			name: "homebrewanswers2.com",
			in:   "https://homebrewanswers.com/pomegranate-wine-recipe/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "wine"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateModified:  "2022-03-29T10:57:13+00:00",
				DatePublished: "2022-03-16T14:13:48+00:00",
				Description: &models.Description{
					Value: "Pomegranate is a peculiar fruit and when I was thinking about making a pomegranate wine all I could think about was all those seeds. Fear not, this recipe is really simple to make and results in a great wine that is tannic and refreshing at the same time. The part of the pomegranate you eat […]",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"6 Pomegranates",
						"4.5 litres Water",
						"250ml White Grape Concentrate",
						"800g Sugar",
						"1 tsp Acid Blend",
						"1/4 tsp Wine Tannin",
						"1 tsp Pectic Enzyme",
						"1 tsp Yeast Nutrient",
						"1 Campden Tablet",
						"1 Sachet Wine Yeast\u00a0(see this guide on wine yeasts for a selection)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{
							Text: "Prepare the pomegranate by slicing in half and hitting the back to knock out the arils and juice into a bowl. See this guide for help preparing the pomegranate.",
							Type: "HowToStep",
						},
						{
							Text: "Take half the quantity of water and combine in a large heavy-based pan with all the sugar. Bring to a boil, stirring to dissolve the sugar and simmer for a few minutes before removing from the heat.",
							Type: "HowToStep",
						},
						{
							Text: "In the sanitised fermenting vessel, add the straining bag and tip in all the pomegranate arils and juice. Use a potato masher to press the pomegranate and secure the straining bag.",
							Type: "HowToStep",
						},
						{
							Text: "Add the hot sugar syrup to the fermenter and give everything a stir and then add the remaining water to cool everything down. Leave for a few hours to cool.",
							Type: "HowToStep",
						},
						{
							Text: "Add the Campden tablet, wine tannin, acid and yeast nutrient and then stir to combine with a sanitised spoon. Cover the fermenter and leave overnight. Take a hydrometer reading at this point if you wish to know the exact specific gravity.",
							Type: "HowToStep",
						},
						{
							Text: "The following day add the pectic enzyme and mix then finally sprinkle the yeast over the surface of the must. Cover the fermenter and attach the airlock to the lid and then allow fermentation to start.",
							Type: "HowToStep",
						},
						{
							Text: "Allow to ferment for around 5 – 7 days stirring the straining bag daily to aid extraction. After 5 days remove the straining bag and squeeze gently and the pulp can be discarded. Leave to settle for a day and then rack to a sanitised demijohn and add an airlock.",
							Type: "HowToStep",
						},
						{
							Text: "Allow to ferment in the demijohn. After a few weeks, the wine will have finished fermentation and begin to clear. Sediment will begin to build up and once this happens rack to a clean demijohn. Take a hydrometer reading when racking to get the final gravity.",
							Type: "HowToStep",
						},
						{
							Text: "Leave the pomegranate wine in the demijohn for at least 2 months or until completely cleared before bottling. If you prefer a sweeter wine then look at this guide on back sweetening. The wine can be stabilised and sugar added before bottling. Once bottled the wine will continue to improve with age and will peak after around a year.",
							Type: "HowToStep",
						},
					},
				},
				Name:            "Pomegranate Wine Recipe – Bright, Crisp Red Wine",
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools: &models.Tools{
					Values: []models.HowToItem{
						{Quantity: 1, Text: "Large Stock Pot", Type: "HowToTool"},
						{Quantity: 1, Text: "Small Fermenting Bucket", Type: "HowToTool"},
						{Quantity: 1, Text: "Demijohn", Type: "HowToTool"},
						{Quantity: 1, Text: "Syphon", Type: "HowToTool"},
						{Quantity: 1, Text: "Fine Straining Bag", Type: "HowToTool"},
						{Quantity: 1, Text: "Potato Masher", Type: "HowToTool"},
						{Quantity: 1, Text: "Airlock & Bung", Type: "HowToTool"},
					},
				},
				Yield: &models.Yield{Value: 1},
				URL:   "https://homebrewanswers.com/pomegranate-wine-recipe/",
				Video: &models.Videos{},
			},
		},
		{
			name: "homebrewanswers3.com",
			in:   "https://homebrewanswers.com/watermelon-wine-recipe/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtGraph:       nil,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "wine"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateModified:  "2021-03-24T19:59:39+00:00",
				DatePublished: "2021-03-24T19:59:34+00:00",
				Description: &models.Description{
					Value: "A watermelon wine is a tricky balancing act. You need to balance the delicate flavour and enhance the aroma that would be lost if the wine is too dry. This watermelon wine recipe has had multiple iterations and will show you how to make the best watermelon wine without losing that subtle flavour. Balancing Flavour […]",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"2kg Watermelon", "4 litres Water", "950g White sugar", "1/4 tsp Wine Tannin",
						"2tsp Mixed Acid", "1/2 tsp Pectic Enzyme", "1 tsp Yeast Nutrient",
						"1 Campden Tablet",
						"1 Sachet Yeast (Lalvin 71B-1122 or Mangrove Jack MA33 is a good choice but experiment with others)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{
							Text: "Heat up half the water along with the sugar in a heavy based pan. Bring to a boil for a few minutes.",
							Type: "HowToStep",
						},
						{
							Text: "In the sanitised fermenting bin add the mesh straining bag and tuck the top around the fermenter opening.",
							Type: "HowToStep",
						},
						{
							Text: "Tip the watermelon chunks into the bag and then begin mashing the fruit with the masher to crush it, don’t worry about any chunks, a rough mash is fine. This will break down the fruit and release a lot of juice.",
							Type: "HowToStep",
						},
						{
							Text: "Once the melon is crushed pour over the boiling sugar solution and give a good mix with a sanitised spoon. Then add the remaining water to bring the temperature down.",
							Type: "HowToStep",
						},
						{
							Text: "Add the acid, tanning and yeast nutrient, mix with a sanitised spoon, cover with the lid leave to stand until cooled.",
							Type: "HowToStep",
						},
						{
							Text: "Once cooled to ambient temperature add the Campden tablet, cover and leave to stand overnight or at least 12 hours. A hydrometer reading at this point is good to know the opening gravity.",
							Type: "HowToStep",
						},
						{
							Text: "Add the pectic enzyme and mix thoroughly before adding the yeast to the surface of the must. You don’t need to mix the yeast in. Cover with the lid and airlock and fermentation should start after 48 hours or so.",
							Type: "HowToStep",
						},
						{
							Text: "Once fermentation has begun give the watermelon a stir once or twice a day for 5 days very gently with a sanitised spoon.",
							Type: "HowToStep",
						},
						{
							Text: "After 7 days of primary fermentation lift out the straining bag with the watermelon in and allow it to drain without squeezing. After drip draining, discard the fruit and recover the fermenting vessel and allow to settle for 2 – 3 days.",
							Type: "HowToStep",
						},
						{
							Text: "After 2 – 3 days rack the watermelon wine to a sanitised demijohn/carboy and seal with a bung and airlock. The wine will continue to ferment and condition in the demijohn for the next few weeks to a month. After this time you may notice the wine beginning to clear.",
							Type: "HowToStep",
						},
						{
							Text: "Rack the wine to a new demijohn after a considerable amount of sediment has built up and the wine is noticeably clearer. The wine can condition for at least 3 – 4 months or longer in the demijohn.",
							Type: "HowToStep",
						},
						{
							Text: "After conditioning for a few months take a sample of the wine and consider if you need to back sweeten the wine. This will help balance the alcohol with the watermelon flavour. A full guide to back sweetening can be found here.",
							Type: "HowToStep",
						},
						{
							Text: "At this point, the wine can be bottle and allow to mature as you see fit. I like to keep the bottles for a number of months and you will find the wine rounds out and the flavours settle. The wine will be good for a few years.",
							Type: "HowToStep",
						},
					},
				},
				Name:            "Watermelon Wine Recipe – Fresh, Fruity & Refreshing",
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools: &models.Tools{
					Values: []models.HowToItem{
						{Quantity: 1, Text: "Large Stock Pot", Type: "HowToTool"},
						{Quantity: 1, Text: "Small Fermenting Bucket", Type: "HowToTool"},
						{Quantity: 1, Text: "Demijohn", Type: "HowToTool"},
						{Quantity: 1, Text: "Syphon", Type: "HowToTool"},
						{Quantity: 1, Text: "Fine Straining Bag", Type: "HowToTool"},
						{Quantity: 1, Text: "Potato Masher", Type: "HowToTool"},
						{Quantity: 1, Text: "Airlock & Bung", Type: "HowToTool"},
					},
				},
				Yield: &models.Yield{Value: 1},
				URL:   "https://homebrewanswers.com/watermelon-wine-recipe/",
				Video: &models.Videos{},
			},
		},
		{
			name: "homechef.com",
			in:   "https://www.homechef.com/meals/farmhouse-fried-chicken",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				Keywords:      &models.Keywords{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Name:          "Farmhouse Fried Chicken",
				URL:           "https://www.homechef.com/meals/farmhouse-fried-chicken",
				Description: &models.Description{
					Value: "This stick-to-your-ribs satisfying country classic is an indulgence you've earned. The crispy comfort that only fried chicken can supply is accompanied by mashed potatoes and sweet corn. While that “other” chicken has you eating out of a bucket, this homey treat transports you to an idyllic country farmhouse on the prairie. Yee-Haw! Tip: Make potatoes easier to cut by making a large slice that leaves a flat surface. Place the flat surface on the cutting board and get to dicing!",
				},
				Yield: &models.Yield{Value: 2},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: `1 Make the Mashed Potatoes Cut potato into 1/2" pieces.Bring a small pot with potato pieces and enough water to cover to a boil. Reduce to a simmer and cook until fork-tender, 12-15 minutes.Drain potatoes in a colander and return to pot. Add half the butter, 1/4 the cream (reserve remaining of each for gravy), 1/2 tsp. olive oil, and a pinch of salt. Mash until desired consistency is reached. Cover and set aside.While potato cooks, prepare ingredients.`},
						{Type: "HowToStep", Text: "2 Prepare the Ingredients Trim and thinly slice green onions on an angle.Heat canola oil in a medium pan over medium heat, 5 minutes.While oil heats, pat chicken breasts dry, and season both sides with a pinch of pepper.Combine mayonnaise and 2 tsp. water in a mixing bowl. Place chicken breading in another mixing bowl.Dip one chicken breast in mayonnaise-water mixture, then coat completely in chicken breading, shaking off any excess. Repeat with second chicken breast."},
						{Type: "HowToStep", Text: "3 Fry the Chicken Line a plate with a paper towel. Test oil temperature by adding a pinch of chicken breading to it. It should sizzle gently. If it browns immediately, turn heat down and let oil cool. If it doesn't brown, increase heat.Lay chicken breasts away from you in hot oil and flip every 3-5 minutes until golden brown and chicken reaches a minimum internal temperature of 165 degrees, 10-14 minutes.Transfer chicken to towel-lined plate. Rest at least 5 minutes.While chicken rests, cook corn."},
						{Type: "HowToStep", Text: "4 Cook the Corn Place another small pot over medium heat. Add 1 tsp. olive oil and corn to hot pot. Stir occasionally until warmed through, 4-5 minutes.Transfer corn to a plate and season with a pinch of salt and pepper.Wipe pot clean and reserve."},
						{Type: "HowToStep", Text: `5 Make Gravy and Finish Dish Return pot used to cook corn to medium heat. Add green onions (reserve a pinch for garnish) and remaining cream and bring to a simmer. Once simmering, stir often until slightly thickened, 3-5 minutes.Remove from burner and swirl in remaining butter. Season with a pinch of pepper.If desired, slice chicken into 1/2" pieces.Plate dish as pictured on front of card, pouring gravy over chicken and garnishing potatoes with reserved green onions. Bon appétit!`},
					},
				},
				Ingredients: &models.Ingredients{
					Values: []string{
						"2 Russet Potatoes",
						"13 oz. Boneless Skinless Chicken Breasts",
						"6 fl. oz. Canola Oil",
						"4 oz. Light Cream",
						"½ cup Chicken Breading",
						"3 oz. Corn Kernels",
						"2 Green Onions",
						"0.84 oz. Mayonnaise",
						"⅗ oz. Butter",
					},
				},
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Video:           &models.Videos{},
			},
		},
		{
			name: "hostthetoast.com",
			in:   "https://hostthetoast.com/guinness-beef-stew-with-cheddar-herb-dumplings/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookTime:      "PT3H",
				DatePublished: "2014-03-18",
				Description:   &models.Description{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"¼ pound bacon",
						"2 pounds boneless beef chuck, chopped into bite-sized pieces",
						"Kosher salt and black pepper",
						"4 sticks celery, chopped",
						"3 large carrots, chopped",
						"1 large onion, chopped",
						"4 cloves garlic, minced",
						"2 large potatoes or parsnips, diced",
						"1 turnip, diced",
						"3 ounces tomato paste",
						"1 (12 ounce) bottle Guinness",
						"4 cups low sodium chicken broth",
						"2 tablespoons Worcestershire sauce",
						"1 bay leaf",
						"3 sprigs thyme",
						"1 tablespoon cornstarch, or as needed",
						"½ pound cremini mushrooms, sliced (optional)",
						"Chopped parsley",
						"1 ½ cups self-rising flour",
						"1/2 teaspoon garlic powder",
						"1/3 cup shortening",
						"3/4 cup shredded Irish sharp cheddar",
						"2/3 cup milk",
						"2 tablespoons mixed fresh herbs such as parsley, chives, and thyme, chopped",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Cook the bacon in a large, oven-safe, heavy-based pot or high-walled saute pan over medium heat."},
						{Type: "HowToStep", Text: "Remove the bacon, crumble, and set aside, but leave the bacon fat in the pot. Season the beef with salt and pepper and fry in the bacon fat until browned on all sides. Remove the beef from the pan and set aside."},
						{Type: "HowToStep", Text: "In the same pot, fry the onion, celery, and carrots until soft and fragrant, adding a little oil if necessary."},
						{Type: "HowToStep", Text: "Add garlic and fry for another 30 seconds. Stir in the tomato paste."},
						{Type: "HowToStep", Text: "Pour in the Guinness and Worcestershire sauce. Allow to come to a simmer and stir with a wooden spoon, scraping up the browned bits from the bottom of the pot."},
						{Type: "HowToStep", Text: "Add the beef back to the pot and pour in the chicken broth. Add the bay leaf and thyme."},
						{Type: "HowToStep", Text: "Reduce to a simmer and cover. Simmer for 1 1/2 hours. Add the potatoes or parsnips and the turnip. Simmer for another ½ hour, or until the vegetables are tender."},
						{Type: "HowToStep", Text: "Remove the bay leaf and thyme branches. If the stew is still thin, mix a tablespoon of cornstarch with a tablespoon of cold water to form a slurry. Mix the slurry into the stew and bring the mixture to a boil. Reduce to a simmer again, stirring occasionally, and add in the mushrooms if desired. Cook for 10 minutes, uncovered, until the stew thickens and the mushrooms are cooked through. Stir the bacon back in. Preheat the oven to 350°F."},
						{Type: "HowToStep", Text: "Stir together the self-rising flour and garlic powder in a medium bowl. Cut in the shortening until mixture resembles coarse crumbs. Stir in the cheddar cheese, then add the milk and stir until the dry ingredients are moistened."},
						{Type: "HowToStep", Text: "Make small balls with the dough and place them on top of the stew, leaving them room to expand-- they grow a lot as they cook. Place the stew in the oven uncovered and bake until the dumplings are browned and cooked through, about 30 to 40 minutes."},
						{Type: "HowToStep", Text: "Garnish the stew with parsley and serve."},
					},
				},
				Name:      "Guinness Beef Stew with Cheddar Herb Dumplings",
				PrepTime:  "PT30M",
				TotalTime: "PT3H30M",
				URL:       "https://hostthetoast.com/guinness-beef-stew-with-cheddar-herb-dumplings/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:       "VideoObject",
							ContentURL:   "https://content.jwplatform.com/videos/VctDiVIG.mp4",
							Description:  "Rich and hearty Guinness Beef Stew is a classic that you'll find at pubs and family dinner tables all across Ireland. This version features ultra-tender meat, deep flavors, and Cheddar Herb Dumplings that will make you swoon. It's the ultimate comfort food.",
							Name:         "Guinness Beef Stew with Cheddar Herb Dumplings",
							ThumbnailURL: &models.ThumbnailURL{Value: "https://content.jwplatform.com/thumbs/VctDiVIG-720.jpg"},
							UploadDate:   time.Date(2019, 2, 28, 21, 23, 13, 0, time.UTC),
						},
					},
				},
				Yield: &models.Yield{Value: 6},
			},
		},
	}
	for _, tc := range testcases {
		t.Run(tc.name, func(t *testing.T) {
			test(t, tc)
		})
	}
}
