package scraper_test

import (
	"github.com/reaper47/recipya/internal/models"
	"testing"
	"time"
)

func TestScraper_D(t *testing.T) {
	testcases := []testcase{
		{
			name: "daringgourmet.com",
			in:   "https://www.daringgourmet.com/homemade-giardiniera/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "condiment"},
				CookTime:      "PT10M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2024-03-25T18:28:31+00:00",
				Description: &models.Description{
					Value: "The ULTIMATE pickled vegetable relish, its flavor and versatility will astound you! Not just for hot dogs and muffuletta sandwiches, add this giardinera to your burgers, nachos, pizzas, pasta salads and anything else your heart desires!",
				},
				Keywords: &models.Keywords{Values: "Giardiniera"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1/2 head cauliflower, chopped into small florets",
						"10 ribs celery (, diced)",
						"5  carrots (, diced)",
						"2  large red bell peppers (, seeded and chopped)",
						"1 cup sliced green pitted olives",
						"4  serrano peppers (or more according to heat preference) (, sliced)",
						"Spices/Ingredients for EACH pint jar:",
						"1/2 teaspoon dried oregano",
						"1/2 teaspoon coriander seeds",
						"1/4 teaspoon yellow mustard seeds",
						"1/4 teaspoon fennel seeds",
						"1/4 teaspoon black peppercorns",
						"1/4 teaspoon red chili flakes (optional, for hot giardiniera)",
						"1/8 teaspoon celery seeds",
						"1 bay leaf",
						"1 clove garlic, cut in half",
						"1 tablespoon extra virgin olive oil",
						"For the Brine:",
						"4 cups white wine vinegar",
						"4 cups water",
						"2 tablespoons kosher salt",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Place the chopped veggies a large non-reactive pot or bowl. Pour 1/4 cup kosher salt over the vegetables and enough water to cover them. Let the vegetables soak in the salt water for at least 6 hours or overnight."},
						{Type: "HowToStep", Text: "To prepare the jars, place the spices into each of the jars, reserving the garlic and olive oil until after the brine is added. (I like to make some jars hot and some mild by adding/omitting the red chili flakes)."},
						{Type: "HowToStep", Text: "Thoroughly rinse and drain the vegetables before dividing them up between the jars. Pack the vegetables in as tightly as you can. Place a clove of garlic (cut in half) in each jar."},
						{Type: "HowToStep", Text: "To make the brine: Bring the water, vinegar and salt to a boil. Pour the boiling brine over the vegetables leaving a little more than 1/2 inch headspace from the top. Pour a tablespoon of olive oil over the top in each jar (omit the oil if water bath canning). Thoroughly wipe the rims with a wet paper towel, ensuring no oil or other residue is on them, and seal the jars."},
						{Type: "HowToStep", Text: "If you plan on using the giardiniera within two weeks let the jars sit at room temperature for a day or two and then transfer them to the fridge. The flavor only gets better with time so wait at least 2-3 days before eating it. Will keep refrigerated for 2 weeks."},
						{Type: "HowToStep", Text: "If you&#39;re canning the giardiniera for long-term storage, seal the jars with the lids and rims and prepare a boiling water bath. Boil the jars for 10 minutes. Carefully remove the jars and let them sit undisturbed for 24 hours before moving them.If processed in the water bath, the giardiniera is best consumed within 6 months but will keep for up to a year.Note: If you&#39;re canning the jars for long-term storage you can add the oil later to your giardiniera when you open the jar."},
					},
				},
				Name: "BEST Giardiniera (Hot or Mild)",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "19 kcal",
					Carbohydrates: "2 g",
					Fiber:         "1 g",
					SaturatedFat:  "5 g",
					Servings:      "85 g",
					Sodium:        "457 mg",
					Sugar:         "1 g",
				},
				PrepTime:  "PT30M",
				TotalTime: "PT40M",
				Yield:     &models.Yield{Value: 6},
				URL:       "https://www.daringgourmet.com/homemade-giardiniera/",
			},
		},
		{
			name: "davidlebovitz.com",
			in:   "https://www.davidlebovitz.com/marcella-hazans-bolognese-sauce-recipe-italian-beef-tomato/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main Course"},
				DatePublished: "2023-09-27T10:25:00+00:00",
				Description: &models.Description{
					Value: "There are a few Marcella Hazan Pasta Bolognese recipes out there. I tweaked a few of them to come up with this recipe, which is inspired and adapted by her. Note that this sauce will take a while to prepare. It&#39;s mostly downtime. At first, you&#39;re just sauteeing ingredients, stirring until they&#39;re combined, then adding wine and milk, simmering and stirring until those have been absorbed. Once the tomatoes have been added, that&#39;s when you let the sauce cook at the lowest heat possible, stirring every once in a while, until it&#39;s ready. Within an hour, it comes together into a nice paste, but if you cook it another hour, nursing it with water as you go, you&#39;ll get a sauce with a richer flavor. One of Hazan&#39;s recipes says to cook sauce Bolognese for up to 4 hours! In the untraditional category, some people like to grate from Parmesan cheese over finished bowls of pasta.",
				},
				Keywords: &models.Keywords{Values: "mushrooms"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"3 tablespoons butter (salted or unsalted, plus 1 tablespoon for finishing the pasta)",
						"3 tablespoons olive oil", "1/2 cup (60g) diced onions",
						"1/2 cup (65g) diced celery", "1/2 cup (65g) diced carrots ((peeled))",
						"12 ounces (340g) ground beef ((I recommend using one that's at least 15% fat))",
						"1 teaspoon salt (or more to taste)", "freshly-ground black pepper",
						"3/4 cup (180ml) whole milk", "1/8 teaspoon freshly ground nutmeg",
						"1 cup (250ml) dry white wine",
						"1 1/2 cups (350ml) canned plum tomatoes (crushed, with their juice)",
						"1 1/2 tablespoons tomato paste", "1 pound (450g) pasta",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Melt the butter with the olive oil in a soup pot over medium-high heat. Add the onions and cook, stirring frequently, until the onions are soft and translucent, about 3 minutes. Add the celery and carrots and cook, stirring a few times, until they start to wilt, 3 to 4 minutes."},
						{Type: "HowToStep", Text: "Add the ground beef, salt, and some freshly ground pepper. Lower the heat to medium and cook, stirring, until the beef is no longer raw on the outside. Pour in the milk, and cook at a steady simmer, stirring occasionally, until the milk is absorbed. Add a dusting of nutmeg and the wine, and continue to cook until the wine is mostly absorbed. (These steps can take a bit longer than you think, maybe 10 to 15 minutes of so, but this isn&#39;t a sauce to be rushed.)"},
						{Type: "HowToStep", Text: "Add the tomatoes in their juice and the tomato paste. Let come close to a boil then lower the heat to as low as possible until the sauce is just barely bubbling. Cook the sauce uncovered for 1 hour, stirring every once in a while, until most of the liquid is absorbed but the mixture is still wet, rich and thick. (There&#39;s a picture of it in the spoon, in the post.) You can use the sauce now, or if you want to give it some extra attention, you can cook it for another hour, adding up to 1/2 cup (125ml) of water, little by little as it continues to cook, and stirring occasionally, to make the sauce even more unctuous."},
						{Type: "HowToStep", Text: "Taste and add salt, if desired."},
						{Type: "HowToStep", Text: "To serve, cook the pasta in lightly salted water as directed on the package. (Before draining, reserve a little of the pasta cooking water.) Drain the pasta and toss the hot pasta in the Bolognese sauce with 1 tablespoon of butter. If the sauce needs a bit of thinning out, add a parsimonious splash of the reserved pasta water."},
					},
				},
				Name:  "Pasta Bolognese",
				Yield: &models.Yield{Value: 4},
				URL:   "https://www.davidlebovitz.com/marcella-hazans-bolognese-sauce-recipe-italian-beef-tomato/",
			},
		},
		{
			name: "delish.com",
			in:   "https://www.delish.com/cooking/recipe-ideas/a24489879/beef-and-broccoli-recipe/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "weeknight meals"},
				CookTime:      "PT0S",
				Cuisine:       &models.Cuisine{Value: "American"},
				DateModified:  "2023-06-26T17:34:00Z EST",
				DatePublished: "2018-11-06T17:45:06.218596Z EST",
				Description: &models.Description{
					Value: "A classic Chinese-American dish with thinly sliced, velveted flank steak in a rich brown sauce with tender-crisp broccoli.",
				},
				Keywords: &models.Keywords{
					Values: "American, Asian, dinner, weeknight meals, beef and broccoli recipe, sirloin recipes, Chinese take out recipes, easy weeknight dinner recipes, stir-fry recipe, beef stir-fry",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"2 tbsp. dry sherry or shaoxing wine",
						"2 tbsp. unseasoned rice vinegar",
						"1/2 tsp. kosher salt",
						"1/2 tsp. freshly ground black pepper",
						"1/3 c. plus 1/4 c. low-sodium soy sauce, divided",
						"2 tbsp. plus 1 1/2 tsp. cornstarch, divided",
						"2 tbsp. light brown sugar, divided",
						"1 1/2 lb. flank or skirt steak, sliced very thin against the grain",
						"4 cloves garlic",
						`1 (1/2") piece ginger, peeled`,
						"2 scallions",
						"2 small heads broccoli",
						"2/3 c. low-sodium beef broth",
						"2 tbsp. oyster sauce",
						"2 tsp. sriracha (optional)",
						"3 tbsp. vegetable oil, divided",
						"Toasted sesame seeds andwhite rice, for serving",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "In a medium bowl, combine sherry, vinegar, salt, pepper, 1/3 cup soy sauce, 1 tablespoon plus 1 1/2 teaspoons cornstarch, and 1 tablespoon brown sugar. Add steak and toss to coat. Let sit 20 minutes."},
						{Type: "HowToStep", Text: "Meanwhile, finely chop garlic and ginger. Slice scallions and separate green and white parts. In a small bowl, combine garlic, ginger, and white scallion parts; reserve green parts for serving. Chop broccoli into florets and transfer to another small bowl."},
						{Type: "HowToStep", Text: "In a large measuring cup, whisk broth, oyster sauce, sriracha (if using), and remaining 1/4 cup soy sauce, 1 tablespoon cornstarch, and 1 tablespoon brown sugar. When ready to cook, arrange bowls of beef, garlic mixture, broccoli, and stir-fry sauce next to stove."},
						{Type: "HowToStep", Text: "In a large skillet over medium-high heat, heat 1 tablespoon oil. Add half of beef and cook, undisturbed, 1 minute, then stir and cook until cooked through and starting to char in some spots, about 1 minute more. Transfer to a plate. Repeat with 1 tablespoon oil and remaining beef. Discard excess marinade."},
						{Type: "HowToStep", Text: "Return skillet to medium heat and heat remaining 1 tablespoon oil. Add garlic mixture and cook, stirring occasionally, until fragrant, about 2 minutes. Add broccoli and cook, stirring frequently, until slightly softened, about 1 minute, then add stir-fry sauce. Cover and cook 3 minutes. Uncover, return beef to skillet, and toss to coat. Cook, tossing frequently, until warmed through and broccoli is crisp-tender, 2 to 3 minutes more."},
						{Type: "HowToStep", Text: "Divide rice among plates. Top with stir-fry, sesame seeds, and reserved green scallion parts."},
					},
				},
				Name: "Beef & Broccoli",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "609 Calories",
					Carbohydrates: "26 g",
					Cholesterol:   "111 mg",
					Fat:           "35 g",
					Fiber:         "7 g",
					Protein:       "46 g",
					SaturatedFat:  "10 g",
					Sodium:        "1918 mg",
					Sugar:         "9 g",
					TransFat:      "1 g",
				},
				PrepTime: "PT10M",
				ThumbnailURL: &models.ThumbnailURL{
					Value: "https://hips.hearstapps.com/hmg-prod/images/delish-230510-beef-broccoli-613-rv-index-646bca228a2b3.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=100:*",
				},
				TotalTime: "PT40M",
				Yield:     &models.Yield{Value: 4},
				URL:       "https://www.delish.com/cooking/recipe-ideas/a24489879/beef-and-broccoli-recipe/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:      "VideoObject",
							ContentURL:  "https://streaming.hearstdigitalstudios.com/46aa890d-5fca-4635-8f72-7c65a59ef391/video_rover_16x9_1080p_hd_1687798821_89157.mp4",
							Description: "A classic Chinese-American dish with thinly sliced, velveted flank steak in a rich brown sauce with tender-crisp broccoli.",
							Duration:    "PT1M28S",
							EmbedURL:    "https://glimmer.hearstapps.com/amp.html?embedId=99d4ade0-430a-4b67-a3ac-6f3e1796edc1",
							Name:        "Our Best-Ever Beef & Broccoli Recipe Will Help You Perfect The Stir-Fry Classic",
							ThumbnailURL: &models.ThumbnailURL{
								Value: "https://hips.hearstapps.com/hmg-prod/images/delish-230510-beef-broccoli-613-rv-index-646bca228a2b3.jpg?crop=0.8890731909599834xw:1xh;center,top",
							},
							UploadDate: time.Date(2023, 6, 26, 17, 20, 7, 0, time.UTC),
						},
					},
				},
			},
		},
		{
			name: "ditchthecarbs.com",
			in:   "https://www.ditchthecarbs.com/how-to-make-keto-samosa-air-fryer-oven/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Appetiser"},
				CookTime:      "PT10M",
				Cuisine:       &models.Cuisine{Value: "Egg free"},
				DatePublished: "2022-03-17T09:35:35+00:00",
				Description: &models.Description{
					Value: "Keto samosas is an Indian vegetarian dish perfect for appitizers, snacks, or even a meal.",
				},
				Keywords: &models.Keywords{Values: "Keto Samosas"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 batch keto roti dough",
						"2 cups cauliflower (steamed and chopped)",
						"2 tbsp extra virgin olive oil ((ghee or coconut oil))",
						"½ tsp ground cumin",
						"½ tsp ground ginger",
						"1 tbsp garam masala",
						"2 cloves garlic (minced)",
						"2 tbsp jalapeno (chopped)",
						"2 stems green onions (chopped)",
						"1 tbsp lemon juice",
						"2 tbsp cilantro (chopped)",
						"+/- salt and pepper",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Start by maxing up a batch of keto roti dough. While the dough is resting you will want to make the filling."},
						{Type: "HowToStep", Text: "To make the filling heat the oil in a skillet. When the oil is hot add the seasoning(cumin, ginger, Garam masala), garlic, and jalapeno to the skillet. Saute in the skillet for about 1 minute then add the rest of the filling ingredients to the skillet. Let the filling cook for 3-4 minutes, stirring occassionally. Once the filling is done remove it from the heat and let it cool completely."},
						{Type: "HowToStep", Text: "While the filling is cooling prepare and shape the samosas wrappers. To do this cut your roti dough into 6 equal sections. Form each section into a ball. Roll each ball into a thin circle about the size of a side plate between two sheets of parchment paper using a rolling pin.Then using a knife cut each circle in half. This will give you 12 samosa wrappers. Cover and set aside until filling is completely cool."},
						{Type: "HowToStep", Text: "Start by laying out one samosa wrapper with the flat cut side toward the bottom. Use your finger to brush water in a line along half of the flat cut side. This will help the wrapper stick together as you fold it."},
						{Type: "HowToStep", Text: "Next, fold the two corner edges up to make a cone. Overlap the corners with the wet edge on top of the other. Firmly press the seam down to ensure it sticks and pinch the bottom of the cone closed."},
						{Type: "HowToStep", Text: "Hold the cone upright and open in your hand with the seam facing your palm. Your palm will help support the seam while you add the filling. Spoon the filling into the cone until it is 2/3 of the way full."},
						{Type: "HowToStep", Text: "Using your finger brush water around the inside edge of the cone. Then press the edges of the cone together and fold the bottom under to seal the cone and form a triangular samosa. Place the samosa down so that it is standing up with the sealed bottom facing down. Repeast until all 12 samosas are filled."},
						{Type: "HowToStep", Text: "Finally, brush the samosas with olive oil and cook one of 3 ways.1) Bake in the oven on a baking tray at 190°C/375°F for 15-18 minutes or until the samosas are golden brown.2) Arrange the samosas in your air fryer basket and air at 190°C/375°F for 7-8 minutes. Depending on the size of your air fryer you may need to cook the samosas in batches.3) Add an inch of olive oil to a skillet and fry the samosas over medium-high heat for 3-4 minutes on each side. Only cook 3-4 samosas at a time. Let the samosas cool for a few minutes after cooking and enjoy."},
					},
				},
				Name: "Easy Keto Samosas Recipe (Air Fryer Recipe)",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "69.6 kcal",
					Carbohydrates: "7.5 g",
					Fat:           "4.5 g",
					Fiber:         "3.8 g",
					Protein:       "1.2 g",
					SaturatedFat:  "",
					Servings:      "1",
					Sodium:        "30.7 mg",
					Sugar:         "0.9 g",
				},
				PrepTime: "PT30M",
				Yield:    &models.Yield{Value: 12},
				URL:      "https://www.ditchthecarbs.com/how-to-make-keto-samosa-air-fryer-oven/",
			},
		},
		{
			name: "domesticate-me.com",
			in:   "https://domesticate-me.com/10-summer-cocktail-recipes/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Drinks"},
				DatePublished: "2021-05-28T16:11:33+00:00",
				Description: &models.Description{
					Value: "Made with muddled strawberries, thyme, lemon, vodka, and St. Germain, this refreshing Strawberry Thyme Cooler is perfect for all your summer celebrations!",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1/3 cup hulled and diced strawberries",
						"1 sprig of fresh thyme",
						"½ ounce fresh lemon juice",
						"1 ounce St. Germain",
						"2 ounces vodka",
						"2-3 ounces club soda (depending on personal taste)",
						"Sliced strawberries",
						"Thyme sprig",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Muddle the strawberries, thyme sprig, and lemon juice in a cocktail shaker. Add the St. Germain, vodka, and some ice, and shake vigorously to combine."},
						{Type: "HowToStep", Text: "Strain the cocktail into a glass with ice and top with club soda."},
						{Type: "HowToStep", Text: "Garnish with sliced strawberries and a sprig of thyme. Bottoms up!"},
					},
				},
				Name:     "Strawberry Thyme Cooler and 9 Other Summer Cocktail Recipes",
				PrepTime: "PT5M",
				Yield:    &models.Yield{Value: 1},
				URL:      "https://domesticate-me.com/10-summer-cocktail-recipes/",
			},
		},
		{
			name: "downshiftology.com",
			in:   "https://downshiftology.com/recipes/baked-chicken-breasts/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main Course"},
				CookTime:      "PT20M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2023-10-31T08:00:00+00:00",
				Description: &models.Description{
					Value: "You&#039;ll love these perfectly baked chicken breasts that are juicy, tender, easy, and flavorful! All you need is a drizzle of olive oil, a special seasoning mix, and a few insider tips for these super tasty, no-fail chicken breasts. Watch the video below to see how I make them in my kitchen!",
				},
				Keywords: &models.Keywords{
					Values: "baked chicken, baked chicken breasts, baked chicken recipe",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"4 boneless skinless chicken breasts",
						"1 tablespoon olive oil (or avocado oil)",
						"1 teaspoon kosher salt",
						"1 teaspoon paprika",
						"½ teaspoon garlic powder",
						"½ teaspoon dried thyme (or oregano, parsley or other herbs)",
						"¼ teaspoon freshly ground black pepper",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat your oven to 425°F (220°C). In a small bowl, mix together the paprika, garlic powder, thyme, salt and pepper."},
						{Type: "HowToStep", Text: "Lightly coat the chicken breasts in olive oil, and then generously rub the spice mix on both sides of the chicken."},
						{Type: "HowToStep", Text: "Place the chicken breasts in a baking dish and cook for 20 to 25 minutes, depending on size (see chart above). Let the chicken rest for a few minutes to allow the juices to redistribute within the meat, then serve."},
					},
				},
				Name: "Best Baked Chicken Breast",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "163 kcal",
					Carbohydrates: "1 g",
					Cholesterol:   "72 mg",
					Fat:           "7 g",
					Fiber:         "1 g",
					Protein:       "24 g",
					SaturatedFat:  "1 g",
					Servings:      "1",
					Sodium:        "713 mg",
					Sugar:         "1 g",
				},
				PrepTime:  "PT5M",
				TotalTime: "PT25M",
				Yield:     &models.Yield{Value: 4},
				URL:       "https://downshiftology.com/recipes/baked-chicken-breasts/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:       "VideoObject",
							ContentURL:   "https://www.youtube.com/watch?v=1TlVgW-pM5g",
							Description:  "Perfectly baked chicken breasts that are juicy, tender, and loaded with flavor! If you’ve ever struggled with dry, rubbery, and just flat-out boring chicken breasts, you're in luck, because today’s recipe is about as easy as they come. Just whip up my special seasoning mix, give the chicken breasts a generous coating of it, and bake until juicy perfection.\n\nThis healthy, baked chicken recipe is perfect to serve for a weeknight dinner with a few side dishes, or slice it up and meal prep it for the week. It's naturally gluten-free, low-carb, and keto friendly, and one of the best dinner recipes! Make sure to check out the blog post below for extra tips and storage suggestions. \n\n🖨  Printable Baked Chicken Breast Recipe: https://downshiftology.com/recipes/baked-chicken-breast/\n\nSign up for weekly emails (never miss a recipe!): https://mailchi.mp/downshiftology/youtube/\n\nJoin the private Facebook group of fellow Downshifters around the world: https://www.facebook.com/groups/downshiftologycommunity/\n\n► PRODUCTS MENTIONED:\nBaking Pan: https://bit.ly/3hHxmAn\nInstant Read Thermometer: https://amzn.to/3owIuDw\nMeat Tenderizer: https://amzn.to/2MOMOAd\n\n► ALWAYS IN MY KITCHEN:\nCounter Stools: http://bit.ly/2tUNvZG\nVitamix Blender: https://amzn.to/2NjFp75\nSpiralizer: https://amzn.to/2N37WRy \nTea Kettle: http://amzn.to/2uuNSMp\nUtensil Holder: http://bit.ly/2tVfGaH\nFlour Jars: https://amzn.to/30UZESn\nSalt Cellar: https://amzn.to/2UUyK9r\nKnife Set: http://bit.ly/2tUGzMa\nCutting Board: https://amzn.to/2Vskgv9\nGlass Mixing Bowls: https://amzn.to/2L2hx6O\nMagnetic Measuring Spoons: https://amzn.to/2YIeKYT\nMagnetic Measuring Cups: https://amzn.to/3hAJu6A\n\nFor everything else I use in my videos, check out the SHOP page on my website: https://downshiftology.com/shop/\n\n► TIMESTAMPS:\n00:00 Intro\n00:31 Tips for juicy and tender baked chicken\n01:33 Make the seasoning mix\n02:00 Coat the chicken in oil and seasoning\n03:10 Bake the chicken breasts\n04:46 Serve the chicken breasts with side dishes\n05:09 Meal prep and save the chicken breasts for future meals\n05:23 Taste test\n\n► WHAT I'M WEARING\nTshirt: https://bit.ly/3h4Wm58\nJeans: http://bit.ly/32Fq7l5\nLinen Apron: http://bit.ly/2twA32E\n\nThe music I use: https://bit.ly/2Ms5nF2 - Great music for YouTubers!\n\nDisclaimer: product links may include affiliate links.\n#chicken #chickenrecipe #bakedchickenbreast",
							Duration:     "PT5M39S",
							EmbedURL:     "https://www.youtube.com/embed/1TlVgW-pM5g?feature=oembed",
							Name:         "BAKED CHICKEN BREAST | juicy, tender, easy, and oh, so flavorful!",
							ThumbnailURL: &models.ThumbnailURL{Value: "https://i.ytimg.com/vi/1TlVgW-pM5g/hqdefault.jpg"},
							UploadDate:   time.Date(2021, 1, 10, 16, 1, 13, 0, time.UTC),
						},
					},
				},
			},
		},
		{
			name: "dr.dk",
			in:   "https://www.dr.dk/mad/opskrift/nytarskage-med-champagne-kransekagebund-solbaer-og-chokoladepynt",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				Name:          "Nytårskage med champagne, kransekagebund, solbær og chokoladepynt",
				DatePublished: "2022-01-01T21:00:00+00:00",
				Image:         &models.Image{Value: anUploadedImage.String()},
				Description: &models.Description{
					Value: "Smuk nytårskage med urvisere og masser af smag, der passer perfekt til nytårsaften.",
				},
				URL: "https://www.dr.dk/mad/opskrift/nytarskage-med-champagne-kransekagebund-solbaer-og-chokoladepynt",
				Ingredients: &models.Ingredients{
					Values: []string{
						"30 g æggehvider",
						"50 g sukker",
						"Fintrevet citronskal",
						"200 g bagemarcipan",
						"15 g sukker",
						"15 g ristede, hakkede smuttede mandler",
						"1 nip salt",
						"50 g mørk chokolade",
						"1 spsk. frysetørret solbærpulver",
						"1 tsk. pufsukker",
						"140 g hvid chokolade",
						"1/2 blad husblas",
						"2 æggeblommer",
						"15 g sukker",
						"80 ml piskefløde",
						"80 g solbærpuré",
						"2 tsk. citronsaft",
						"1/2 tsk. citronsyre",
						"75 g sukker",
						"40 g glukosesirup",
						"30 ml tør champagne",
						"1/2 tsk. citronsyre",
						"50 g æggehvider",
						"1 spsk. sukker",
						"2 tsk. solbærpulver",
						"2 blade husblas",
						"400 g gold chokolade",
						"160 ml tør champagne",
						"40 ml citronsaft",
						"4 dl piskefløde",
						"1 tsk. solbærpulver",
						"5 blade husblas",
						"150 g hvid chokolade",
						"100 g kondenseret mælk",
						"51 g solbærpuré",
						"54 g vand",
						"150 g sukker",
						"100 g glukosesirup",
						"Minimum 800 g mørk chokolade",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Kransekagebund"},
						{Type: "HowToStep", Text: "Varm marcipan kort i mikroovn, rør alle ingredienser sammen i røremaskinen indtil den samler sig."},
						{Type: "HowToStep", Text: "Fordel dejen i en kagering på ca. 16ø og bag den I ca. 15 minutter ved 200C, til den er let gylden. Lad den køle ned."},
						{Type: "HowToStep", Text: "\n"},
						{Type: "HowToStep", Text: "Mandel-solbær-knas"},
						{Type: "HowToStep", Text: "Smelt sukkeret ved lav blus i en gryde, indtil den er let gylden. Tag gryden af varme og rør mandler og salt i."},
						{Type: "HowToStep", Text: "Hæld karamelliseret mandler i et stk bagepapir og lad den køle helt ned. Hak mandlerne fint. Smelt chokoladen op til 45C, tilsæt solbærpulver, pufsukker og de hakket mandler i."},
						{Type: "HowToStep", Text: "Fordel knaset oven på kransekagebunden til et jævnt fint lag. Stil kagen i fryseren mens du arbejder videre."},
						{Type: "HowToStep", Text: "\n"},
						{Type: "HowToStep", Text: "Solbærcremeux"},
						{Type: "HowToStep", Text: "Kom chokoladen i en skål og sæt den til side. Sæt husblas i koldt vand i ca. 5 minutter."},
						{Type: "HowToStep", Text: "Pisk æggeblommer og sukker let sammen i en anden skål."},
						{Type: "HowToStep", Text: "Varm fløde, citronsyre og solbærpuré op til kogepunktet og hæld den i æggeblandingen under piskning. Hæld blandingen tilbage i gryden og kog cremen op til 85C under konstant omrøring med en silikoneske."},
						{Type: "HowToStep", Text: "Tag gryden af varmen og sigt cremen."},
						{Type: "HowToStep", Text: "Vrid husblas fri fra vand og smelt den i cremen. Hæld cremen over chokoladen og rør midt i skålen indtil chokoladen og cremen er blevet homogen."},
						{Type: "HowToStep", Text: "Smag til med citronsaft og stablen cremeuxen. Fordel den ovenpå kransekagebund (chokolade knas skal være ned i bunden) i bageringen og sæt den i fryseren."},
						{Type: "HowToStep", Text: "\n"},
						{Type: "HowToStep", Text: "Champagne-flødebolleskum"},
						{Type: "HowToStep", Text: "Bring 75g sukker, glukosesirup, champagne og citronsyre i kog op til 118C."},
						{Type: "HowToStep", Text: "Pisk æggehvider og 1 spsk sukker næsten stive i en skål og hæld den varme sukkerlage ned i æggehviderne i en tynd stråle under piskning. Pisk videre, til skummet er sejt og fast. Ved slutning tilsæt solbærpulver og pisk færdig."},
						{Type: "HowToStep", Text: "Fordel skummet over solbærcremeux, gør overfladen glat med en paletkniv og stil kagen i fryseren igen."},
						{Type: "HowToStep", Text: "\n"},
						{Type: "HowToStep", Text: "Champagnemousse"},
						{Type: "HowToStep", Text: "1/2 tsk citronsyre Udblød husblassen i koldt vand. Smelt chokoladen op til 45C."},
						{Type: "HowToStep", Text: "Bring champagne, citronsyre og citronsaft til kogepunktet og tag gryden straks af varmen."},
						{Type: "HowToStep", Text: "Vrid husblas fri for vand og rør den i den varme champagne. Hæld champagnen over chokoladen, mens du rør i midten af skålen. Fortsæt indtil massen samler sig."},
						{Type: "HowToStep", Text: "Pisk fløde til let skum, ved skummet over chokoladen ad 3 omgange."},
						{Type: "HowToStep", Text: "Fordel champagnemousse i en silikoneforme og tryk solbærindlæg ned i moussen - bunden skal være oppe. Lad kagen fryse indtil den skal glazes."},
						{Type: "HowToStep", Text: "\n"},
						{Type: "HowToStep", Text: "Solbærglaze"},
						{Type: "HowToStep", Text: "Læg husblad i koldt vandbad i ca. 5 minutter. Kom chokolade i en høj kande."},
						{Type: "HowToStep", Text: "Bring solbærpuré, vand, sukker og glukosesirup i en gryde og koge den op til kogepunktet. Tag gryden af varmen og rør kondenseret mælk i."},
						{Type: "HowToStep", Text: "Vrid husblassen fri for vand og rør den ud i den varme væske. Hæld væsken over chokoladen og lad den træk i et par minutter."},
						{Type: "HowToStep", Text: "Stavblend glaze indtil det er samlet og ensartet. Tilsæt guldstøv og stavblend igen."},
						{Type: "HowToStep", Text: "Dæk overflade med film og lad gazen køle ned til 32 grader."},
						{Type: "HowToStep", Text: "Placér den frosne kage på en rist og glaze kagen."},
						{Type: "HowToStep", Text: "\n"},
						{Type: "HowToStep", Text: "Forberedelse af chokoladepynt"},
						{Type: "HowToStep", Text: "Klip et langt stykke plast på 63 cm til som et bylandskab og et andet stykke plast på 30 cm"},
						{Type: "HowToStep", Text: "Klip to viser af stift kageplast"},
						{Type: "HowToStep", Text: "Forberedelse af en halvkugle Ø10 cm pudses med vat"},
						{Type: "HowToStep", Text: "Temperere guld kakaofarve sammen med guldstøv og dup med en svamp et fyrværkeri mønster i halvkuglen, så det ligner en guldregn"},
						{Type: "HowToStep", Text: "Temperere 800 g mørk chokolade"},
						{Type: "HowToStep", Text: "Fyld hele halvkuglen op med chokolade og lade det sidde i 1-2 min for at sørge for, at skallen bliver tyk"},
						{Type: "HowToStep", Text: "Bank alt det overskydende chokolade ud på et stykke bagepapir og sæt den til at størkne"},
						{Type: "HowToStep", Text: "Fordel et jævnt lag chokolade ud på plasten der forestiller et bylandskab og på 30 cm plast"},
						{Type: "HowToStep", Text: "Beklæd en 20 cm kagering med plast og sæt bylandskabet rundt herom, som et stort bånd"},
						{Type: "HowToStep", Text: "Udstik med en Ø3 cm ring små knapper af den næsten størknet chokolade på 30 cm plast og befri dem, når chokoladen er kølet helt af"},
						{Type: "HowToStep", Text: "De runde cirkler pensles med guldstøv og efterfølgende skrives der med romertal fra 1-12"},
						{Type: "HowToStep", Text: "Befri halvkuglen fra formen og sæt til side"},
						{Type: "HowToStep", Text: "Lav visere af chokolade"},
						{Type: "HowToStep", Text: "\n"},
						{Type: "HowToStep", Text: "Samling"},
						{Type: "HowToStep", Text: "Den frosne kage befries fra formen og sættes på en drejeskive"},
						{Type: "HowToStep", Text: "Kagen betrækkes med et lag smørcreme, som glattes tyndt ud"},
						{Type: "HowToStep", Text: "Kagen sættes tilbage på frost i 10 min"},
						{Type: "HowToStep", Text: "Betræk med et nyt lag, som glattes helt jævnt ud"},
						{Type: "HowToStep", Text: "Sæt kagen tilbage på frost 10-15 min"},
						{Type: "HowToStep", Text: "Spray kagen med cremet velvet spray farve"},
						{Type: "HowToStep", Text: "Betræk kagen med chokoladebånd"},
						{Type: "HowToStep", Text: "Pynt toppen med guldtal oven på små chokoladekugler og placere halvkuglen i midten af kagen"},
					},
				},
				Keywords:        &models.Keywords{},
				NutritionSchema: &models.NutritionSchema{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{},
			},
		},
		{
			name: "dreenaburton.com",
			in:   "https://dreenaburton.com/2-ingredient-watermelon-gelato/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Dessert"},
				DatePublished: "2022-07-08T19:35:00+00:00",
				Description: &models.Description{
					Value: "Watermelon gets even better when frozen and churned into this refreshing, sugar-free, dairy-free gelato. It's magical!&nbsp;",
				},
				Keywords: &models.Keywords{Values: "banana, gelato, ice cream, watermelon"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"5 cups frozen cubed watermelon (see note)",
						"1 cup sliced overripe banana (frozen or room temp) (see note)",
						"1/2 - 1 tbsp coconut nectar or cassava syrup OPTIONAL (see note)",
						"1-2 tbsp raw cashew butter, OPTIONAL (see note)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Add watermelon and banana to a food processor (if you prefer to use a blender, it must be high-speed for this recipe). Pulse to first mince the frozen fruit, and then once in slivers or small pieces, switch to puree."},
						{Type: "HowToStep", Text: "Puree until smooth, stopping to scrape down food processor once or twice. Taste, and if you’d like it a little sweeter, add the sweetener to taste. Serve, or transfer to the freezer for an hour or more for a firmer set gelato."},
					},
				},
				Name:  "Vegan Watermelon Gelato (Only 2 Ingredients!)",
				Yield: &models.Yield{Value: 1},
				URL:   "https://dreenaburton.com/2-ingredient-watermelon-gelato/",
			},
		},
		{
			name: "drinkoteket.se",
			in:   "https://drinkoteket.se/recept/limoncello-spritz/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Champagnedrinkar"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				CookTime:      "PT2M",
				DatePublished: "2023-12-30",
				Description: &models.Description{
					Value: "Limoncello Spritz Drinkrecept på Drinkoteket.se. Här hittar du en mängd recept på enkla och goda drinkar och cocktails online. Välkommen in!",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"5 cl Limoncello", "10 cl Bubbel", "4 cl Sodavatten", "1 cl Citronjuice",
						"Rekommenderat bubbel", "Prosecco",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Fyll ett glas med is."},
						{Type: "HowToStep", Text: "Tillsätt ett torrt mousserande vin, förslagsvis prosecco."},
						{Type: "HowToStep", Text: "Tillsätt limoncello och en skvätt citronjuice."},
						{Type: "HowToStep", Text: "Rör om lite lätt."},
						{Type: "HowToStep", Text: "Garnera med en citronskiva."},
					},
				},
				Name:            "Limoncello Spritz",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT1M",
				Tools: &models.Tools{
					Values: []models.HowToItem{
						{Quantity: 1, Text: "Barset med shaker", Type: "HowToTool"},
						{Quantity: 1, Text: "Shaker", Type: "HowToTool"},
						{Quantity: 1, Text: "Jigger", Type: "HowToTool"},
						{Quantity: 1, Text: "Citruspress", Type: "HowToTool"},
						{Quantity: 1, Text: "Cocktailsil", Type: "HowToTool"},
						{Quantity: 1, Text: "Barsked", Type: "HowToTool"},
					},
				},
				Yield: &models.Yield{Value: 1},
				URL:   "https://drinkoteket.se/recept/limoncello-spritz/",
			},
		},
	}
	for _, tc := range testcases {
		t.Run(tc.name, func(t *testing.T) {
			test(t, tc)
		})
	}
}
