package scraper_test

import (
	"github.com/reaper47/recipya/internal/models"
	"testing"
	"time"
)

func TestScraper_P(t *testing.T) {
	testcases := []testcase{
		{
			name: "paleorunningmomma.com",
			in:   "https://www.paleorunningmomma.com/grain-free-peanut-butter-granola-bars-vegan-paleo-option/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Breakfast"},
				Cuisine:       &models.Cuisine{Value: "Gluten-free"},
				DatePublished: "2021-03-26T18:11:21+00:00",
				Description: &models.Description{
					Value: "These no bake, chewy peanut butter granola bars are a breeze to make and so addicting!  They’re gluten free and grain free, with both vegan and paleo options.  Perfect for quick snacks, these homemade granola bars are perfect right out of the fridge or freezer.",
				},
				Keywords: &models.Keywords{
					Values: "bars, egg-free, no-bake, nut butter, paleo, peanut butter, vegan",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 1/2 cups pecan halves ( or walnuts)",
						"1 1/2 cups almonds",
						"1 cup unsweetened coconut flakes",
						"1/2 tsp salt",
						"2 tablespoons organic coconut oil (melted (use refined for neutral flavor))",
						"2/3 cup peanut butter or other nut butter like almond (cashew, walnut, or sunflower butter (for paleo))",
						"1/4 cup + 2 Tbsp pure maple syrup (or raw honey (for paleo))",
						"1 tsp pure vanilla extract",
						"2/3 cup mini chocolate chips (dairy free )",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Place the nuts in a food processor and pulse several times to “chop” them into a crumbly texture - a few larger pieces are a good thing - don’t overmix!"},
						{Type: "HowToStep", Text: "Transfer the nuts to a large mixing bowl and stir in coconut flakes and salt to evenly combine."},
						{Type: "HowToStep", Text: "Place the melted coconut oil in a medium bowl and whisk in the peanut butter and honey or maple syrup. Once mixture is smooth and well combined, stir in the vanilla."},
						{Type: "HowToStep", Text: "Pour the wet mixture into the large bowl with the dry ingredients and stir to fully combine - I used a silicone spatula for this step. Thoroughly mix to make sure all the dry mixture is coated. Once coated, gently stir in the chocolate chips."},
						{Type: "HowToStep", Text: "Line an 8 x 8” or 9 x 9” square pan with parchment paper along the bottom and sides, with extra up the sides for easy removal. Transfer mixture in and press down, using your hands, or another piece of parchment paper to get it packed tightly into the pan."},
						{Type: "HowToStep", Text: "Cover the top with parchment or plastic wrap, then set in the freezer for at least 1 hour to firm, or longer if you have time."},
						{Type: "HowToStep", Text: "Remove pan from freezer and grab two ends of the parchment paper to remove the bars, set on a cutting board."},
						{Type: "HowToStep", Text: "Using a long very sharp knife, cut into 15-20 bars. You can wrap them in parchment individually storing in the fridge (for up to two weeks) or freezer for longer."},
						{Type: "HowToStep", Text: "Bars will start to melt around room temp due to the coconut oil, so they’ll need to be kept chilled to stay firm. Enjoy!"},
					},
				},
				Name: "Grain Free Peanut Butter Granola Bars {Vegan, Paleo Option}",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "249 kcal",
					Carbohydrates: "12 g",
					Cholesterol:   "1 mg",
					Fat:           "21 g",
					Fiber:         "3 g",
					Protein:       "6 g",
					SaturatedFat:  "7 g",
					Servings:      "1",
					Sodium:        "106 mg",
					Sugar:         "7 g",
					TransFat:      "1 g",
				},
				PrepTime: "PT15M",
				Yield:    &models.Yield{Value: 20},
				URL:      "https://www.paleorunningmomma.com/grain-free-peanut-butter-granola-bars-vegan-paleo-option/",
			},
		},
		{
			name: "panelinha.com.br",
			in:   "https://www.panelinha.com.br/receita/Frango-ao-curry",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Aves"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{Value: "Prática"},
				DatePublished: "2000-05-13",
				Description: &models.Description{
					Value: "A lista de vantagens desta receita é longa: fácil, rápida, tem poucos ingredientes e muito sabor. E tem mais: você pode preparar bem antes da hora de servir. Graças ao caldinho delicioso de creme de leite, maçãs e especiarias, o frango segue macio, macio mesmo depois de requentado. Agora, o inegociável: investir em um curry de qualidade, já que é ele que dá todo o sabor ao preparo.",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"2 filés de peito de frango (cerca de 500g)",
						"2 maçãs fuji",
						"1 cebola",
						"2 dentes de alho",
						"2 colheres (sopa) de curry",
						"1 xícara (chá) de creme de leite fresco",
						"2 colheres (sopa) de azeite",
						"sal e pimenta-do-reino moída na hora a gosto",
						"folhas de coentro a gosto para servir",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Corte os filés de frango em cubos de 3 cm e transfira para uma tigela. Tempere com 1 colher (chá) de sal, o curry e pimenta a gosto e mantenha em temperatura ambiente enquanto prepara os outros ingredientes — assim ele absorve melhor o sabor do curry e perde o gelo antes de ir para a panela."},
						{Type: "HowToStep", Text: "Descasque e pique fino a cebola e os dentes de alho. Descasque e corte as maçãs em fatias de 1,5 cm; descarte o miolo com as sementes, corte as fatias em tiras e as tiras em cubos."},
						{Type: "HowToStep", Text: "Leve uma panela média ao fogo médio. Quando aquecer, regue com o azeite, adicione a cebola e tempere com uma pitada de sal. Refogue por cerca de 3 minutos, até murchar. Junte o alho e mexa bem por 1 minuto para perfumar."},
						{Type: "HowToStep", Text: "Acrescente os cubos de frango e refogue por cerca de 1 minuto, até perderem a aparência crua — evite refogar em excesso para que o frango não resseque; ele vai terminar de cozinhar com o restante dos ingredientes."},
						{Type: "HowToStep", Text: "Junte os cubos de maçã, regue com o creme de leite e misture bem. Assim que começar a ferver, abaixe o fogo e deixe cozinhar por cerca de 10 minutos, até que o frango e a maçã estejam cozidos e o molho levemente encorpado. Sirva a seguir com folhas de coentro a gosto."},
					},
				},
				Name:            "Frango ao curry com maçã",
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 4},
				URL:             "https://www.panelinha.com.br/receita/Frango-ao-curry",
				Video:           &models.Videos{},
			},
		},
		{
			name: "paninihappy.com",
			in:   "https://paninihappy.com/why-you-need-this-pumpkin-muffin-recipe/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				Name:          "My Favorite Pumpkin Muffins",
				PrepTime:      "PT10M",
				CookTime:      "PT20M",
				Description: &models.Description{
					Value: "Because I’ve made them many times over the years and they’re the best pumpkin muffins I’ve tasted — fluffy, flavorful, unfussy, nice doming.\n\nBecause even though baking with pumpkin can be kind of a seasonal fad, it’s a delicious one, so pumpkin on!\n\nBecause now that it’s October you’re undoubtedly going to need to bring a crowd-pleasing, autumn-appropriate dish to school/work/church/soccer, etc. Or you’re simply going to want one at home on a brisk autumn afternoon.\n\nBecause you can easily double the recipe for a big group — in fact, the orignal recipe from Erin Cooks (one of my earliest favorite food blogs) makes a whole lot of muffins — or make them in mini muffin pans or mini loaf pans for lunch boxes or cute gifts.\n\nBecause pumpkin + cake mix does not equal a recipe (yeah, I said it — sorry, Pinterest!).\n\nBecause you probably have all the ingredients on hand already (especially in October, because pumpkin time).\n\nBecause they can pass for breakfast, dessert or even a side dish — versatility awaits!\n\nBecause friends love to receive the occasional pumpkin muffin surprise on their doorstep.\n\nBecause baking these muffins doubles as an awesome home fragrance for your kitchen.\n\nBecause…oh, just turn on the oven and make ’em!",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Yield:    &models.Yield{Value: 12},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 1/2 cups flour",
						"1 teaspoon baking soda",
						"1 teaspoon baking powder",
						"1 teaspoon cinnamon",
						"1/2 teaspoon salt",
						"1/4 teaspoon ground ginger",
						"1/4 teaspoon ground nutmeg",
						"2 eggs",
						"3/4 cup sugar",
						"1 cup pumpkin purée",
						"3/4 cup vegetable oil",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Heat the oven to 400ºF."},
						{Type: "HowToStep", Text: "Combine all of the dry ingredients in a medium bowl. Beat the eggs, sugar, pumpkin, and oil until smooth. Pour the pumpkin mixture into the dry ingredients and mix just until blended."},
						{Type: "HowToStep", Text: "Grease a muffin tin or fill your tin with cupcake papers. Fill the wells with the batter until they are 2/3 of the way full. Bake for 16-20 minutes. Cool 5 minutes and then complete the cooling process on a wire rack."},
					},
				},
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				URL:             "https://paninihappy.com/why-you-need-this-pumpkin-muffin-recipe/",
				Video:           &models.Videos{},
			},
		},
		{
			name: "parsleyandparm.com",
			in:   "https://parsleyandparm.com/zaatar-sheet-pan-vegetables-and-eggs/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Breakfast"},
				CookTime:      "PT45M",
				CookingMethod: nil,
				Cuisine:       &models.Cuisine{Value: "Middle Eastern"},
				DateCreated:   "",
				DateModified:  "",
				DatePublished: "2022-04-21T14:16:28+00:00",
				Description: &models.Description{
					Value: "Mixed vegetables roasted with herby, zesty za&#39;atar seasoning and perfectly-cooked eggs, all in one sheet pan!",
				},
				Keywords: &models.Keywords{Values: "eggs, za'atar"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"5 medium yellow potatoes (cut into 1½ inch pieces)",
						"3 large bell peppers - red (yellow, or orange)",
						"½ large red onion (sliced into ½ inch wedges)",
						"3 tablespoons extra virgin olive oil (divided)",
						"¾ teaspoon fine sea salt (divided)",
						"3 teaspoons za’atar (see notes, divided)", "Cooking spray of your choice",
						"6 eggs (not extra large)",
						"¼ cup cilantro leaves (stems removed and roughly chopped)",
						"¼ cup feta cheese (crumbled)",
						"1 large avocado (peeled and sliced (optional))",
						"Harissa (optional)",
						"1 cup hummus (such as my white bean hummus)",
						"Whole wheat pita bread (1/2-1 per person)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Text: "Place a clean, dry sheet pan in the oven and preheat to 400 degrees.", Type: "HowToStep"},
						{Text: "Toss the potatoes in a bowl with 2 tablespoons of olive oil, ½ teaspoon of salt, and 2 teaspoons of za’atar. Set aside while your oven preheats.", Type: "HowToStep"},
						{Text: "Once the oven is preheated, take the pan out of the oven and shut the oven door to preserve the heat. Spray the hot pan well with cooking spray, then dump the potatoes onto the hot pan. Use a spatula to spread them out in a single layer. Return the pan to the oven and roast for 20 minutes.", Type: "HowToStep"},
						{Text: "Cut two ½-inch thick rings out of the thickest part of each bell pepper. Use a small knife to remove any pith and seeds without breaking the rings. Set aside.", Type: "HowToStep"},
						{Text: "Remove the stems, seeds, and pith from the remaining bell pepper pieces and cut them into 1½ inch chunks.", Type: "HowToStep"},
						{Text: "Toss the bell peppers and onions in the bowl that you tossed the potatoes with. Add the remaining olive oil, salt, and za’atar and toss.", Type: "HowToStep"},
						{Text: "After the potatoes have been in the oven for 20 minutes, take the pan out of the oven and close the oven door to preserve the heat. Dump the peppers and onions onto the hot pan, and use a spatula to stir them together well. Add the bell pepper rings to the bowl and gently toss to coat them with some of the residual oil and seasoning.", Type: "HowToStep"},
						{Text: "Push the veggies aside a bit to create six “wells” to fit the pepper rings. Your pan will be pretty full! I usually use a spatula to rearrange the veggies a bit, they will pile up a little. Add the pepper rings to the wells, then return the pan to the oven for 20 minutes.", Type: "HowToStep"},
						{Text: "Remove the pan from the oven, and use tongs to turn over each of the pepper rings. Spray the pan in the middle of each of the rings with cooking spray, then carefully break an egg into each ring.", Type: "HowToStep"},
						{Text: "Return the pan to the oven (careful, the eggs are runny!) and bake for 5-7 minutes, depending how well done you like your eggs. 6 minutes is usually perfect for our family. You want the tops of the eggs to be just past the point where they still look liquid.", Type: "HowToStep"},
						{Text: "Top the veggies and eggs with the feta, cilantro, harissa, and avocado (you can also serve the harissa on the side if you don’t like things spicy). Serve with warm pita bread and hummus.", Type: "HowToStep"},
					},
				},
				Name: "Za'atar Sheet Pan Vegetables and Eggs",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "417 kcal",
					Carbohydrates:  "44 g",
					Cholesterol:    "169 mg",
					Fat:            "22 g",
					Fiber:          "10 g",
					Protein:        "15 g",
					SaturatedFat:   "5 g",
					Servings:       "1",
					Sodium:         "633 mg",
					Sugar:          "5 g",
					TransFat:       "1 g",
					UnsaturatedFat: "16 g",
				},
				PrepTime:     "PT10M",
				ThumbnailURL: nil,
				Tools:        nil,
				TotalTime:    "PT55M",
				Yield:        &models.Yield{Value: 6},
				URL:          "https://parsleyandparm.com/zaatar-sheet-pan-vegetables-and-eggs/",
			},
		},
		{
			name: "persnicketyplates.com",
			in:   "https://www.persnicketyplates.com/easy-slow-cooker-french-toast-casserole/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Breakfast"},
				CookTime:      "PT240M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2023-11-13T23:57:32+00:00",
				Description: &models.Description{
					Value: "Slow Cooker French Toast Casserole has only a few ingredients, preps overnight, and is perfect for Christmas morning, brunch, or just a weekend breakfast. Full of cinnamon flavor, this easy crockpot casserole is perfect finished off with a dusting of powdered sugar and some fresh fruit.",
				},
				Keywords: &models.Keywords{
					Values: "crockpot french toast casserole, overnight slow cooker french toast casserole, slow cooker french toast casserole",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 loaf Italian bread (cut into 1&quot; pieces. (This should be 6-7 cups of bread))",
						"6 large eggs", "2 cups milk (I use 2%)", "2 teaspoons cinnamon (divided)",
						"¼ cup salted butter (at room temperature)", "⅓ cup brown sugar",
						"½ teaspoon vanilla extract", "powdered sugar (for topping)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: `Cube the bread into approximately 1" pieces and spread onto a lipped baking sheet. Bake in a 170°F preheated oven for 30-60 minutes, or until dry. Alternatively, you can cube the bread and let it sit out overnight to stale.`},
						{Type: "HowToStep", Text: "In a large mixing bowl, whisk together the eggs, milk, vanilla, and 1 teaspoon of the cinnamon."},
						{Type: "HowToStep", Text: "Add the stale cubed bread to the egg mixture and stir so all pieces of the bread are fully coated. Cover the bowl with plastic wrap and move it to the fridge for 4-8 hours."},
						{Type: "HowToStep", Text: "In a small mixing bowl, use a pastry cutter or a fork to cut together the butter, brown sugar, and remaining cinnamon. Cover and put in the fridge as well."},
						{Type: "HowToStep", Text: "When ready, spray a 6 quart slow cooker with non-stick spray and pour in the soaked bread pieces."},
						{Type: "HowToStep", Text: "Crumble the butter mixture evenly over the top."},
						{Type: "HowToStep", Text: "Cover and cook on HIGH for 2 hours or LOW for 4 hours, or until the center is set."},
						{Type: "HowToStep", Text: "Turn the slow cooker to WARM and remove the lid. Let stand for 15 minutes to set before serving."},
						{Type: "HowToStep", Text: "Top with powdered sugar, syrup, and berries."},
					},
				},
				Name: "Slow Cooker French Toast Casserole",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "494 kcal",
					Carbohydrates:  "42 g",
					Cholesterol:    "162 mg",
					Fat:            "31 g",
					Fiber:          "2 g",
					Protein:        "11 g",
					SaturatedFat:   "17 g",
					Servings:       "1 g",
					Sodium:         "335 mg",
					Sugar:          "30 g",
					TransFat:       "0.4 g",
					UnsaturatedFat: "13 g",
				},
				PrepTime:  "PT15M",
				TotalTime: "PT495M",
				Yield:     &models.Yield{Value: 8},
				URL:       "https://www.persnicketyplates.com/easy-slow-cooker-french-toast-casserole/",
			},
		},
		{
			name: "pickuplimes.com",
			in:   "https://www.pickuplimes.com/recipe/the-best-vegan-chow-mein-800",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main"},
				CookingMethod: &models.CookingMethod{},
				CookTime:      "PT15M",
				Cuisine:       &models.Cuisine{Value: "Asian-inspired"},
				Description: &models.Description{
					Value: "To effortlessly serve up this dish that outshines takeout, the secret is having all your vegetables chopped and prepped. Once you begin cooking, this recipe comes together swiftly, and with everything ready, the entire meal flows seamlessly.",
				},
				Keywords: &models.Keywords{Values: "peanut free, tree nut free, vegan, vegetarian, plant-based"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"3 Tbsp dark soy sauce", "2 Tbsp water", "2 Tbsp toasted sesame oil",
						"&#189; vegetable bouillon cube", "cornstarch", "agave syrup",
						"sriracha hot sauce", "rice vinegar", "&#189; Tbsp vegetable oil",
						"1 cup mock chicken pieces", "1 Tbsp vegetable oil", "1 medium onion",
						"2 clove garlic", "5.291 oz vegan chow mein noodles", "&#188; napa cabbage",
						"2 carrot", "1 head of bok choy",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Text: "Combine sauce ingredients in a jar or small bowl.", Type: "HowToStep"},
						{
							Text: "Add the oil to sauté pan on high heat. Cook the mock chicken pieces until golden. Transfer to a plate and set aside.",
							Type: "HowToStep",
						},
						{
							Text: "Add the some more oil to the now-empty pan. Cook the onion and garlic in the pan until the garlic becomes golden.",
							Type: "HowToStep",
						},
						{
							Text: "Then add the cabbage, carrots, and white stems of the bok choy. Cook for 3 - 4 minutes.",
							Type: "HowToStep",
						},
						{
							Text: "Meanwhile, cook the noodles according to the package directions. Then drain and rinse with cold water to stop the cooking process.",
							Type: "HowToStep",
						},
						{
							Text: "Add the mock chicken back to the pan along with the bok choy leaves. Cook until warmed through.",
							Type: "HowToStep",
						},
						{
							Text: "Stir through the cooked noodles, then pour over the sauce and toss to combine. Cook for 3 minutes to allow the cornstarch to thicken.",
							Type: "HowToStep",
						},
						{Text: "Serve with green onions and sesame seeds. Enjoy!", Type: "HowToStep"},
					},
				},
				NutritionSchema: &models.NutritionSchema{},
				Name:            "The Best Vegan Chow Mein",
				PrepTime:        "PT20M",
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				TotalTime:       "PT35M",
				Yield:           &models.Yield{Value: 3},
				URL:             "https://www.pickuplimes.com/recipe/the-best-vegan-chow-mein-800",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:      "VideoObject",
							Description: "If you&#39;ve ever been on a quest for the ultimate noodle dish, your journey ends here. We&#39;re diving into a chow mein recipe that&#39;s become an obsession for our entire team—and even for our friends and family who aren&#39;t vegan. Packed with flavor and loaded with veggies, this dish rivals any takeout option and is perfect for impressing anyone, vegan or not. Master the golden formula for the perfect sauce and up your knife skills with our brief knife skills tutorial. Whether you&#39;re craving comfort food or looking to impress, this chow mein recipe is your one-stop solution. And trust us, once you try it, you&#39;ll be hooked just like we are. Let&#39;s get cooking!",
							EmbedURL:    "https://www.youtube.com/embed/vvm9na0x2_Q",
							Name:        "If I Could Make Only 1 Noodle Dish for the Rest of My Life… 🥢",
							ThumbnailURL: &models.ThumbnailURL{
								Value: "https://cdn.pickuplimes.com/cache/16/43/1643904be6b964bc60e62047ebb2a955.jpg",
							},
						},
					},
				},
			},
		},
		{
			name: "pinchofyum.com",
			in:   "https://pinchofyum.com/the-best-soft-chocolate-chip-cookies",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Dessert"},
				CookTime:      "PT10M",
				CookingMethod: &models.CookingMethod{Value: "Bake"},
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2020-10-15",
				Description: &models.Description{
					Value: "These are THE BEST soft chocolate chip cookies! No chilling required. Just ultra thick, soft, classic chocolate chip cookies!",
				},
				Keywords: &models.Keywords{
					Values: "chocolate chip cookies, best chocolate chip cookies, soft chocolate chip cookies, easy cookie recipe, small batch cookies",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"8 tablespoons of salted butter",
						"1/2 cup white sugar (I like to use raw cane sugar with a coarser texture)",
						"1/4 cup packed light brown sugar", "1 teaspoon vanilla", "1 egg",
						"1 1/2 cups all purpose flour (6.75 ounces)", "1/2 teaspoon baking soda",
						"1/4 teaspoon salt (but I always add a little extra)",
						"3/4 cup chocolate chips (I use a combination of chocolate chips and chocolate chunks)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat the oven to 350 degrees. Microwave the butter for about 40 seconds to just barely melt it. It shouldn't be hot &#8211; but it should be almost entirely in liquid form."},
						{Type: "HowToStep", Text: "Using a stand mixer or electric beaters, beat the butter with the sugars until creamy. Add the vanilla and the egg; beat on low speed until just incorporated &#8211; 10-15 seconds or so (if you beat the egg for too long, the cookies will be stiff)."},
						{Type: "HowToStep", Text: "Add the flour, baking soda, and salt. Mix until crumbles form. Use your hands to press the crumbles together into a dough. It should form one large ball that is easy to handle (right at the stage between &#8220;wet&#8221; dough and &#8220;dry&#8221; dough). Add the chocolate chips and incorporate with your hands."},
						{Type: "HowToStep", Text: "Roll the dough into 12 large balls (or 9 for HUGELY awesome cookies) and place on a cookie sheet. Bake for 9-11 minutes until the cookies look puffy and dry and just barely golden. Warning, friends: DO NOT OVERBAKE. This advice is probably written on every cookie recipe everywhere, but this is essential for keeping the cookies soft. Take them out even if they look like they're not done yet (see picture in the post). They'll be pale and puffy."},
						{Type: "HowToStep", Text: "Let them cool on the pan for a good 30 minutes or so (I mean, okay, eat four or five but then let the rest of them cool). They will sink down and turn into these dense, buttery, soft cookies that are the best in all the land. These should stay soft for many days if kept in an airtight container. I also like to freeze them."},
					},
				},
				Name: "The Best Soft Chocolate Chip Cookies",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "250 calories",
					Carbohydrates: "33.4 g",
					Cholesterol:   "35.9 mg",
					Fat:           "12.2 g",
					Fiber:         "1.4 g",
					Protein:       "3.2 g",
					SaturatedFat:  "7.5 g",
					Sodium:        "169.3 mg",
					Sugar:         "20.5 g",
					TransFat:      "0.3 g",
				},
				PrepTime:  "PT10M",
				TotalTime: "PT20M",
				Yield:     &models.Yield{Value: 12},
				URL:       "https://pinchofyum.com/the-best-soft-chocolate-chip-cookies",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:       "VideoObject",
							ContentURL:   "https://content.jwplatform.com/videos/wk3TBZA0.mp4",
							Description:  "These are THE BEST soft chocolate chip cookies! No chilling required. Just ultra thick, soft, classic chocolate chip cookies!",
							Name:         "The Best Soft Chocolate Chip Cookies",
							ThumbnailURL: &models.ThumbnailURL{Value: "https://content.jwplatform.com/thumbs/wk3TBZA0-720.jpg"},
							UploadDate:   time.Date(2021, 5, 18, 19, 38, 51, 0, time.UTC),
						},
					},
				},
			},
		},
		{
			name: "pingodoce.pt",
			in:   "https://www.pingodoce.pt/receitas/tarte-de-alho-frances-caramelizado/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DatePublished: "2021-09-01",
				Description: &models.Description{
					Value: "O alho-francês é um ingrediente muito versátil, que fica bem em várias receitas. Aqui, preparámos uma tarte de alho-francês caramelizado, com massa folhada e queijo. Experimente e delicie-se.",
				},
				Keywords: &models.Keywords{Values: "alho-francês, tartes"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"800 g alho-francês", "1 c. de sopa azeite Pingo Doce",
						"1 c. de chá flor de sal Pingo Doce", "1 q.b. pimenta",
						"1 q.b. tomilho fresco", "150 ml vinagre de vinho branco Pingo Doce",
						"3 c. de sopa manteiga", "1 c. de sopa açúcar mascavado Pingo Doce",
						"2 c. de sopa mostarda", "3 c. de sopa queijo parmesão ralado Pingo Doce",
						"230 g massa folhada Pingo Doce",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Pré-aqueça o forno a 200 °C."},
						{Type: "HowToStep", Text: "Corte dois alhos a meio e dois em quatro, eliminando as folhas."},
						{Type: "HowToStep", Text: "Coloque-os num tabuleiro e regue com o azeite. Tempere com flor de sal, pimenta e tomilho. Leve ao forno por 20 minutos ou até ficarem dourados."},
						{Type: "HowToStep", Text: "Numa frigideira de ferro ou que possa ir ao forno, adicione o vinagre e deixe cozinhar cerca de 1 minuto ou até reduzir."},
						{Type: "HowToStep", Text: "Junte a manteiga, o açúcar e mais um pouco de tomilho. Cozinhe durante cerca de 2 minutos."},
						{Type: "HowToStep", Text: "Retire os alhos do forno e coloque-os na frigideira alinhados sobre o molho de manteiga. Tente ao máximo que fiquem apertadinhos."},
						{Type: "HowToStep", Text: "Pincele-os com mostarda, polvilhe com o parmesão e cubra com a massa folhada. Empurre as bordas da massa para dentro."},
						{Type: "HowToStep", Text: "Leve ao forno por 35 minutos ou até a massa estar dourada."},
						{Type: "HowToStep", Text: "Retire do forno, deixe que arrefeça ligeiramente e vire para um prato."},
						{Type: "HowToStep", Text: "Sirva ainda quente."},
					},
				},
				Name: "Tarte de alho-francês caramelizado",
				NutritionSchema: &models.NutritionSchema{
					Calories: "411 calories",
				},
				PrepTime:     "PT45M",
				ThumbnailURL: &models.ThumbnailURL{},
				Tools:        &models.Tools{Values: []models.HowToItem{}},
				TotalTime:    "PT45M",
				Yield:        &models.Yield{Value: 4},
				URL:          "https://www.pingodoce.pt/receitas/tarte-de-alho-frances-caramelizado/",
				Video:        &models.Videos{},
			},
		},
		{
			name: "pinkowlkitchen.com",
			in:   "https://pinkowlkitchen.com/cajun-dirty-rice-with-smoked-sausage/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Main Course"},
				CookingMethod: &models.CookingMethod{},
				CookTime:      "PT20M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2022-04-08T15:41:52+00:00",
				Description: &models.Description{
					Value: "This Cajun dirty rice dish is made with chopped veggies, cajun spices, and smoked sausage and is loaded with flavor! Serve this rice with chicken, fish, or shrimp to create the ultimate Cajun meal.",
				},
				Keywords: &models.Keywords{Values: "cajun recipes, cajun rice, dirty rice, rice side dishes"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 cup long-grain rice", "2 1/4 cups chicken stock (divided)",
						"1 tablespoon butter (unsalted)", "1 tablespoon olive oil (extra virgin)",
						"12 ounces smoked sausage (about 4 medium links)",
						"1 small yellow onion (chopped)",
						"1 small red bell pepper (seeded and chopped)",
						"1 large stalk celery (chopped into half moons)", "3 cloves garlic (minced)",
						"1 teaspoon onion powder", "1 teaspoon garlic powder",
						"1 teaspoon smoked paprika", "1/2 teaspoon dried thyme",
						"1/2 teaspoon dried oregano", "1/2 teaspoon cayenne pepper",
						"salt and cracked black pepper (to taste)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Cook the rice in 2 cups of chicken stock until tender according to package instructions. Fluff the rice with a fork and set aside."},
						{Type: "HowToStep", Text: "In a medium heavy-bottomed skillet over medium-high heat, melt butter with the olive oil. Add the smoked sausage to the skillet and cook until the sausage is browned, about 3-5 minutes."},
						{Type: "HowToStep", Text: "Add the onion, bell pepper, and celery and cook until the veggies begin to soften, about 2-3 minutes. Add the garlic and cook until fragrant, about another minute."},
						{Type: "HowToStep", Text: "Season the sausage and vegetables with garlic powder, onion powder, smoked paprika, dried thyme, dried oregano, salt, black pepper, and cayenne pepper and stir with a wooden spoon."},
						{Type: "HowToStep", Text: "Add a little bit of chicken stock to the skillet to deglaze the pan, scraping up any brown bits with the wooden spoon. Add the cooked rice to the skillet and stir to combine the rice with the veggies and sausage. Continue to cook while stirring for another 2 to 3 minutes. Add a little more chicken stock if needed so that the rice isn't dry."},
						{Type: "HowToStep", Text: "Remove the pan from the heat and transfer the rice to a serving dish. Garnish with fresh chopped parsley if desired. Enjoy!"},
					},
				},
				Name: "Cajun Dirty Rice with Smoked Sausage",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "389 kcal",
					Carbohydrates: "45.4 g",
					Cholesterol:   "63 mg",
					Fat:           "15.5 g",
					Fiber:         "1.9 g",
					Protein:       "17 g",
					SaturatedFat:  "4.8 g",
					Servings:      "1",
					Sodium:        "942 mg",
					Sugar:         "4.5 g",
				},
				PrepTime:     "PT10M",
				ThumbnailURL: &models.ThumbnailURL{},
				Tools:        &models.Tools{Values: []models.HowToItem{}},
				TotalTime:    "PT30M",
				Yield:        &models.Yield{Value: 4},
				URL:          "https://pinkowlkitchen.com/cajun-dirty-rice-with-smoked-sausage/",
				Video:        &models.Videos{},
			},
		},
		{
			name: "platingpixels.com",
			in:   "https://www.platingpixels.com/mushroom-tart-recipe/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Appetizer"},
				CookTime:      "PT15M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2022-06-17T13:15:30+00:00",
				Description: &models.Description{
					Value: "With only 15 minutes of prep, this decadent, yet easy mushroom tart is ready in less than 30 minutes.",
				},
				Keywords: &models.Keywords{Values: "mushroom flatbread, Mushroom Tart, Mushroom Tart recipe"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 tablespoon olive oil", "1 medium yellow onion (diced)",
						"4-6 cups sliced Baby Bella mushrooms (about 16-ounces)", "½ teaspoon salt",
						"¼ teaspoon ground black pepper", "2 cloves minced garlic",
						"1 tablespoon fresh thyme leaves", "1 sheet Jus-Rol™ Puff Pastry Dough",
						"8- ounces shredded Italian cheese blend (or Mozzarella)",
						"1 medium egg (lightly beaten)",
					},
				}, Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat the oven to 425° F. Remove the Puff Pastry Dough from the fridge at let sit at room temp."},
						{Type: "HowToStep", Text: "Meanwhile, heat olive oil in a pan to medium heat. Add onions and saute until fragrant and slightly translucent, about 5 minutes. Add the mushrooms, salt, and pepper. Cook stirring occasionally until the mushrooms are browned and have released liquids, then the liquid evaporates, about 8 minutes."},
						{Type: "HowToStep", Text: "Stir in garlic and thyme and cook 2 minutes more. Remove the pan from the heat."},
						{Type: "HowToStep", Text: "Unroll the puff pastry sheet on a baking sheet, keeping the parchment on the bottom to prevent sticking. Score the edges using a sharp knife, leaving a 1-inch border. Then use a fork to prick the center puff pastry sheet every 2 to 3 inches."},
						{Type: "HowToStep", Text: "Top the puff pastry with grated cheese, leaving the 1-inch border of dough, followed by the sauteed mushrooms and onion mixture."},
						{Type: "HowToStep", Text: "Using a pastry brush, brush the dough border with the beaten egg to help with browning."},
						{Type: "HowToStep", Text: "Bake for 14-16 minutes, or until the puff pastry edges are golden brown."},
						{Type: "HowToStep", Text: "Remove from oven and let cool 2-3 minutes. Cut into squares and serve."},
					},
				},
				Name: "Mushroom Tart Recipe",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "197 kcal",
					Carbohydrates:  "12 g",
					Cholesterol:    "29 mg",
					Fat:            "14 g",
					Fiber:          "1 g",
					Protein:        "7 g",
					SaturatedFat:   "5 g",
					Servings:       "1",
					Sodium:         "274 mg",
					Sugar:          "1 g",
					TransFat:       "1 g",
					UnsaturatedFat: "8 g",
				},
				PrepTime:  "PT15M",
				TotalTime: "PT30M",
				Yield:     &models.Yield{Value: 12},
				URL:       "https://www.platingpixels.com/mushroom-tart-recipe/",
			},
		},
		{
			name: "plentyvegan.com",
			in:   "https://plentyvegan.com/almond-chickpea-chocolate-chip-cookies/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "dessert"},
				CookTime:      "PT8M",
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				Description:   &models.Description{Value: "Cookies that contain no flour are fascinating. Gluten-free, paleo, or just the adventurous bakers out there have given us an exciting new trend. It makes you feel like you just ate a salad rather than a chocolate chip cookie. Right?"},
				Keywords:      &models.Keywords{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"¼ coconut sugar",
						"¼ cup maple syrup",
						"¼ cup almond milk",
						"¼ cup coconut oil",
						"¼ cup almond butter",
						"¼ cup tahini",
						"¼ cup cooked sweet potato",
						"1 teaspoon vanilla extract",
						"1 cup garbanzo bean flour",
						"1 teaspoon baking powder",
						"½ teaspoon baking soda",
						"½ teaspoon salt",
						"½ cup chocolate chips",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{
							Text: "If you haven't already prepared your baked sweet potato, be sure to bake it! You can roast it whole in the oven for ~45 minutes at 425°F. Poke the potato with a fork before putting it on a baking sheet to bake.",
							Type: "HowToStep",
						},
						{Text: "Preheat oven to 350°F.", Type: "HowToStep"},
						{
							Text: "Grease 1 baking sheets with spray canola oil or a vegan butter. (You can always grease up another sheet if all the cookies don't all fit on one sheet.)",
							Type: "HowToStep",
						},
						{
							Text: "Combine the coconut sugar, maple syrup, almond milk and coconut oil and mix vigorously with a fork. If your coconut oil is solid, heat it in the microwave or on the stove until it is just melted (but not hot) before mixing it with the other ingredients.",
							Type: "HowToStep",
						},
						{
							Text: "Mix in the remaining wet ingredients: almond butter, tahini, sweet potato and vanilla extract.",
							Type: "HowToStep",
						},
						{
							Text: "Add in the flour, baking powder, baking soda and salt and mix until just combined.",
							Type: "HowToStep",
						},
						{Text: "Fold in the chocolate chips.", Type: "HowToStep"},
						{
							Text: "Roll golfball-size amounts of dough. Use your hands to flatten them before placing them on the greased cookie sheet. Leave about 1-2 inches between cookies in case they spread.",
							Type: "HowToStep",
						},
						{Text: "Bake for 8-10 minutes or until browned.", Type: "HowToStep"},
						{
							Text: "Let cool for 5 minutes on the baking sheet and then transfer to a cooking rack to cool completely.",
							Type: "HowToStep",
						},
					},
				},
				Name:            "Almond Chickpea Chocolate Chip Cookies",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT10M",
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 16},
				URL:             "https://plentyvegan.com/almond-chickpea-chocolate-chip-cookies/",
				Video:           &models.Videos{},
			},
		},
		{
			name: "ploetzblog.de",
			in:   "https://www.ploetzblog.de/rezepte/hartweizenbrot/id=61fbd728a672573b7a4f6e3e",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				Description:   &models.Description{Value: "100 % Hartweizen, 100 % italienischer Geschmack.\n\nDie einen fühlen sich an Zimt erinnert, die anderen an Nudeln. Die Meinungen über reine Hartweizenbrote gehen auseinander. Mal geliebt, mal gehasst. Ich gehöre eher zur wohlmeinenden Gruppe.\n\nDieses Rezept arbeitet mit Vor- und Sauerteig. Die Krume ist mittelporig und offen, saftig und aromatisch, die Kruste kräftig ausgebacken."},
				Keywords:      &models.Keywords{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"524 g Hartweizenmehl", "402 g Wasser", "50 g Weizenanstellgut", "12 g Salz",
						"11 g Olivenöl", "0,33 g Frischhefe",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Weizensauerteig\n1. Die Zutaten in der genannten Reihenfolge in eine Schüssel wiegen.\n2. Mischen, bis sich die Zutaten zu einem festen Teig verbunden haben.\n3. Mit einer Abdeckhaube, einem Deckel oder etwas ähnlichem zudecken.\n4. 12 Stunden bei 20 °C reifen lassen."},
						{Type: "HowToStep", Text: "Vorteig\n1. Die Zutaten in der genannten Reihenfolge in eine Schüssel wiegen.\n2. Mischen, bis sich die Zutaten zu einem festen Teig verbunden haben.\n3. Mit einer Abdeckhaube, einem Deckel oder etwas ähnlichem zudecken.\n4. 12 Stunden bei 20 °C reifen lassen."},
						{Type: "HowToStep", Text: "Autolyseteig\n1. Die Zutaten in der genannten Reihenfolge in eine Schüssel wiegen.\n2. Mischen, bis sich die Zutaten zu einem mittelfesten Teig verbunden haben.\n3. Mit einer Abdeckhaube, einem Deckel oder etwas ähnlichem zudecken.\n4. 30 Minuten bei 20 °C quellen lassen."},
						{Type: "HowToStep", Text: "Hauptteig\n1. Die Zutaten (außer Wasser B) in der genannten Reihenfolge in die Schüssel wiegen.\n2. Zu einem Teig vermischen.\n3. Kneten, bis sich eine dünne Teighaut ausziehen lässt (Fenstertest).\n4. Das Wasser B einarbeiten (gewünschte Teigtemperatur: ca. 27 °C).\n5. Mit einer Abdeckhaube, einem Deckel oder etwas ähnlichem zudecken.\n6. 3 Stunden bei 20 °C reifen lassen. Dabei nach 30 und 60 Minuten dehnen und falten.\n7. 30 Minuten bei 20 °C reifen lassen.\n8. Den Teig dehnen und falten.\n9. 30 Minuten bei 20 °C reifen lassen.\n10. Den Teig dehnen und falten.\n11. 2 Stunden bei 20 °C reifen lassen.\n12. Den Teig schonend aus der Schüssel oder Wanne auf die mit Hartweizenmehl bestreute Arbeitsfläche geben.\n13. Zwei gegenüberliegende Teigränder jeweils knapp über die Mitte legen (fast wie einen Geschäftsbrief falten), dann 90° versetzt dazu zu einem länglichen Laib aufwickeln. Auf das letzte Stückchen Teig Roggenmehl streuen, damit sich der Schluss beim Backen öffnet.\n14. 1 Stunde bei 20 °C mit Schluss nach unten im leicht bemehlten Gärkorb zugedeckt reifen lassen.\n15. Den Teigling aus dem Gärkorb auf Backpapier stürzen.\n16. Das Backpapier mit dem Teigling (Schluss nach oben) mithilfe eines flachen Bleches oder Brettes in den auf 280 °C vorgeheizten Ofen auf den Backstein befördern. Sofort kräftig bedampfen. Den Ofen sofort auf 220 °C herunterdrehen. Den Dampf nach 20 Minuten ablassen. Insgesamt 50 Minuten ausbacken."},
						{Type: "HowToStep", Text: "Ähnliche Rezepte\n1. Weizensauerteig-Ciabatta"},
					},
				},
				Name:            "Hartweizenbrot",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT17H20M",
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 1},
				URL:             "https://www.ploetzblog.de/rezepte/hartweizenbrot/id=61fbd728a672573b7a4f6e3e",
				Video:           &models.Videos{},
			},
		},
		{
			name: "plowingthroughlife.com",
			in:   "https://plowingthroughlife.com/the-best-rich-and-moist-chocolate-cake/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Dessert"},
				CookTime:      "PT35M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2023-01-21T10:07:00+00:00",
				Description: &models.Description{
					Value: "This Easy Chocolate Cake Recipe from a box mix is professional bakery-quality, but anyone can make it at home with simple ingredients.",
				},
				Keywords: &models.Keywords{Values: "Chocolate Box Cake, The Best Rich and Moist Chocolate Cake"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 box Devil's food cake mix", "3.4 ounce package instant chocolate pudding",
						"4 large eggs", "1 cup sour cream", "1/2 cup warm water",
						"1/2 cup vegetable oil", "1 1/2 cups semi-sweet chocolate chips",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat oven to 350°F. Grease a 9 x 13 inch pan."},
						{Type: "HowToStep", Text: "Mix all ingredients except chocolate chips at medium speed for 2 minutes."},
						{Type: "HowToStep", Text: "Gently fold in chips."},
						{Type: "HowToStep", Text: "I always use a 9 x 13 pan, by 2 - 9 inch round pans can also be used. Bake for 30 - 40 minutes until a toothpick inserted in the center comes out clean."},
					},
				},
				Name: "The Best Rich and Moist Chocolate Cake",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "363 kcal",
					Carbohydrates:  "37 g",
					Cholesterol:    "54 mg",
					Fat:            "23 g",
					Fiber:          "2 g",
					Protein:        "5 g",
					SaturatedFat:   "8 g",
					Servings:       "1",
					Sodium:         "353 mg",
					Sugar:          "23 g",
					TransFat:       "0.1 g",
					UnsaturatedFat: "13 g",
				},
				PrepTime:  "PT10M",
				TotalTime: "PT45M",
				Yield:     &models.Yield{Value: 15},
				URL:       "https://plowingthroughlife.com/the-best-rich-and-moist-chocolate-cake/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:      "VideoObject",
							ContentURL:  "https://mediavine-res.cloudinary.com/video/upload/t_original/v1665608961/imXifum7P.mp4",
							Description: "Are you craving a delicious chocolate cake?  This is the BEST rich and moist chocolate cake from a box mix that is unbelievably EASY to make!  This is a bakery quality cake that anyone can make at home with common ingredients!",
							Duration:    "PT82S",
							EmbedURL:    "https://video.mediavine.com/videos/imXifum7P.js",
							Name:        "Rich & Moist Chocolate Cake",
							ThumbnailURL: &models.ThumbnailURL{
								Value: "https://mediavine-res.cloudinary.com/image/upload/s--H2ahcV3O--/c_limit,f_auto,fl_lossy,h_1080,q_auto,w_1920/v1665608963/o3wucpclxhb4sit7fvr6.jpg",
							},
							UploadDate: time.Date(2020, 4, 23, 17, 11, 18, 0, time.UTC),
						},
					},
				},
			},
		},
		{
			name: "popsugar.co.uk",
			in:   "https://www.popsugar.co.uk/food/cinnamon-butter-baked-carrot-recipe-46882533",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Side Dishes"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{Value: "North American"},
				DateModified:  "2023-11-04T11:05:08+00:00",
				DatePublished: "2023-11-02T13:33:04+00:00",
				Description: &models.Description{
					Value: "This easy Christmas carrots recipe features fresh carrots smothered in cinnamon butter, baked until they're perfectly glazed.",
				},
				Keywords: &models.Keywords{
					Values: "Christmas, Fall Food, Fall Recipes, Original Recipes, Side Dishes, Carrots, Autumn, Exclusive",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"15 carrots, peeled and stems removed", "75g of butter, softened",
						"100g of sugar", "1 teaspoon kosher salt", "1/2 teaspoon ground cinnamon",
						"80ml boiling water", "2 1/2 teaspoons orange juice",
						"Fresh parsley, chopped, optional",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat the oven to 180°C (or gas mark 4)."},
						{Type: "HowToStep", Text: "Clean carrots and arrange in a 22 x 33 centimetre baking dish."},
						{Type: "HowToStep", Text: "Using an electric mixer, cream the butter, sugar, salt, and cinnamon. While the mixer is running, slowly add the boiling water and orange juice."},
						{Type: "HowToStep", Text: "Pour mixture over the carrots and cover the dish with aluminium foil. Bake for 90 minutes."},
						{Type: "HowToStep", Text: "Remove the foil and transfer carrots to a serving platter. Drizzle carrots with the melted cinnamon butter from the baking dish. Garnish with chopped parsley, if desired."},
					},
				},
				Name: "These Cinnamon-Butter Carrots Are Almost Too Easy to Make",
				NutritionSchema: &models.NutritionSchema{
					Calories: "219 per serving",
				},
				ThumbnailURL: &models.ThumbnailURL{},
				Tools:        &models.Tools{Values: []models.HowToItem{}},
				TotalTime:    "PT1H30M",
				Yield:        &models.Yield{Value: 6},
				URL:          "https://www.popsugar.co.uk/food/cinnamon-butter-baked-carrot-recipe-46882533",
				Video:        &models.Videos{},
			},
		},
		{
			name: "practicalselfreliance.com",
			in:   "https://practicalselfreliance.com/zucchini-relish/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				CookTime:      "PT10M",
				DatePublished: "2022-08-08",
				Description: &models.Description{
					Value: "Zucchini relish is a flavorful topping for summer grilling, and the perfect way to use up extra zucchini from the garden.",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"2 cups zucchini, diced (about 3 medium)",
						"1 cup onion, diced (about 1 medium)",
						"1 cup red bell pepper, diced (about 2 small or 1 large)",
						"2 Tablespoons Salt (pickling and canning salt, or kosher salt)",
						"1 3/4 cups sugar",
						"2 teaspoons celery seed (whole)",
						"1 teaspoon mustard seed (whole)",
						"1 cup cider vinegar (5% acidity)",
						"Pickle Crisp Granules (optional, helps veggies stay firm after canning)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Wash vegetables."},
						{Type: "HowToStep", Text: "Remove stem and blossom ends from zucchini and dice into 1/4 to 1/2 inch pieces. Measure 2 cups."},
						{Type: "HowToStep", Text: "Peel and dice onion. Measure 1 cup."},
						{Type: "HowToStep", Text: "Stem and seed peppers, then dice. Measure 1 cup."},
						{Type: "HowToStep", Text: "Important, don't skip this step! Combine diced vegetables in a large bowl and sprinkle salt over the top. Stir gently to distribute the salt, then add water until vegetables are completely submerged. Allow the vegetables to soak in the saltwater for 2 hours, then drain completely."},
						{Type: "HowToStep", Text: "Prepare a water bath canner (optional, only if canning)."},
						{Type: "HowToStep", Text: "In a separate saucepan or stockpot, bring vinegar, sugar, and spices to a gentle simmer (180 degrees F). Do not add salt, the salt is only used to soak veggies before draining."},
						{Type: "HowToStep", Text: "Add drained vegetables to the simmering vinegar/spices and gently simmer for 10 minutes."},
						{Type: "HowToStep", Text: "Pack hot relish into prepared half-pint or pint jars, leaving 1/2 inch headspace."},
						{Type: "HowToStep", Text: "If not canning, just seal jars and allow them to cool on the counter before storing in the refrigerator."},
						{Type: "HowToStep", Text: "If canning, de-bubble jars, wipe rims, and adjust headspace to ensure 1/2 inch. Seal with 2 part canning lids."},
						{Type: "HowToStep", Text: "Process in a water bath canner for 10 minutes, then turn off the heat. Allow the jars to sit in the canner for another 5 minutes to cool slightly, then remove the jars to cool on a towel on the counter."},
						{Type: "HowToStep", Text: "Leave the jars undisturbed for 24 hours, then check seals. Store any unsealed jars in the refrigerator for immediate use. Properly canned and sealed jars should maintain peak quality on the pantry shelf for 12-18 months."},
					},
				},
				Name:            "Zucchini Relish Recipe for Canning",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT2H10M",
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				TotalTime:       "PT2H30M",
				Yield:           &models.Yield{Value: 4},
				URL:             "https://creativecanning.com/zucchini-relish/",
				Video:           &models.Videos{},
			},
		},
		{
			name: "pressureluckcooking.com",
			in:   "https://pressureluckcooking.com/spanish-omelette-scramble/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Breakfast"},
				CookTime:      "PT20M",
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{Value: "Spanish"},
				DatePublished: "2023-10-26",
				Description: &models.Description{
					Value: "When I was in Valencia, Spain, I was taught how to make a Spanish omelette. It&#x27;s essentially pan-fried onions and potatoes coated with eggs, seasoned with the basics that are salt and pepper and then cooked in a skillet on both sides for a few minutes where it looks like a super thick, egg pancake. Truth be told, it is one of the most delicious egg dishes you&#x27;ll ever have. \n\nHOWEVER, as basic as it sounds, it can be a messy and somewhat cumbersomething to make with the flipping, removing a half-cooked, runny egg mound toa plate and then returning it to the pan to cook on the other side. At the class I took, three people who volunteered with flipping the half-cooked omelette had itspill onto the counter. So I decided to take the basics of a Spanish omelette, add some optional Spanish-favored cheese and meat and scramble itup to give you that flavor experience, but with a much simpler and fool-proof approach to making it.",
				},
				Keywords: &models.Keywords{Values: "Spanish Omelette, Scrambled Eggs"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1/2 cup extra virgin olive oil",
						"2 pounds Idaho or russet potatoes (about 2-3 of them), peeled, sliced into 1/4-inch pieces and then quartered",
						"1 large Spanish or yellow onion, sliced into thin strips",
						"2 teaspoons seasoned salt or regular salt (you can also use Tony Chachere’s Creole seasoning for a little spice)",
						"1 teaspoon black pepper (optional)", "12 large eggs, lightly beaten",
						"1 cup shredded Manchego cheese (optional, see Jeff's Tips)",
						"4 ounces jamón ibérico, Spanish chorizo (cured/charcuterie-style, NOT raw and the raw and crumbled kind in a tube), prosciutto, or deli ham, diced or sliced into small pieces (optional, see Jeff's Tips)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Add the olive oil to a 12-inch skillet/frying pan or large sauté pan (nonstick is definitely best here) and bring to medium-high heat."},
						{Type: "HowToStep", Text: "While the oil’s heating, gently crack the eggs into a bowl and whisk until smooth. Set aside."},
						{Type: "HowToStep", Text: "Once shimmering and heated, about 3 minutes, add the potato, onion, salt and pepper to the skillet and sauté for 15-20 minutes, stirring every 2-3 minutes until the onion and potato have softened and become golden-brown or even slightly charred in color (the potatoes should look like the color of breakfast hash browns/home fries)."},
						{Type: "HowToStep", Text: "Reduce the heat to medium-low. Pour the whisked eggs into the pan with the veggies and oil, top with the cheese and meat (if using either or both) and let it all rest, undisturbed without stirring, for 30-60 seconds. Almost immediately, the egg around the perimeter of the skillet will begin to solidify."},
						{Type: "HowToStep", Text: "Gently slide a silicone spatula under the eggs. A firm, yet fluffy bottom layer will have formed, and now it's time to scramble the eggs! Using the spatula (and NEVER a fork), gently swirl the eggs, veggies, cheese and meat around in the pan, folding it all together (aka mixing them with a swirly flip) so the egg clings to the veggies and the cheese begins to melt. This should take about 1-2 minutes total, at most. (NOTE: A Spanish omelette is typically served a little runny. Since this is an homage to that, I like to cook my eggs until they're JUST underdone and slightly runny. However, you can absolutely continue to cook your eggs until they're more well-done, if you desire. The oil in the pan will prevent them from drying out.)"},
						{Type: "HowToStep", Text: "Turn off the stove and remove the pan from the heat and serve immediately."},
					},
				},
				Name:            "Spanish Omelette Scramble",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT10M",
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				TotalTime:       "PT30M",
				Yield:           &models.Yield{Value: 4},
				URL:             "https://pressureluckcooking.com/spanish-omelette-scramble/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:       "VideoObject",
							ContentURL:   "https://www.youtube.com/watch?v=BFls1-xB190",
							Description:  "NEW Recipe!: https://pressureluckcooking.com/spanish-omelette-scramble/\n\nWhen I was in Valencia, Spain, I was taught how to make a Spanish omelette. It's essentially pan-fried onions and potatoes coated with eggs, seasoned with the basics that are salt and pepper and then cooked in a skillet on both sides for a few minutes where it looks like a super thick, egg pancake. Truth be told, it is one of the most delicious egg dishes you'll ever have. \n\nHOWEVER, as basic as it sounds, it can be a messy and somewhat cumbersome thing to make with the flipping, removing a half-cooked, runny egg mound to a plate and then returning it to the pan to cook on the other side. At the class I took, three people who volunteered with flipping the half-cooked omelette had it spill onto the counter. So I decided to take the basics of a Spanish omelette, add some optional Spanish-favored cheese and meat and scramble it up to give you that flavor experience, but with a much simpler and fool-proof approach to making it. I give you, the Spanish Omelette Scramble!\n\n#spanishomelette #spanishomelettescramble #pressureluck \n\nGet My #1 Bestselling SUPER SHORTCUT (green) Cookbook Here!: https://amzn.to/3QFiMdO\n\nGet My #1 Bestselling Original (orange) Cookbook Here!: https://amzn.to/3eqjEkQ\n\nGet My #1 Bestselling Lighter (blue) Cookbook Here!: https://amzn.to/2RWzrjS\n\nGet my #1 Bestselling Simple Comforts (yellow) Cookbook Here!: https://amzn.to/3kbH14A\n\nVISIT https://pressureluckcooking.com for MORE written recipes and easy-to-follow videos - with more always being added!\n\nWant the products I recommend and use? Check out my Amazon store here (#amazoninfluencer): https://www.amazon.com/shop/pressureluck\n\nWant even more content? Please visit and “like” Pressure Luck on Facebook at https://facebook.com/pressureluckcooking\n\nAdvertising Disclosure: Jeffrey Eisner/Pressure Luck is a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for sites to earn advertising fees by advertising and linking to amazon.com",
							Duration:     "PT14M34S",
							Name:         "Spanish Omelette Scramble",
							ThumbnailURL: &models.ThumbnailURL{Value: "https://i.ytimg.com/vi/BFls1-xB190/hqdefault.jpg"},
							UploadDate:   time.Date(2023, 10, 29, 14, 0, 12, 0, time.UTC),
						},
					},
				},
			},
		},
		{
			name: "primaledgehealth.com",
			in:   "https://www.primaledgehealth.com/slow-cooker-crack-chicken/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Appetizers"},
				CookTime:      "PT360M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2022-03-09T09:12:57+00:00",
				Description: &models.Description{
					Value: "Cheesy Ranch chicken, also known as Crack Chicken, is a low-carb slow cooker recipe with 5 ingredients! Easily made into a dip or dinner, depending on how you serve it, this ultra-creamy combo of chicken, cheese, and bacon is sure to please!",
				},
				Keywords: &models.Keywords{
					Values: "Cheesy Ranch Chicken, Keto Crack Chicken, Slow Cooker Crack Chicken",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"3 pounds chicken thigh (or breast)",
						"12 ounces cream cheese",
						"1 cup cheddar cheese (shredded)",
						"8 ounces bacon (cooked and crumbled)",
						"2 1-ounce Ranch seasoning packets (or follow the DIY option below)",
						"2 teaspoons parsley (dried)",
						"2 teaspoons dill (dried)",
						"2 teaspoons chives (dried)",
						"2 teaspoons onion powder",
						"2 teaspoons garlic powder",
						"1 teaspoon salt",
						"½ teaspoon ground black pepper",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Add chicken to slow cooker and cover with seasoning. Top with cream cheese. Use the back of a spoon to smear the cream cheese over the meat."},
						{Type: "HowToStep", Text: "Cover the slow cooker with a lid. Cook on LOW for 6-8 hours or HIGH 3-4 hours."},
						{Type: "HowToStep", Text: "Once cooking time finishes, shred the chicken by using two forks and pulling the meat apart. Remove bones if needed. Stir well and thoroughly coat the chicken with sauce."},
						{Type: "HowToStep", Text: "Fry bacon in a pan over medium heat on the stove. Remove and chop or crumble into small pieces. Cover the chicken with bacon and shredded cheese. Put the lid back on and continue cooking on HIGH for 15 minutes until cheese melts."},
						{Type: "HowToStep", Text: "Remove from heat. Mix bacon and cheese into the chicken or serve as is with them resting on top. Garnish with a tablespoon or two of fresh parsley if desired!"},
					},
				},
				Name: "Slow Cooker Crack Chicken (Cheesy Ranch Chicken)",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "603 kcal",
					Carbohydrates:  "3 g",
					Cholesterol:    "247 mg",
					Fat:            "39 g",
					Fiber:          "1 g",
					Protein:        "37 g",
					SaturatedFat:   "23 g",
					Servings:       "1",
					Sodium:         "689 mg",
					Sugar:          "1 g",
					TransFat:       "1 g",
					UnsaturatedFat: "30 g",
				},
				PrepTime:  "PT5M",
				TotalTime: "PT365M",
				Yield:     &models.Yield{Value: 8},
				URL:       "https://www.primaledgehealth.com/slow-cooker-crack-chicken/",
			},
		},
		{
			name: "projectgezond.nl",
			in:   "https://www.projectgezond.nl/italiaanse-kiprollade-met-gremolata/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Diner"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateModified:  "2023-12-04T13:31:53+00:00",
				Description: &models.Description{
					Value: "Ben je gek op kip pesto en valt een rollade ook altijd goed in de smaak? Maar vind je het op z’n tijd ook leuk en lekker om eens iets anders te proberen? Dan is dit recept echt iets voor jou! Een heerlijke zelfgemaakte kiprollade op Italiaanse wijze. De pesto vervang je door gremolata. Een …",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"400 gr kipfilet", "40 gr prosciutto", "40 gr zuivelspread",
						"40 gr platte peterselie", "1 teentje knoflook", "1 citroen",
						"10 ml olijfolie",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Snijd de kipfilets doormidden en leg de kipfilets op een stuk huishoudfolie."},
						{Type: "HowToStep", Text: "Hoe platter de kipfilets zijn hoe beter. Daarom gaan we ze platslaan. Bedek de kipfilets met nog een stuk huishoudfolie en sla ze voorzichtig plat met bijvoorbeeld een koekenpan."},
						{Type: "HowToStep", Text: "Verwijder de bovenste laag huishoudfolie en leg de kipfilets tegen elkaar aan."},
						{Type: "HowToStep", Text: "Bedek de kip met de prosciutto en bedek weer met een stuk huishoudfolie. Draai het geheel nu om zodat de prosciutto onderop komt te liggen."},
						{Type: "HowToStep", Text: "Smeer de kipfilet in met de zuivelspread."},
						{Type: "HowToStep", Text: "Maak de gremolata door de peterselie, knoflook, sap van de citroen en de olijfolie met elkaar te blenden in een keukenmachine of hakmolen."},
						{Type: "HowToStep", Text: "Verdeel de gremolata nu ook over de kipfilet."},
						{Type: "HowToStep", Text: "Rol de kipfilet met de prosciutto aan de buitenkant nu zo strak mogelijk in de folie en leg voor 1 uur in de koelkast."},
						{Type: "HowToStep", Text: "Verwarm de oven voor op 150 graden."},
						{Type: "HowToStep", Text: "Verwijder het folie van de kiprollade en bindt hem eventueel op met rolladetouw om te voorkomen dat hij uit elkaar valt."},
						{Type: "HowToStep", Text: "Leg de kiprollade in een ovenschaal en bak in ongeveer 45 à 60 minuten gaar."},
						{Type: "HowToStep", Text: "Snijd de kiprollade in mooie plakken en serveer ze direct."},
					},
				},
				Name: "Italiaanse kiprollade met gremolata",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "125 kcal",
					Carbohydrates: "1 gram",
					Fat:           "5 gram",
					Fiber:         "1 gram",
					Protein:       "18 gram",
				},
				ThumbnailURL: &models.ThumbnailURL{},
				Tools:        &models.Tools{Values: []models.HowToItem{}},
				Yield:        &models.Yield{Value: 1},
				URL:          "https://www.projectgezond.nl/italiaanse-kiprollade-met-gremolata/",
				Video:        &models.Videos{},
			},
		},
		{
			name: "przepisy.pl",
			in:   "https://www.przepisy.pl/przepis/placki-ziemniaczane",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Placki ziemniaczane"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DatePublished: "2010-11-12T14:29:28.000Z",
				Description: &models.Description{
					Value: "Jedni zajadają się plackami ziemniaczanymi posypanymi cukrem, inni z ochotą dodają do nich gęstą, kwaśną śmietanę, a jeszcze inni najbardziej cenią przepisy na placki ziemniaczane polane mięsnym gulaszem. Niewątpliwie najlepsze placki ziemniaczane to te usmażone na złoto, których chrupiąca, lekko przypieczona skórka skrywa miękki i delikatny środek. Niezależnie od tego, jakie dodatki należą do Twoich kulinarnych faworytów, poznaj naszą wersję przyrządzania tych przysmaków. Rumiane placki ziemniaczane to coś zdecydowanie więcej niż tylko potrawa charakterystyczna dla barów mlecznych.\r\nDla kogo? \r\nPrzepis na placki ziemniaczane przypadnie do gustu smakoszom ziemniaczanych potraw. Do stołu chętnie zasiądą również zwolennicy tradycyjnych dań. Kuchnia jak u mamy? Z plackami ziemniaczanymi według naszego przepisu ten efekt uzyskasz bez problemów. Masz ochotę na odrobinę nowości? Do chrupiących placuszków dodaj łososia albo krewetki – nie pożałujesz!\r\nNa jaką okazję? \r\nPlacki ziemniaczane to idealna propozycja na poskromienie większego głodu. Świetnie sprawdzają się w jesiennych i zimowych miesiącach jako rozgrzewający obiad. Jak zrobić placki ziemniaczane w takiej odsłonie? Sos grzybowy, żurawina i oscypek to sezonowe, obowiązkowe dodatki.\r\nCzy wiesz, że? \r\nZiemniaków nie musisz trzeć na drobnej tarce. Wystarczy, że zetrzesz je na grubych oczkach. Jak zrobić placki ziemniaczane tak, aby nie rozpadły się podczas smażenia, do masy ziemniaczanej dodaj jajko i odrobinę mąki. Ich postrzępione brzegi nie tylko pięknie się prezentują, ale też genialnie smakują i chrupią.\r\nDla urozmaicenia: \r\nPamiętaj, że przepis na placki ziemniaczane możesz dowolnie urozmaicić, serwując je z ulubionymi składnikami. Jak zrobić placki ziemniaczane, które zaskoczą wszystkich? Jeśli lubisz eksperymentować, do masy (oprócz czosnku) dorzuć ulubione zioła lub drobno pokrojone warzywa. Dzięki szpinakowi, papryce chili lub cebuli będą aromatyczne i kolorowe.",
				},
				Keywords: &models.Keywords{
					Values: "Na co dzień, Ziemniaki, Warzywa, Jajka, Łagodne, Bez mięsa",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 kilogram ziemniaki",
						"1 sztuka cebula",
						"2 sztuki jajka",
						"1 sztuka Przyprawa w Mini kostkach Czosnek Knorr",
						"1 szczypta gałka muszkatołowa",
						"1 szczypta sól",
						"3 łyżki mąka",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Obierz ziemniaki, zetrzyj na tarce. Odsącz masę przez sito. Zetrzyj cebulę na tarce."},
						{Type: "HowToStep", Text: "Dodaj do ziemniaków cebulę, jajka, gałkę muszkatołową oraz mini kostkę Knorr."},
						{Type: "HowToStep", Text: "Wymieszaj wszystko dobrze, dodaj mąkę, aby nadać masie odpowiednią konsystencję."},
						{Type: "HowToStep", Text: "Rozgrzej na patelni olej, nakładaj masę łyżką. Smaż placki z obu stron na złoty brąz i od razu podawaj."},
					},
				},
				Name:            "Placki ziemniaczane",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT40M",
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				TotalTime:       "PT40M",
				Yield:           &models.Yield{Value: 8},
				URL:             "https://www.przepisy.pl/przepis/placki-ziemniaczane",
				Video:           &models.Videos{},
			},
		},
		{
			name: "purelypope.com",
			in:   "https://purelypope.com/sweet-chili-brussel-sprouts/",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateModified:  "2020-09-17T22:05:26+00:00",
				DatePublished: "2020-05-21T00:35:12+00:00",
				Description:   &models.Description{},
				Keywords:      &models.Keywords{},
				Name:          "Sweet Chili Brussel Sprouts",
				Yield:         &models.Yield{Value: 4},
				PrepTime:      "PT10M",
				CookTime:      "PT32M",
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"2 cups brussel sprouts, stems removed & cut in half",
						"2 tbsp coconut aminos",
						"1 tbsp sriracha",
						"1/2 tbsp maple syrup",
						"1 tsp sesame oil",
						"Everything bagel seasoning or sesame seeds, to top",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat oven to 350 degrees."},
						{Type: "HowToStep", Text: "Whisk the sauce (coconut aminos, sriracha, maple syrup & sesame oil) together in a large bowl."},
						{Type: "HowToStep", Text: "Toss in brussel sprouts and coat mixture evenly over the brussels."},
						{Type: "HowToStep", Text: "Roast for 30 minutes."},
						{Type: "HowToStep", Text: "Turn oven to broil for 2-3 minutes to crisp (watch carefully to not burn.)"},
						{Type: "HowToStep", Text: "Top with everything or sesame seeds."},
					},
				},
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				URL:             "https://purelypope.com/sweet-chili-brussel-sprouts/",
				Video:           &models.Videos{},
			},
		},
		{
			name: "purewow.com",
			in:   "https://www.purewow.com/recipes/corn-fritter-caprese-peaches-tomatoes",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookTime:      "PT15M",
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DatePublished: "2020-08-19 00:00:00",
				Description:   &models.Description{Value: "Our summer meals are defined by two things: corn and tomatoes. So recipe developer Erin McDowell, author of The Fearless Baker and the upcoming The Book on Pie, had the genius idea to combine them into one unbeatable dish. Behold the corn fritter caprese (with peaches and tomatoes, because summer).\n\n“I love corn,” McDowell tells us, “and I’m always looking for new ways to cook with it in the summer. These corn fritters are something that I make a lot for a really simple dinner, but I’ve been playing around with making them into more of a meal. Usually, I just make the fritters and serve them alongside a salad, but I thought, ‘why not make the corn fritters part of the salad?’”\n\n“The only thing you have to cook is the fritters,” she continues, “so it’s really easy. They’re quick to throw together, so you can make this on a weeknight. But it’s also beautiful because of all the colors, and it’s fancy enough that if you put it down at a dinner party, it would elicit oohs and ahhs.”\n\nBe still our corn-loving hearts."},
				Keywords:      &models.Keywords{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"Corn Fritters",
						"1 bunch scallions, thinly sliced",
						"3 cups fresh corn kernels (from about 4 ears of corn)",
						"¼ cup chopped fresh parsley",
						"2 tablespoons chopped fresh basil",
						"¾ teaspoon kosher salt",
						"1 teaspoon freshly ground black pepper",
						"½ teaspoon crushed red-pepper flakes",
						"1 cup all-purpose flour",
						"1 teaspoon baking powder",
						"2 large eggs, whisked",
						"¼ cup half-and-half",
						"1 cup shredded mozzarella cheese",
						"⅓ cup grated Parmesan cheese",
						"3 tablespoons vegetable oil",
						"Assembly",
						"3 tomatoes, thickly sliced",
						"4 peaches, thickly sliced",
						"12 ounces fresh mozzarella, thickly sliced",
						"½ cup basil leaves, roughly torn",
						"Extra-virgin olive oil, as needed",
						"Flaky sea salt and freshly ground black pepper",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{
							Text: "In a large bowl, toss the scallions, corn, parsley, basil, salt, pepper and red-pepper flakes. Add the flour and baking powder, and toss until the mixture is well combined.",
							Type: "HowToStep",
						},
						{
							Text: "Add the eggs and half-and-half and then mix with a spatula until a thick batter forms. Fold in the mozzarella and Parmesan.",
							Type: "HowToStep",
						},
						{
							Text: "In a large skillet over medium heat, heat the vegetable oil. While it heats, line a baking sheet with paper towels.",
							Type: "HowToStep",
						},
						{
							Text: "When the oil is hot, scoop ¼-cup portions of batter into the skillet. You’ll need to work in batches, cooking just a few at a time. Cook until golden brown, about 3 minutes, then flip and cook until golden on the other side, about 2 to 3 minutes more.",
							Type: "HowToStep",
						},
						{
							Text: "When the fritters are cooked, transfer to the prepared baking sheet. Continue until you’ve used all the batter.",
							Type: "HowToStep",
						},
						{
							Text: "To assemble, arrange the corn fritters, tomatoes, peaches and mozzarella slices on a large platter. Sprinkle basil evenly over the top. Garnish with a generous drizzle of olive oil, flaky salt and freshly ground black pepper.",
							Type: "HowToStep",
						},
					},
				},
				Name: "Corn Fritter Caprese with Peaches and Tomatoes",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "582",
					Fat:           "30",
					Carbohydrates: "51",
					Protein:       "28",
					Sugar:         "14",
				},
				PrepTime:     "PT15M",
				ThumbnailURL: &models.ThumbnailURL{},
				Tools:        &models.Tools{Values: []models.HowToItem{}},
				Yield:        &models.Yield{Value: 1},
				URL:          "https://www.purewow.com/recipes/corn-fritter-caprese-peaches-tomatoes",
				Video:        &models.Videos{},
			},
		},
		{
			name: "purplecarrot.com",
			in:   "https://www.purplecarrot.com/recipe/gnocchi-al-pesto-with-charred-green-beans-lemon-zucchini-bc225f0b-1985-4d94-b05b-a78de295b2da?plan=chefs_choice",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DatePublished: "2020-05-13T06:59:57.162-04:00",
				Description:   &models.Description{},
				Keywords:      &models.Keywords{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 zucchini, trimmed and peeled lengthwise into ribbons",
						"1 lemon, half juiced, half cut into wedges (divided)",
						"1 tsp Aleppo pepper flakes",
						"6 oz green beans, cut in half",
						"10 oz fresh gnocchi",
						"¼ cup vegan basil pesto",
						"1 tbsp + 2 tsp olive oil*",
						"Salt and pepper*",
						"*Not included",
						"Ingredients are listed for 2 servings. If you're making 4 servings, please double your ingredients by using both meal kit bags provided.",
						"For full ingredient list, see Nutrition.",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "1 - Prepare the zucchini."},
						{Type: "HowToStep", Text: "2 - Char the green beans."},
						{Type: "HowToStep", Text: "3 - Cook the gnocchi."},
						{Type: "HowToStep", Text: "4 - Finish the gnocchi."},
						{Type: "HowToStep", Text: "5 - Serve."},
					},
				},
				Name: "Gnocchi Al Pesto with Charred Green Beans & Lemon Zucchini",
				NutritionSchema: &models.NutritionSchema{
					Calories: "540 cal",
					Fat:      "22.0 g",
				},
				PrepTime:     "PT30M",
				ThumbnailURL: &models.ThumbnailURL{},
				Tools:        &models.Tools{Values: []models.HowToItem{}},
				TotalTime:    "PT30M",
				Yield:        &models.Yield{Value: 2},
				URL:          "https://www.purplecarrot.com/recipe/gnocchi-al-pesto-with-charred-green-beans-lemon-zucchini-bc225f0b-1985-4d94-b05b-a78de295b2da?plan=chefs_choice",
				Video:        &models.Videos{},
			},
		},
		{
			name: "puurgezond.nl",
			in:   "https://www.puurgezond.nl/eten/sperziebonen/recepten/zalm-met-sperziebonen-en-cashew-dillesaus",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				CookTime:      "PT15M",
				Description:   &models.Description{Value: "Sperziebonen laten zich heel goed combineren met vis. Neem dit recept met zalm"},
				Keywords:      &models.Keywords{Values: "zalm, sperziebonen, cashew, hoofdgerecht, saus"},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{Values: []string{
					"4 zalmfilets",
					"2 eetlepels olie",
					"800 gram sperziebonen",
					"2 handjes cashewnoten, minimaal 1 uur geweekt in ruim water",
					"2 eetlepels limoensap",
					"6 eetlepels verse dille",
					"600 gram gekookte krieltjes in de schil",
				}},
				Instructions: &models.Instructions{Values: []models.HowToItem{
					{Type: "HowToStep", Text: "Verwarm de oven voor op 200 ºC. Leg de zalmfilets in een ovenschaal en bestrijk ze met de olie en eventueel wat peper en zout. Bak ze in het midden van de oven gaar in 15 minuten."},
					{Type: "HowToStep", Text: "Kook (of stoom) de cashewnoten in een klein laagje water, circa 8 minuten. Giet de cashewnoten af en doe ze met het limoensap, de dille, 60 ml koud water en een snufje zout in de keukenmachine of blender en blendeer tot een romige saus. Voeg eventueel wat meer water toe om te verdunnen."},
					{Type: "HowToStep", Text: "Serveer de zalm met krieltjes sperziebonen en cashew-dillesaus."},
				}},
				Name:            "Zalm met sperziebonen en cashew-dillesaus",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT30M",
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 4},
				URL:             "https://www.puurgezond.nl/eten/sperziebonen/recepten/zalm-met-sperziebonen-en-cashew-dillesaus",
				Video:           &models.Videos{},
			},
		},
	}
	for _, tc := range testcases {
		t.Run(tc.name, func(t *testing.T) {
			test(t, tc)
		})
	}
}
