package scraper_test

import (
	"testing"
	"time"

	"github.com/reaper47/recipya/internal/models"
)

func TestScraper_K(t *testing.T) {
	testcases := []testcase{
		{
			name: "keepinitkind.com",
			in:   "https://keepinitkind.com/jackfruit-vietnamese-summer-rolls-with-hoisin-peanut-sauce/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtGraph:       nil,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateModified:  "2016-08-21T22:27:30+00:00",
				DatePublished: "2016-08-25T16:00:38+00:00",
				Description: &models.Description{
					Value: "Jackfruit Vietnamese Summer Rolls with Hoisin Peanut Sauce Keepin' It Kind",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"Two 20-ounce cans jackfruit (in brine or water), rinsed and drained",
						"1/2 cup hoisin sauce (use gluten-free if necessary)",
						"1/4 cup + 1 tablespoon low-sodium tamari sauce",
						"1/4 cup rice vinegar",
						"3 tablespoons maple syrup",
						"2 tablespoons tomato paste",
						"1 tablespoon sriracha sauce",
						"1 tablespoon ume plum vinegar, optional",
						"2 teaspoons arrowroot powder",
						"2 tablespoons sesame oil",
						"5 shallots, diced",
						"2 garlic cloves, minced",
						"1 tablespoon minced lemongrass, optional",
						"1 teaspoon Chinese 5 spice",
						"14 sheets of rice paper, preferarbly white",
						"4-ounces rice vermicelli or maifun (very thin rice noodles), cooked according to package instructions and rinsed in cold water",
						"2 medium carrots, peeled and sliced into thin sticks",
						"1/2 English cucumber, sliced into thin sticks",
						"1 head of butter lettuce, leaves chopped into 1-inch strips",
						"Roughly 1/2 cup cilantro",
						"whole chives",
						"1/2 cup smooth, unsalted, unsweetened peanut butter",
						"3 1/2 tablespoons lime juice",
						"3 tablespoons water",
						"2 tablespoons hoisin sauce (use gluten-free if necessary)",
						"2 tablespoons low-sodium tamari sauce",
						"1-2 teaspoons sriracha sauce",
						"1 teaspoon minced fresh ginger",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{
							Text: "After rinsing and draining the jackfruit, use your fingers to tear it into small chunks. Set aside.",
							Type: "HowToStep",
						},
						{
							Text: "Preheat the oven to 400 F and line a baking sheet with parchment paper.",
							Type: "HowToStep",
						},
						{
							Text: "In a small bowl, whisk together the hoisin sauce, tamari, rice vinegar, maple syrup, tomato paste, sriracha, and ume plum vinegar until smooth. Whisk in the arrowroot powder until fully incorporated. Set aside.",
							Type: "HowToStep",
						},
						{
							Text: "Heat the sesame oil in a large, shallow saucepan over medium heat. Add the shallots and cook, stirring occasionally, until the shallots begin to turn translucent. Add the garlic and lemongrass and cook for a couple more minutes. And the Chinese 5 spice and stir until incorporated.",
							Type: "HowToStep",
						},
						{
							Text: "Add the jackfruit and let cook for about five minutes, stirring occasionally. Once softened a bit, use two forks to tear the jackfruit into smaller, more shredded pieces. Add the reserved hoisin sauce (you may have to give it a quick stir before pouring) and stir until combined. Let cook for a couple minutes before transferring to the prepared baking sheet.",
							Type: "HowToStep",
						},
						{
							Text: "Spread the jackfruit out into an even layer. Place the baking sheet in the oven and bake for about 25 minutes, stirring it and spreading it out again once halfway through. Once done, remove from teh oven and let cool, without stirring, for about 10 minutes.",
							Type: "HowToStep",
						},
						{
							Text: "While the jackfruit is baking, prepare your peanut sauce. In a medium bowl, whisk together the sauce ingredients until completely smooth. If you desire a thinner sauce, you can add more water a tablespoon at a time until you reach your desired consistency. Chill until ready to use.",
							Type: "HowToStep",
						},
						{
							Text: "To assemble: fill a wide bowl full of warm water. Dip one of the sheets of rice paper into the water and lay it out on a clean surface. Lay out about 1/4 cup of the jackfruit mixture into a small strip on the half of the rice paper closest to you. Top with a small handful of the rice pasta (about a scant 1/2 cup). Lay out several carrot and cucumber sticks next to the pile of pasta, top with a couple strips of lettuce, and then add a sprig of cilantro.",
							Type: "HowToStep",
						},
						{
							Text: "Fold the edge of rice paper closest to you over the pile. Fold the two side edges towards the center, and then roll the pile over once. Before you've rolled it all the way, add a couple chives, letting them stick out of one end, and then continue rolling until it is completely sealed. Please see this post for similar how-to photos.",
							Type: "HowToStep",
						},
						{
							Text: "Repeat with the remaining rice paper sheets and ingredients until all are completed. If necessary, you can make fewer rolls and refrigerate the rest of the ingredients for a day or two to make the rest of the rolls. If you make all the rolls at once, you can refrigerate the completed rolls overnight and eat it the next day, if you'd like. You should be able to make about 14 rolls total. Enjoy!",
							Type: "HowToStep",
						},
					},
				},
				Name:            "Jackfruit Vietnamese Summer Rolls with Hoisin Peanut Sauce",
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 14},
				URL:             "https://keepinitkind.com/jackfruit-vietnamese-summer-rolls-with-hoisin-peanut-sauce/",
				Video:           &models.Videos{},
			},
		},
		{
			name: "kennymcgovern.com",
			in:   "https://kennymcgovern.com/chicken-noodle-soup",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Soup"},
				CookTime:      "PT5M",
				Cuisine:       &models.Cuisine{Value: "Chinese"},
				DatePublished: "2022-03-27T18:12:02+00:00",
				Description:   &models.Description{},
				Keywords: &models.Keywords{
					Values: "noodles, Soup, noodle soup, chicken, chicken noodle soup, chicken soup",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"40g thin lucky boat noodles (soaked and drained, drained weight)",
						"275 ml light chicken stock",
						"Dash light soy sauce",
						"1/4 teaspoon sea salt",
						"1/4 teaspoon MSG",
						"Pinch white pepper",
						"50 grams raw chicken breast, thinly sliced (or 1 small handful cooked shredded chicken breast or thigh meat)",
						"1 spring onion (finely sliced)",
						"Dash sesame oil (optional, see notes)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Put the noodle nest in a bowl and cover with boiling water. Let stand for 2 minutes, mix briefly and drain the water. Place 40g of prepared noodles in a soup bowl (one nest of lucky boat noodles will do about 4-5 takeaway sized portions of soup). Set aside."},
						{Type: "HowToStep", Text: "Put the light chicken stock, light soy sauce, sea salt, MSG and white pepper in a saucepan, bring to the boil then reduce to a simmer. Add the sliced chicken and simmer for about 3 minutes until the chicken is cooked through."},
						{Type: "HowToStep", Text: "Pour the chicken soup over the prepared noodles in the bowl. Garnish with the sliced spring onion, drizzle with sesame oil (if using) and serve."},
					},
				},
				Name:      "Chicken Noodle Soup",
				PrepTime:  "PT5M",
				TotalTime: "PT10M",
				Yield:     &models.Yield{Value: 1},
				URL:       "https://kennymcgovern.com/chicken-noodle-soup",
			},
		},
		{
			name: "kingarthurbaking.com",
			in:   "https://www.kingarthurbaking.com/recipes/sourdough-zucchini-bread-recipe",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "bread:quick bread"},
				CookingMethod: &models.CookingMethod{},
				CookTime:      "PT1H5M",
				Cuisine:       &models.Cuisine{},
				DatePublished: "2021-06-03",
				Description: &models.Description{
					Value: "This delicious whole grain zucchini bread makes wonderful use of excess sourdough starter you might otherwise discard. Paired with summer’s avalanche of zucchini, it’s one loaf that solves two kitchen conundrums!",
				},
				Keywords: &models.Keywords{
					Values: "Quick bread, Lemon, Raisin, Sourdough, Spice, Breakfast & brunch",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"3/4 cup (170g) sourdough starter fed (ripe) or unfed (discard)",
						"1/2 cup (99g) granulated sugar",
						"1/4 cup (85g) honey",
						"6 tablespoons (75g) vegetable oil",
						"2 large eggs",
						"1/4 teaspoon nutmeg",
						"1 1/2 teaspoons lemon zest",
						"1 1/2 teaspoons King Arthur Pure Vanilla Extract",
						"1 cup (113g) King Arthur Golden Wheat Flour",
						"3/4 cup (90g) King Arthur Unbleached All-Purpose Flour",
						"1/2 teaspoon baking soda",
						"1 teaspoon baking powder",
						"1 teaspoon table salt",
						"2 cups (242g to 300g) grated zucchini somewhere between firmly and lightly packed",
						"3/4 cup (85g) chopped walnuts lightly toasted",
						"3/4 cup (128g) raisins currants or dried cranberries",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Preheat the oven to 350°F. Lightly grease a 9” x 5” quick bread pan or 12” x 4” tea loaf pan."},
						{Type: "HowToStep", Text: "In a large bowl, stir together the starter, sugar, honey, oil, eggs, nutmeg, lemon zest, and vanilla until thoroughly combined."},
						{Type: "HowToStep", Text: "In a separate medium bowl, whisk together the flours, baking soda, baking powder, and salt; stir into the wet ingredients."},
						{Type: "HowToStep", Text: "Stir in the grated zucchini, then the nuts and fruit. Transfer the batter to the prepared pan, smoothing the top."},
						{Type: "HowToStep", Text: "Bake the bread in the 9” x 5” pan for 45 minutes. Tent with foil and bake for an additional 20 minutes, until a thin paring knife inserted in the center comes out clean. For bread in a tea loaf pan, bake for 40 minutes before tenting, then bake for another 20 minutes, or until the loaf tests done."},
						{Type: "HowToStep", Text: "Remove the bread from the oven and cool in the pan on a rack."},
						{Type: "HowToStep", Text: "Store bread, well wrapped, at room temperature for up to three days; freeze for longer storage."},
					},
				},
				Name: "Sourdough Zucchini Bread",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "279",
					Carbohydrates:  "33",
					Cholesterol:    "23",
					Fat:            "13",
					Fiber:          "2",
					Protein:        "5",
					SaturatedFat:   "2",
					Servings:       "",
					Sodium:         "202",
					Sugar:          "21",
					TransFat:       "0",
					UnsaturatedFat: "",
				},
				PrepTime:  "PT30M",
				Tools:     &models.Tools{},
				TotalTime: "PT1H30M",
				Yield:     &models.Yield{Value: 16},
				URL:       "https://www.kingarthurbaking.com/recipes/sourdough-zucchini-bread-recipe",
			},
		},
		{
			name: "kingarthurbaking2.com",
			in:   "https://www.kingarthurbaking.com/recipes/fudge-brownies-recipe",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "cookies:brownies"},
				CookTime:      "PT32M",
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DatePublished: "2009-12-31",
				Description:   &models.Description{Value: "Fudgy, cakey, fudgy, cakey... can't make up your mind? If you're looking for a brownie that's right in between those two styles, you've found it. These brownies combine a fudge brownie's ultra-moist texture with a subtle cake-like rise, for the best of both worlds."},
				Keywords:      &models.Keywords{Values: "Brownies & blondies, Chocolate, Quick & easy"},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"4 large eggs",
						"1 1/4 cups (106g) Dutch-process cocoa",
						"1 teaspoon table salt",
						"1 teaspoon baking powder",
						"1 teaspoon espresso powder optional for enhanced flavor",
						"1 tablespoon King Arthur Pure Vanilla Extract",
						"16 tablespoons (227g) unsalted butter",
						"2 1/4 cups (447g) granulated sugar",
						"1 1/2 cups (180g) King Arthur Unbleached All-Purpose Flour",
						"2 cups (340g) chocolate chips",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Text: "Preheat the oven to 350°F. Lightly grease a 9\" x 13\" pan. If you plan to turn the whole sheet of brownies out of the pan at once, grease the pan, line it with parchment, and grease the parchment.", Type: "HowToStep"},
						{Text: "Crack the 4 eggs into a bowl, and beat them at medium speed with the cocoa, salt, baking powder, espresso powder, and vanilla for about 1 minute, or until smooth. You can do this while you're melting your butter (next step).", Type: "HowToStep"},
						{Text: "In a medium-sized microwave-safe bowl, or in a saucepan set over low heat, melt the butter, then add the sugar and stir to combine. Or simply combine the butter and sugar, and heat, stirring, until the butter is melted. Continue to heat (or microwave) briefly, just until the mixture is hot (about 110°F to 120°F), but not bubbling; it'll become shiny looking as you stir it. Heating the mixture to this point will dissolve more of the sugar, which will help produce a shiny top crust on your brownies.", Type: "HowToStep"},
						{Text: "Add the hot butter/sugar mixture to the egg/cocoa mixture, stirring until smooth.", Type: "HowToStep"},
						{Text: "Add the flour and chips, stirring until smooth. Again, adding the chips helps produce a shiny top crust.", Type: "HowToStep"},
						{Text: "Spoon the batter into a lightly greased 9\" x 13\" pan.", Type: "HowToStep"},
						{Text: "Bake the brownies for 28 to 32 minutes, until\u00a0the edges feel set, and the center should look very moist, but not uncooked. When testing to see if brownies are done, take a toothpick or the tip of a sharp knife and carefully poke it into the center of the pan, digging around just enough to see the interior. You should see moist crumbs, but no uncooked batter. Yes, you'll be left with a small divot in the center of your brownies; just cut around it when you're cutting the brownies into squares.", Type: "HowToStep"},
						{Text: "Remove them from the oven and cool on a rack before cutting and serving.", Type: "HowToStep"},
						{Text: "Store any leftovers, well-wrapped, at room temperature for 5 to 6 days. Freeze for longer storage.", Type: "HowToStep"},
					},
				},
				Name: "Fudge Brownies",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "260",
					Carbohydrates: "36",
					Cholesterol:   "55",
					Fat:           "17",
					Fiber:         "2",
					Protein:       "3",
					SaturatedFat:  "8",
					Servings:      "1",
					Sodium:        "130",
					Sugar:         "27",
					TransFat:      "0",
				},
				PrepTime:  "PT12M",
				Tools:     &models.Tools{},
				TotalTime: "PT40M",
				Yield:     &models.Yield{Value: 24},
				URL:       "https://www.kingarthurbaking.com/recipes/fudge-brownies-recipe",
			},
		},
		{
			name: "kitchenaid.com.au",
			in:   "https://kitchenaid.com.au/blogs/kitchenthusiast/hot-cross-buns",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Dessert"},
				CookTime:      "",
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateCreated:   "",
				DateModified:  "",
				DatePublished: "2019-04-15T19:41:00Z",
				Description: &models.Description{
					Value: "An everyday classic Easter treat! Ben Milbourne shares his recipe for hot cross buns, filled with fruit and spices. Serve fresh with a dollop of butter!\nExplore our Easter dessert and lunch recipe ideas too!",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"4 cups plain flour",
						"¼ cup caster sugar",
						"1 tsp cinnamon",
						"pinch of salt",
						"¾ cup sultanas",
						"2 x 7g sachets dried yeast",
						"3½ teaspoon ground allspice",
						"3¼ teaspoon grated nutmeg",
						"¾ cup currants",
						"300ml milk",
						"50g butter",
						"2 eggs",
						"Crosses",
						"4 Tbs plain flour",
						"4 Tbs water",
						"Glaze",
						"1/3 cup sugar",
						"½ cup hot water",
						"¼ tsp cinnamon",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Text: "Pre-heated oven to 220 degrees", Type: "HowToStep"},
						{
							Text: "Using the KitchenAid Sifter + Scale Attachment, sift flour, sugar, salt and spices into KitchenAid stand mixer bowl with dough hook attachment.",
							Type: "HowToStep",
						},
						{Text: "Add yeast", Type: "HowToStep"},
						{
							Text: "In a saucepan heat the milk over a low temperature, add butter, stir until melted",
							Type: "HowToStep",
						},
						{
							Text: "Add milk and butter mixture to dry mix and turn stand mixer to level 2 until mixed thoroughly. Add the eggs and then the dried fruit continue mixing for 3-4 minutes until the dough is smooth and no longer sticky.",
							Type: "HowToStep",
						},
						{
							Text: "Remove bowl from mixer, shape dough into a ball and cover with plastic wrap and place in a warm spot to prove for 1 hour or until doubled in size.",
							Type: "HowToStep",
						},
						{
							Text: "Portion dough into 12 equal sized buns, placed closely together on a greased baking tray. Leave to rise for 1 hour",
							Type: "HowToStep",
						},
						{
							Text: "To make the crosses, mix the flour and water thoroughly to form a thick paste. Spoon into a piping bag and pipe the paste in crosses on the buns",
							Type: "HowToStep",
						},
						{Text: "Bake in oven for 20 minutes or until golden", Type: "HowToStep"},
						{
							Text: "Mix glaze ingredients together until sugar has dissolved. Brush glaze over buns while still hot.",
							Type: "HowToStep",
						},
					},
				},
				Name:            "Hot Cross Buns",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT1H20M",
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				TotalTime:       "",
				Yield:           &models.Yield{Value: 12},
				URL:             "https://kitchenaid.com.au/blogs/kitchenthusiast/hot-cross-buns",
				Video:           &models.Videos{},
			},
		},
		{
			name: "kitchensanctuary.com",
			in:   "https://www.kitchensanctuary.com/air-fryer-crispy-chicken-wings/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtGraph:       nil,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Appetizer"},
				CookTime:      "PT35M",
				CookingMethod: nil,
				Cuisine:       &models.Cuisine{Value: "American"},
				DateCreated:   "",
				DateModified:  "",
				DatePublished: "2022-11-28T14:34:51+00:00",
				Description: &models.Description{
					Value: "These crispy chicken wings cook in the air fryer in 35 minutes. The perfect party food! They taste great on their own or smothered in your favourite sauce.",
				},
				Keywords: &models.Keywords{Values: "air fryer cooking"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"2.2 lbs (1 kg) chicken wings", "1 level tbsp aluminium-free baking powder*",
						"½ tsp table salt", "½ tsp pepper",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Text: "Cut each wing at the joint so you have a mini wing and a drumette.", Type: "HowToStep"},
						{Text: "Dry the wings with paper towels, then place in a large bowl and add the baking powder, salt and pepper. Toss to combine. Note - it&#39;s important to dry the wings first so they only get a light coating.", Type: "HowToStep"},
						{Text: "Add to air fryer, cook for 30-35 minutes at 210C/410F, shaking the basket every 10 minutes.", Type: "HowToStep"},
						{Text: "Serve on their own or with your favourite sauce.", Type: "HowToStep"},
					},
				},
				Name: "Air Fryer Crispy Chicken Wings",
				NutritionSchema: &models.NutritionSchema{
					Calories:       "30",
					Carbohydrates:  "0.02",
					Cholesterol:    "10",
					Fat:            "2",
					Fiber:          "0.01",
					Protein:        "2",
					SaturatedFat:   "1",
					Servings:       "1",
					Sodium:         "42",
					TransFat:       "0.03",
					UnsaturatedFat: "1.5",
				},
				PrepTime:     "PT5M",
				ThumbnailURL: nil,
				Tools:        nil,
				TotalTime:    "PT40M",
				Yield:        &models.Yield{Value: 40},
				URL:          "https://www.kitchensanctuary.com/air-fryer-crispy-chicken-wings/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:       "VideoObject",
							ContentURL:   "https://content.jwplatform.com/videos/ikK7sjgH.mp4",
							Description:  "These crispy chicken wings cook in the air fryer in 35 minutes - no oil needed!\nThe perfect party food! They taste great on their own, or smothered in your favourite sauce.",
							Name:         "Air Frier Crispy Chicken",
							ThumbnailURL: &models.ThumbnailURL{Value: "https://content.jwplatform.com/thumbs/ikK7sjgH-720.jpg"},
							UploadDate:   time.Date(2022, 11, 28, 14, 9, 4, 0, time.UTC),
						},
					},
				},
			},
		},
		{
			name: "kitchenstories.com",
			in:   "https://www.kitchenstories.com/de/rezepte/valencianische-paella",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Vegetarische Gerichte"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{Value: "spanisch und portugiesisch"},
				DatePublished: "2015-03-12T03:00:00+0000",
				Description: &models.Description{
					Value: "Wer sagt das man Meeresfrüchte für eine gute Paella braucht. Lerne wie du eine perfekte Paella nur mit Gemüse machst – schnell & einfach zum Nachkochen!",
				},
				Keywords: &models.Keywords{
					Values: "kinderfreundlich,Brand Content,Alltagsgerichte,vegetarisch,vegan,Vorspeise,Beilagen,Hauptgericht,Party Food,street food,pescetarisch,Wohlfühlessen,laktosefrei,Gewürze,Fleischlos,Le Creuset,thermohauser,spanisch und portugiesisch,herzhaft,für vier,Alkohol,Kräuter,Gemüse,anschwitzen",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"100 g Oliven", "350 g Cherrytomaten", "2 Knoblauch", "2 Frühlingszwiebeln",
						"1 Zwiebel (rot)", "2 Paprika (rot)", "1 Zucchini", "1 Aubergine",
						"250 g Reis", "2 Zitronen", "0.5 TL Safran", "100 ml Weißwein",
						"300 ml Gemüsebrühe", "300 g Erbsen", "Salz", "Pfeffer",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Oliven abgießen. Cherrytomaten halbieren, Knoblauch hacken und Frühlingszwiebeln in feine Ringe schneiden. Zwiebel, Paprika, Zucchini und Aubergine in walnussgroße Stücke schneiden."},
						{Type: "HowToStep", Text: "Etwas Olivenöl in die Pfanne geben und Knoblauch, Zwiebel, Paprika, Zucchini und Aubergine bei mittlerer Hitze ca. 4 – 6 Min. anbraten."},
						{Type: "HowToStep", Text: "Reis in die Pfanne geben und gut umrühren. Für weitere 1 – 2 Min. anbraten."},
						{Type: "HowToStep", Text: "Zitronen filitieren."},
						{Type: "HowToStep", Text: "Safran in die Pfanne geben und gut umrühren, um alles zu vermengen. Für weitere 1 – 2 Min. braten."},
						{Type: "HowToStep", Text: "Mit Weißwein ablöschen. Gemüsebrühe hinzugeben, bis alle Zutaten mit Flüssigkeit bedeckt sind. Nach Geschmack mit Salz und Pfeffer würzen. Alles aufkochen lassen, dann auf ein Köcheln reduzieren und ca. 15 – 20 Min. köcheln lassen, bis der Reis bissfest ist. Gelegentlich umrühren."},
						{Type: "HowToStep", Text: "Vorsichtig die Zitronenfilets, Tomaten, Oliven, Frühlingszwiebeln und Erbsen unterheben. Für weitere 5 – 6 Min. braten. Genießen!"},
					},
				},
				Name: "Vegetarische Paella mit Zucchini und Aubergine",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "448",
					Carbohydrates: "69",
					Fat:           "7",
					Protein:       "15",
					Servings:      "1",
				},
				PrepTime: "PT45M",
				ThumbnailURL: &models.ThumbnailURL{
					Value: "https://images.kitchenstories.io/recipeImages/RP02_18_06_valencianPaella_titlePicture.jpg",
				},
				Tools:     &models.Tools{Values: []models.HowToItem{}},
				TotalTime: "PT45M",
				URL:       "https://www.kitchenstories.com/de/rezepte/valencianische-paella",
				Video:     &models.Videos{},
				Yield:     &models.Yield{Value: 4},
			},
		},
		{
			name: "kochbar.de",
			in:   "https://www.kochbar.de/rezept/465773/Spargelsalat-Fruchtig.html",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Hauptspeise"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{Value: "Internationale Küche"},
				DatePublished: "2013-04-20T18:30:20+02:00",
				Description:   &models.Description{Value: "lauwarmer Spargel-Salat"},
				Keywords: &models.Keywords{
					Values: "Spargelsalat Fruchtig, Spargel grün frisch, Spargel weiss frisch, Mango frisch",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 kg Spargel grün frisch",
						"1 Kg Spargel weiss frisch",
						"1 Stück Mango frisch",
						"1 Stück Orange frisch",
						"4 El Olivenöl",
						"Gourmet-Pfeffer aus meinem KB",
						"Salz",
						"Zucker",
						"Räucherlachs",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "für 2 Personen als Hauptspeise \r\nfür 4 Personen als Vorspeise"},
						{Type: "HowToStep", Text: "1. Spargel schälen und in 4-5 Stücke schneiden"},
						{Type: "HowToStep", Text: "3. Spargel inm Salzwasser und wenig Zucker bissfest Kochen. Wasser wegschütten"},
						{Type: "HowToStep", Text: "4. leicht abkühlen lassen und in der Zwischenzeit die Mango schälen und in kleine Würfel schneiden"},
						{Type: "HowToStep", Text: "Dressing"},
						{Type: "HowToStep", Text: "Saft von 1 Orange in eine Schüssel geben und das Olivenöl hinzufügen gut verrühren und mit Salz und Pfeffer abschmecken. Die Spargeln darin wenden und ein wenig ziehen lassen."},
						{Type: "HowToStep", Text: "Schön Anrichten und mit Lachs garnieren ANSTELLE Lachs passen auch wunderbar Crevetten dazu."},
					},
				},
				Name: "Spargelsalat Fruchtig",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "97",
					Carbohydrates: "1.87273",
					Fat:           "9.23273",
					Protein:       "1.78182",
					Servings:      "100 g",
				},
				ThumbnailURL: &models.ThumbnailURL{},
				Tools:        &models.Tools{Values: []models.HowToItem{}},
				Yield:        &models.Yield{Value: 2},
				URL:          "https://www.kochbar.de/rezept/465773/Spargelsalat-Fruchtig.html",
				Video:        &models.Videos{},
			},
		},
		{
			name: "kochbucher.com",
			in:   "https://kochbucher.com/eierlikor-pralinen/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				Description: &models.Description{
					Value: "Zutaten : 200 g Schokolade, weiße 25 g Butter 125 g Mandel(n), gemahlene 75 ml Eierlikör Zubereitung : Arbeitszeit: ca. 1 Std. Ruhezeit: ca. 1 Tag Schwierigkeitsgrad: simpel Kalorien p. P.: keine Angabe Die Schokolade mit der Butter langsam schmelzen. Einen Teil der Mandeln mit unterheben, dann den Eierlikör unterrühren. Am besten über Nacht erkalten […]",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"200 g Schokolade, weiße", "25 g Butter", "125 g Mandel(n), gemahlene",
						"75 ml Eierlikör",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Arbeitszeit: ca. 1 Std. Ruhezeit: ca. 1 Tag\nSchwierigkeitsgrad: simpel\nKalorien p. P.: keine Angabe"},
						{Type: "HowToStep", Text: "Die Schokolade mit der Butter langsam schmelzen. Einen Teil der Mandeln mit unterheben, dann den Eierlikör unterrühren. Am besten über Nacht erkalten lassen."},
						{Type: "HowToStep", Text: "Mit Hilfe von einem Teelöffel kleine Mengen abstechen und zu Kugeln formen. Die Kugeln anschließend in den restlichen gemahlenen Mandeln wälzen und in Papierförmchen setzen. Kühl aufbewahren!"},
						{Type: "HowToStep", Text: "Das Rezept ergibt ca. 24 Pralinen."},
					},
				},
				Name:            "Eierlikör – Pralinen",
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 1},
				URL:             "https://kochbucher.com/eierlikor-pralinen/",
				Video:           &models.Videos{},
			},
		},
		{
			name: "koket.se",
			in:   "https://www.koket.se/mitt-kok/tommy-myllymaki/myllymakis-toast-skagen",
			want: models.RecipeSchema{
				AtContext: atContext,
				AtType:    &models.SchemaType{Value: "Recipe"},
				Category:  &models.Category{Value: "uncategorized"},
				Description: &models.Description{
					Value: "Toast skagen är en klassisk förrätt på årets festdag - nyårsafton. Tommys variant görs med hemslagen majonnäs, pepparrot och löjrom.",
				},
				Image: &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"1 kg räkor med skal (gärna färska av fin kvalitet)",
						"2 äggulor",
						"2 tsk senap",
						"1 msk vitvinsvinäger",
						"6 dl matolja",
						"1 kruka dill",
						"10 cm färsk pepparrot, skalad",
						"4 skivor vitt bröd (ej levain)",
						"smör, till stekning",
						"50 g löjrom",
						"1 citron",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Skala alla räkor och ställ åt sidan."},
						{Type: "HowToStep", Text: "Gör en majonnäs genom att lägga ner äggulor, senapen och vinägern i en bunke. Tillsätt matoljan i en tunn stråle medan du vispar hela tiden. Använd elvisp eller handvisp. När majonnäsen är tjock och du ser dragen/spåren av vispen i majonnäsen är den klar."},
						{Type: "HowToStep", Text: "Lägg alla räkor i en bunke, tillsätt fint plockad dill och blanda ner lite majonnäs i taget."},
						{Type: "HowToStep", Text: "Tillsätt lite riven pepparrot och smaka av. Slå på mer majonnäs för en rinnigare röra eller mer pepparrot för mer sting."},
						{Type: "HowToStep", Text: "Ta fram brödet och skär ut önskad form utan att ta med kanterna, använd en skål eller ett glas som mall om ni vill ha runda bröd. Stek sedan gyllene i smör."},
						{Type: "HowToStep", Text: "Lägg upp bröden på tallrik, toppa med skagenröra och en rejäl klick löjrom. Avsluta med en dillkvist och en citronskiva."},
					},
				},
				Name:      "Myllymäkis toast skagen",
				TotalTime: "PT25M",
				URL:       "https://www.koket.se/mitt-kok/tommy-myllymaki/myllymakis-toast-skagen",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:       "VideoObject",
							ContentURL:   "https://www.tv4play.se/iframe/video/20277435?autoload=true",
							Description:  "Myllymäkis toast skagen",
							EmbedURL:     "https://www.tv4play.se/iframe/video/20277435?autoload=true",
							Name:         "Myllymäkis toast skagen",
							ThumbnailURL: &models.ThumbnailURL{Value: "https://img.koket.se/standard-mega/myllymakis-toast-skagen-2.jpg"},
							UploadDate:   time.Date(2014, 12, 29, 5, 0, 0, 0, time.UTC),
						},
					},
				},
				Yield: &models.Yield{Value: 4},
			},
		},
		{
			name: "kookjij.nl",
			in:   "https://www.kookjij.nl/recepten/daging-smoor-heerlijk-gestoofd-indisch-rundvlees-ook-voor-slowcooker",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Hoofdgerechten - Vlees"},
				CookTime:      "",
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{Value: "Indonesie"},
				DatePublished: "2024-06-26T17:38:06+02:00",
				Description:   &models.Description{Value: "Daging Smoor heerlijk gestoofd Indisch rundvlees ook voor slowcooker is een lekker recept, Deze stoofpot is heel gemakkelijk te maken.Vlees in gedeelten aanbraden, alle andere ingrediënten erbij en dan ....Stoven maar ! Uitermate geschikt voor de slowcooker omdat je er dan dan geen omkijken meer naar hebt. Maar ook in de pan gemakkelijk te maken. \nWij hebben ervan gesmuld."},
				Keywords:      &models.Keywords{},
				Image:         &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"400 gram runderlappen (sukadelappen of riblappen)",
						"2 eetlepels zonnebloemolie",
						"3 tenen knoflook, gesnipperd + 5 sjalotjes, gesnipperd",
						"1/2 theelepel nootmuskaat",
						"1/4 theelepel gemalen kruidnagels",
						"½ eetlepel kerriepoeder (zelf toegevoegd)",
						"½ eetlepel azijn",
						"zout + peper",
						"½ eetlepel donkerbruine basterdsuiker (zelf toegevoegd)",
						"1 tomaat, ontveld",
						"4 eetlepel ketjap manis",
						"300 ml water",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{
							Text: "Een scheutje zonnebloemolie in een hapjespan verhitten.",
							Type: "HowToStep",
						},
						{
							Text: "De runderlappen in dobbelstenen snijden en rondom bruin bakken.",
							Type: "HowToStep",
						},
						{
							Text: "De gesnipperde uien, knoflook en alle kruiden toevoegen en even mee fruiten.",
							Type: "HowToStep",
						},
						{
							Text: "De ontvelde tomaat in stukjes snijden en toevoegen aan de pan gelijk met 4 eetlepels ketjap manis, een scheutje azijn en 300 ml water en laat dit 3 uur zacht stoven* **",
							Type: "HowToStep",
						},
						{
							Text: "Nu nog even proeven en eventueel nog water en/of ketjap toevoegen",
							Type: "HowToStep",
						},
						{
							Text: "* **Op dit moment kan het vlees in de slowcooker (6 uur op low de laagste stand)",
							Type: "HowToStep",
						},
					},
				},
				Name:            "Daging Smoor heerlijk gestoofd Indisch rundvlees ook voor slowcooker",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT20M",
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools: &models.Tools{
					Values: []models.HowToItem{
						{Quantity: 1, Text: "koekenpan", Type: "HowToTool"},
						{Quantity: 1, Text: "stoofpan of slowcooker", Type: "HowToTool"},
					},
				},
				Yield: &models.Yield{Value: 2},
				URL:   "https://www.kookjij.nl/recepten/daging-smoor-heerlijk-gestoofd-indisch-rundvlees-ook-voor-slowcooker",
				Video: &models.Videos{},
			},
		},
		{
			name: "kptncook.com",
			in:   "https://mobile.kptncook.com/recipe/pinterest/empanadas-mit-wuerziger-tomaten-salsa/3f1e5736",
			want: models.RecipeSchema{
				AtContext:       "https://schema.org",
				AtType:          &models.SchemaType{Value: "Recipe"},
				Category:        &models.Category{Value: "uncategorized"},
				CookingMethod:   &models.CookingMethod{},
				NutritionSchema: &models.NutritionSchema{},
				Cuisine:         &models.Cuisine{},
				Description:     &models.Description{},
				Keywords:        &models.Keywords{},
				Image:           &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"0 red onion",
						"1 chili pepper",
						"1 cup(s) cilantro, fresh",
						"1 lime",
						"1 cup(s) cheese, shredded",
						"egg",
						"1 tomato",
						"pepper",
						"salt",
						"butter",
						"vegetable oil",
						"wheat flour",
						"water",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "All set?"},
						{Type: "HowToStep", Text: "Knead butter, flour, water, egg, and salt into a uniform dough."},
						{Type: "HowToStep", Text: "Wrap in cling film and refrigerate."},
					},
				},
				Name:         "Cheese Empanadas with Fresh Tomato Salsa",
				PrepTime:     "PT30M",
				ThumbnailURL: &models.ThumbnailURL{},
				Tools:        &models.Tools{Values: []models.HowToItem{}},
				Yield:        &models.Yield{Value: 2},
				URL:          "https://mobile.kptncook.com/recipe/pinterest/empanadas-mit-wuerziger-tomaten-salsa/3f1e5736",
				Video:        &models.Videos{},
			},
		},
		{
			name: "kristineskitchenblog.com",
			in:   "https://kristineskitchenblog.com/blackberry-pie/",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Dessert"},
				CookTime:      "PT60M",
				Cuisine:       &models.Cuisine{Value: "American"},
				DatePublished: "2024-07-02T07:12:14+00:00",
				Description: &models.Description{
					Value: "This homemade blackberry pie has a sweet blackberry filling and an all-butter flaky pie crust. It&#39;s surprisingly simple to make and so good with a scoop of vanilla ice cream!",
				},
				Keywords: &models.Keywords{Values: "blackberry pie, blackberry pie recipe"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"6 cups fresh blackberries (about 30 ounces, see note below about frozen berries)",
						"½ cup granulated sugar (or to taste*)",
						"3 tablespoons cornstarch (use ¼ cup if using frozen blackberries)",
						"2 teaspoons fresh lemon juice", "1 teaspoon vanilla extract",
						"2 ¼ cups all-purpose flour", "1 tablespoon granulated sugar",
						"½ teaspoon salt",
						"1 cup cold unsalted butter (cut into cubes)",
						"7 tablespoons ice-cold water",
						"1 egg",
						"1 tablespoon milk",
						"coarse (turbinado) sugar or granulated sugar (optional, for sprinkling on top of pie)",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Text: "Preheat oven to 400° F with a rack in the lower third of the oven.", Type: "HowToStep"},
						{Text: "Place blackberries in a large bowl. Add the sugar, cornstarch, lemon juice and vanilla and stir until well combined. Let the filling mixture rest while you make the pie crust so that the berries release some of their juices.", Type: "HowToStep"},
						{Text: "Place the flour, granulated sugar and salt in the bowl of a food processor fitted with the steel blade. (Alternatively, the pie dough can be made by hand in a bowl using a pastry cutter.) Pulse a few times to combine.", Type: "HowToStep"},
						{Text: "Add the cold butter cubes and pulse 10-12 times, until the butter pieces are the size of small peas. Then add the ice-cold water and pulse until the dough starts to come together.", Type: "HowToStep"},
						{Text: "Turn the dough out onto a lightly floured work surface and bring it together into a ball; cut it in half. Form each half into a round disk. Refrigerate one dough disk.", Type: "HowToStep"},
						{Text: "Roll out bottom pie crust: On a floured work surface, use a rolling pin to roll the other dough disk out into a circle that is 12 inches in diameter, turning the dough a quarter turn with each roll as you roll it out. Place dough circle into a 9x2-inch deep dish pie dish. (Gently wrap dough around the rolling pin to transfer it.) Gently smooth the dough out into the pie dish, but do not press it down firmly into the dish as this can cause the crust to stick to the dish.", Type: "HowToStep"},
						{Text: "Stir the blackberry mixture again to make sure that everything is well distributed. Transfer the blackberries and all juices from the bowl to the pie dish with the rolled out pie crust. Set aside.", Type: "HowToStep"},
						{Text: "Roll out the top pie crust: Place the second dough disk onto a floured work surface. Roll it out into a 12-inch diameter circle. To make a lattice top crust, use a sharp knife, pizza cutter or pastry wheel to cut the dough circle into ½-inch strips. Using every other strip from the circle, arrange half of the dough strips going one direction across the top of the pie, leaving a little bit of space in between each strip. Weave the other half of the dough strips through the first set, over and under, pulling back the first set of strips as needed to weave. (As an alternative to the lattice crust, you can place the whole dough round on top of the pie. Cut a few slits in the center to allow steam to escape.)", Type: "HowToStep"},
						{
							Text: "Trim the edges of the pie crust so that there is a ½-inch overhang over the edge of the pie dish. Fold the overhang under and use your fingers or a fork to flute/crimp the edges of the crust as desired.",
							Type: "HowToStep",
						},
						{
							Text: "Egg wash: In a small bowl, beat together the egg and the 1 tablespoon milk. Lightly brush the top of the pie crust with the egg wash. (You will not use all of the egg wash.) If desired, sprinkle coarse sugar or granulated sugar over the top of the pie.",
							Type: "HowToStep",
						},
						{
							Text: "Bake pie at 400° F for 15 minutes, then reduce the oven temperature to 350° F and continue baking for 45-50 more minutes, until the filling is bubbly and crust is light golden brown. Begin checking on the pie at 30 minutes and cover crust edges with a pie crust shield or foil as needed to prevent over-browning.",
							Type: "HowToStep",
						},
						{
							Text: "Let pie cool for at least 2-3 hours at room temperature before slicing and serving. Store leftover pie in the refrigerator, wrapped tightly, for up to 5 days.",
							Type: "HowToStep",
						},
					},
				},
				Name: "Blackberry Pie",
				NutritionSchema: &models.NutritionSchema{
					Calories:      "402",
					Carbohydrates: "56",
					Cholesterol:   "46",
					Fat:           "18",
					Fiber:         "8",
					Protein:       "6",
					SaturatedFat:  "11",
					Servings:      "1",
					Sodium:        "152",
					Sugar:         "20",
				},
				PrepTime:  "PT35M",
				TotalTime: "PT95M",
				Yield:     &models.Yield{Value: 1},
				URL:       "https://kristineskitchenblog.com/blackberry-pie/",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:      "VideoObject",
							ContentURL:  "https://mediavine-res.cloudinary.com/video/upload/t_original/v1721052383/rm8lqyzrqklcauolhhps.mp4",
							Description: "From the sweet, juicy blackberry pie filling that's brightened with a touch of lemon to the homemade pie crust, every single bite of this blackberry pie is worth celebrating.",
							Duration:    "PT78S",
							EmbedURL:    "https://video.mediavine.com/videos/rm8lqyzrqklcauolhhps.js",
							Name:        "Blackberry Pie",
							ThumbnailURL: &models.ThumbnailURL{
								Value: "https://mediavine-res.cloudinary.com/image/upload/s--bDlCnC_r--/c_limit,f_auto,fl_lossy,h_1080,q_auto,w_1920/v1721052511/zr4sw4pivzhzstm9bixz.jpg",
							},
							UploadDate: time.Date(2024, 7, 15, 14, 10, 47, 0, time.UTC),
						},
					},
				},
			},
		},
		{
			name: "kuchnia-domowa.pl",
			in:   "https://www.kuchnia-domowa.pl/przepisy/dodatki-do-dan/548-mizeria",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "Dodatki do dań"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{Value: "Polska"},
				DateCreated:   "2020-08-27T14:21:24+02:00",
				DateModified:  "2020-08-27T14:35:56+02:00",
				DatePublished: "2020-08-27T14:32:45+02:00",
				Description: &models.Description{
					Value: "Lekka surówka do obiadu ze świeżego ogórka, śmietany lub jogurtu oraz koperku. Bardzo prosta, idealnie nadająca się do wielu dań obiadowych. Mizeria najsmaczniejsza jest z ziemniakami najlepiej młodymi i jakimś mięsem np. kotletem mielonym lub schabowym. My najbardziej lubimy kremową mizerię z miękkimi, cienkimi plasterkami ogórka doprawioną nie tylko solą i pieprzem, ale również (aby była słodko- winna) sokiem z cytryny i cukrem. A jak u Ciebie przygotowuje się mizerię?",
				},
				Keywords: &models.Keywords{Values: "przepis, mizeria, surówka z ogórków, mizeria z octem i śmietaną, tradycyjna mizeria, klasyczna mizeria, domowa mizeria"},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"600 g świeżych ogórków gruntowych (lub długich, szklarniowych)*",
						"300 g gęstej, kwaśnej śmietany 18% lub jogurtu typu greckiego",
						"1 łyżeczka soli",
						"1 łyżka soku z cytryny (lub niepełna łyżka octu jabłkowego)",
						"1 łyżeczka cukru",
						"czarny pieprz mielony",
						"1 łyżka drobno posiekanego koperku",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Ogórki umyć, osuszyć, obrać i pokroić w jak najcieńsze plasterki."},
						{Type: "HowToStep", Text: "Plasterki umieścić w misce i posypać 1 łyżeczką soli. Wymieszać i pozostawić na ok. 15 minut."},
						{Type: "HowToStep", Text: "W międzyczasie śmietanę przełożyć do miseczki. Przyprawić sokiem z cytryny, cukrem, pieprzem i posiekanym koperkiem. Wymieszać."},
						{Type: "HowToStep", Text: "Po 15 minutach odlać wodę, którą puściły ogórki. (Lekko je odcisnąć, ale nie za mocno, aby mizeria nie wyszła za sucha)."},
						{Type: "HowToStep", Text: "Dodać przygotowaną śmietanę i wymieszać."},
					},
				},
				Name:            "Mizeria",
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 4},
				URL:             "https://www.kuchnia-domowa.pl/przepisy/dodatki-do-dan/548-mizeria",
				Video: &models.Videos{
					Values: []models.VideoObject{
						{
							AtType:       "VideoObject",
							ContentURL:   "https://kuchnia-domowa.pl/dodatki/548-mizeria",
							Description:  "Lekka surówka do obiadu ze świeżego ogórka, śmietany lub jogurtu oraz koperku. Bardzo prosta, idealnie nadająca się do wielu dań obiadowych. Mizeria najsmaczniejsza jest z ziemniakami najlepiej młodymi i jakimś mięsem np. kotletem mielonym lub schabowym. My najbardziej lubimy kremową mizerię z miękkimi, cienkimi plasterkami ogórka doprawioną nie tylko solą i pieprzem, ale również (aby była słodko- winna) sokiem z cytryny i cukrem. A jak u Ciebie przygotowuje się mizerię?",
							Name:         "Mizeria",
							ThumbnailURL: &models.ThumbnailURL{Value: "https://kuchnia-domowa.pl/images/content/548/mizeria.webp"},
							UploadDate:   time.Date(2020, 8, 27, 14, 32, 45, 0, time.FixedZone("+2", 2*60*60)),
						},
					},
				},
			},
		},
		{
			name: "kuchynalidla.sk",
			in:   "https://kuchynalidla.sk/recepty/bravcova-rolada-so-syrom-a-sunkou",
			want: models.RecipeSchema{
				AtContext:     "https://schema.org",
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DatePublished: "2018-06-21T00:25:43+00:00",
				Description: &models.Description{
					Value: "Zatočte s mäsom a zasýťte hladné bruchá svojich najmilších. Pripravte im na obed bravčovú roládu so syrom a šunkou s lahodným zemiakovým pyré podľa Marcela. Budú sa zalizovať až za ušami!",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"10 plátkov bravčového karé", "morská soľ v mlynčeku Kania",
						"čierne korenie v mlynčeku Kania", "200 g prosciutto cotto Dulano Selection",
						"čerstvá šalvia", "150 g ementálu Milbona (plátky)",
						"olivový olej Primadonna",
						"hladká múka Belbake (na obalenie a do výpeku)", "1 lyžica masla Pilos",
						"100 ml suchého bieleho vína", "trochu vývaru alebo vody na podliatie",
						"1 kg zemiakov", "300 ml plnotučného mlieka Pilos", "80 g masla Pilos",
						"čerstvá pažítka", "125 g rukoly", "trochu citrónovej šťavy",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Postup"},
						{Type: "HowToStep", Text: "POTREBUJEME"},
						{Type: "HowToStep", Text: "Bravčové rolády"},
						{Type: "HowToStep", Text: "Bravčové karé prikryjeme fóliou a naklepeme na tenké plátky. Nožom narežeme okraje,"},
						{Type: "HowToStep", Text: "aby mäso počas opekania držalo svoj tvar. Ochutíme soľou a korením. Na každý plátok položíme plátok šunky, lístky šalvie a plátok syra. Zrolujeme a uzatvoríme pomocou špáradiel."},
						{Type: "HowToStep", Text: "Pripravené rolády obalíme v hladkej múke a opečieme na rozohriatom olivovom oleji"},
						{Type: "HowToStep", Text: "po celom obvode do zlatohneda. K výpeku pridáme lyžicu masla, lyžicu hladkej múky, podlejeme vínom a\u00a0trochou vody. Varíme, kým sa z vína odparí alkohol. Potom pridáme nadrobno nasekané lístky šalvie a dochutíme soľou a korením. Stiahneme z ohňa, prikryjeme pokrievkou a necháme chvíľu odpočívať."},
						{Type: "HowToStep", Text: "Zemiaková kaša"},
						{Type: "HowToStep", Text: "Umyté a očistené zemiaky nakrájame na menšie kúsky a uvaríme v osolenej vode domäkka. Potom ich scedíme. V kastróle zohrejeme mlieko spolu s maslom, ktoré postupne prilievame k uvareným"},
						{Type: "HowToStep", Text: "a scedeným zemiakom. Mixérom vymiešame hladkú kašu. Na záver dochutíme nadrobno nasekanou pažítkou."},
						{Type: "HowToStep", Text: "Servírovanie"},
						{Type: "HowToStep", Text: "Na tanier naservírujeme zemiakovú kašu a rolády nakrájané na kolieska. Pokvapkáme výpekom. Podávame spolu s rukolou, ktorú ochutíme soľou, korením, olivovým olejom a citrónovou šťavou."},
					},
				},
				Name:            "Bravčová roláda so syrom a šunkou",
				NutritionSchema: &models.NutritionSchema{},
				PrepTime:        "PT1H0M",
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools: &models.Tools{
					Values: []models.HowToItem{
						{Type: "HowToTool", Text: "tĺčik na mäso", Quantity: 1},
						{Type: "HowToTool", Text: "potravinovú fóliu", Quantity: 1},
						{Type: "HowToTool", Text: "špáradlá, mixér", Quantity: 1},
						{Type: "HowToTool", Text: "panvicu s\u00a0pokrievkou", Quantity: 1},
					},
				},
				Yield: &models.Yield{Value: 5},
				URL:   "https://kuchynalidla.sk/recepty/bravcova-rolada-so-syrom-a-sunkou",
				Video: &models.Videos{},
			},
		},
		{
			name: "kwestiasmaku.com",
			in:   "https://www.kwestiasmaku.com/przepis/muffiny-czekoladowe-z-maslem-orzechowym",
			want: models.RecipeSchema{
				AtContext:     atContext,
				AtType:        &models.SchemaType{Value: "Recipe"},
				Category:      &models.Category{Value: "uncategorized"},
				CookingMethod: &models.CookingMethod{},
				Cuisine:       &models.Cuisine{},
				DateModified:  "2022-11-05T09:43:22+01:00",
				DatePublished: "2022-03-24T19:55:17+01:00",
				Description: &models.Description{
					Value: "Mocno kakaowe muffiny wzmocnione dodatkową dawką czekolady w postaci dropsów czekoladowych (lub posiekanej czekolady). Dla miłośników masła orzechowego dodajemy do nich po łyżeczce masła orzechowego i rozprowadzamy je w czekoladowej masie za pomocą wykałaczki.\nZ przepisu otrzymamy od 14 do 16 muffinków. Nakładamy do foremek tyle ciasta aby nie wypływało na zewnątrz podczas pieczenia i nie robił się \"grzybek\". W związku z tym, że możemy mieć różne wielkości foremek, najlepiej wypełniać foremki surowym ciastem do 2/3 ich objętości. Pozostawiamy w ten sposób miejsce na wyrośnięcie ciasta i otrzymamy kształtne babeczki.\n",
				},
				Keywords: &models.Keywords{},
				Image:    &models.Image{Value: anUploadedImage.String()},
				Ingredients: &models.Ingredients{
					Values: []string{
						"150 g masła",
						"150 g dropsów czekoladowych (np. z ciemnej czekolady) lub 150 g czekolady deserowej lub gorzkiej",
						"300 g mąki",
						"2 łyżeczki proszku do pieczenia",
						"1/2 łyżeczki sody oczyszczonej",
						"3 łyżki kakao",
						"1 szklanka (200 g) cukru",
						"1 łyżka cukru wanilinowego",
						"2 duże jajka (L)",
						"200 ml mleka",
						"ok. 5 - 6 łyżek masła orzechowego",
						"15 - 18 papilotek",
						"metalowa forma na muffiny z wgłębieniami",
					},
				},
				Instructions: &models.Instructions{
					Values: []models.HowToItem{
						{Type: "HowToStep", Text: "Piekarnik nagrzać do 180 stopni C.\u00a0Masło roztopić i przestudzić. Czekoladę pokroić na kawałeczki."},
						{Type: "HowToStep", Text: "Mąkę przesiać do miski razem z proszkiem do pieczenia, sodą i kakao, dokładnie wymieszać. Dodać cukier oraz cukier wanilinowy i ponownie wymieszać."},
						{Type: "HowToStep", Text: "W drugiej misce rozmiksować jajka z mlekiem (rózgą lub mikserem)."},
						{Type: "HowToStep", Text: "Do sypkich składników dodać masę jajeczną i krótko zamieszać łyżką. Dodać roztopione masło i wymieszać do połączenia składników, pod koniec dodając 2/3 ilości dropsów czekoladowych."},
						{Type: "HowToStep", Text: "Masę wyłożyć do papilotek umieszczonych w formie na muffiny, na wierzch wyłożć po łyżeczce masła orzechowego na każdą muffinkę."},
						{Type: "HowToStep", Text: "Wykałaczką zrobić \"ósemkę\" w cieście mieszając delikatnie masę czekoladową z masłem orzechowym. Wierzch posypać pozostałą 1/3 dropsów czekoladowych."},
						{Type: "HowToStep", Text: "Wstawić do piekarnika (można piec na raty, w 2 partiach) i piec\u00a0przez około 20 -\u00a023 minuty, do suchego patyczka."},
					},
				},
				Name:            "Muffiny czekoladowe z masłem orzechowym",
				NutritionSchema: &models.NutritionSchema{},
				ThumbnailURL:    &models.ThumbnailURL{},
				Tools:           &models.Tools{Values: []models.HowToItem{}},
				Yield:           &models.Yield{Value: 15},
				URL:             "https://www.kwestiasmaku.com/przepis/muffiny-czekoladowe-z-maslem-orzechowym",
				Video:           &models.Videos{},
			},
		},
	}
	for _, tc := range testcases {
		t.Run(tc.name, func(t *testing.T) {
			test(t, tc)
		})
	}
}
